### ISSUE TITLE
Android wear 'flat tire' screen 

### ISSUE THREAD

**Issue by joostjdj** [domoticz/domoticz-android#106]
To add one more issue, 'the flat' tire is still visible on non round not Moto watches. On the top it scrolls nicely with fade in/out, at the bottom the switches will pop in behind the 'flat tire'.

http://i.imgur.com/g9nTYmw.png

+
I don't think you need to keep the flat tire at all since it doens't do anything different for the watches, also not for Moto because that part will not be displayed by default because there is no screen. (maybe also an improvement that all switches shown on screen can be switched)

**Comment by galadril** [comment]
I've reworked some layouts for wear. 
Is the still a problem with alpha?

**Comment by RoadXY** [comment]
He is a Alpha tester.

**Comment by joostjdj** [comment]
Issue solved. Great work!

**Comment by joostjdj** [comment]
This is just an ecstatic tip, make the switches for wear also "card" style like the app and material design.

**Comment by RoadXY** [comment]
Created a new issue for the tip: https://github.com/domoticz/domoticz-android/issues/134
