### ISSUE TITLE
A button for groups instead of a switch

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#108]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&start=560#p70876

by maluko » Tue Jan 19, 2016 4:27 pm

this is quite equal that i said about group button.

group don't seem to be the solution, because Domoticz has 2 button (on and Off), and on app it has a slide button so you cant push off or on twice.
Help me understand. Why do you need to push on twice?

yes, like i said:

i have a scene with :
blind A- close
Blind B- open
Blind C- Close
Blinde D- Open
if they are all close only open B/D but if all open, the A/C goes closed, then if i want close/open all when are mixed?

i had a group with all blind that in Domoticz i can click on or off when they are mixed, that not happen on app because if the status of group on app are off and the blind are mixed how can i close? have to open group and then close? or close every blind individual?

**Comment by galadril** [comment]
Think we can close this case then ;-)

**Comment by RoadXY** [comment]
Yes :-)
