### ISSUE TITLE
Security panel pin code always wrong

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#109]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=70998#p70911

by pluggin » Tue Jan 19, 2016 8:10 pm

I have some protected sensors and when I put the PIN on the panel always tell me "incorrect pin" but all works fine via Domoticz front end web.
Is this a malfunction or something else?

**Comment by galadril** [comment]
protected devices are not supported your on the prod version of this app.. only in alpha :-)
So how does he test this?

The only device that allows a Pincode is the Security Panel ?

**Comment by RoadXY** [comment]
Hmm, sorry I didn't think of that. Will change my reply on the forum

**Comment by RoadXY** [comment]
Done.
Will leave this open until he replied.

**Comment by galadril** [comment]
:+1:

**Comment by RoadXY** [comment]
One issue though: when trying to switch a protected switch, while entering the wrong code, still flips the switch in the app.
After refresh the switch is back to it's original state from before.

**Comment by RoadXY** [comment]
He ment the security panel:
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=71039#p71039

Asked if it's always wrong because I've tried and all seems fine.

**Comment by galadril** [comment]
I don't see the problem at my setup...

If i specify a pincode within the settings of Domoticz, it also works in the app.!

**Comment by RoadXY** [comment]
I'll ask Remco and Joost to test

**Comment by galadril** [comment]
Not an issue.. closing case
