### ISSUE TITLE
Set button should be made smaller

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#110]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=70998#p70996

by pepeEL » Wed Jan 20, 2016 12:39 pm

I think that button SET should be change size to small size. Now is too big

**Comment by RoadXY** [comment]
I do agree with pepeEl on this.
Whats your thoughts on this @galadril?

**Comment by galadril** [comment]
We could make them smaller.. but we've an issue with translations.
In some translations the words are bigger, in some smaller..

So how do get fit all that information in one button ...

**Comment by RoadXY** [comment]
We could check since I've created a first version of language change in the app.
Or could use a image for it instead of a word?

**Comment by pp1984** [comment]
Maybe change size font or user must done short translation
