### ISSUE TITLE
Create a widget, separate app, launcher icon for security panel

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#114]
So your tablet mounted on the wall can be used for arming Domoticz security.

I prefer an Activity which has the intent filter:

<intent-filter>
  <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>

So it creates a separate launcher icon from which the security panel activity can be started directly.
And use the bootup receiver broadcast to start this activity when specified by the user.
Also we can set the activity to be full screen.

**Comment by galadril** [comment]
Security panel implemented

![widgets](https://cloud.githubusercontent.com/assets/14561640/21936564/e2515210-d9b1-11e6-9bfd-e76b4d72fef5.png)
