### ISSUE TITLE
Add "Week" as option for graphs

### ISSUE THREAD

**Issue by sonar98** [domoticz/domoticz-android#116]
At this moment it is possible to see the graph for a day, a month or a year.
Is it possible to add an option for Week-graphs?

**Comment by joostjdj** [comment]
Good comment. I even think it will be more convenient and ecstatically pleasing that you have one 'graph button' below the sensor, and in the pop-up which actually shows the data you will be able to switch between day, week, month and year. 
This way you keep the main screen clean of options.

**Comment by RoadXY** [comment]
Did some testing and the server supports week as request for data. If I got some spare time I'll try and implement week as a view

**Comment by galadril** [comment]
![screenshot_20160204-153659](https://cloud.githubusercontent.com/assets/14561640/12818179/01a4bc44-cb56-11e5-9c43-e885b6447c4c.png)

I now show the extra log/graph buttons below the Row when you click on the row.
If you click on another row, the log/graph buttons of the previous one get's removed again

(with some nice animations)

![screenshot_20160204-153705](https://cloud.githubusercontent.com/assets/14561640/12818209/2291fd90-cb56-11e5-82d8-31afc6b112d6.png)

Im not really happy with the buttons yet.. but it's looking better and better :+1:

**Comment by galadril** [comment]
At this moment we just show all 4 (day, week, month, year) buttons for the graph rows..
But most of the rows don't have week data..

How can we filter those types and then make the week button not appear??

**Comment by RoadXY** [comment]
Enhanced it a little and changed the color of the buttons

**Comment by sonar98** [comment]
Looks promissing... is there a way to test an alpha build?

**Comment by RoadXY** [comment]
You can build it yourself or wait for the alpha (if you opted in and bought the premium)

**Comment by galadril** [comment]
Think we can close this for now...
