### ISSUE TITLE
Bad french traduction of SecPannel buttons

### ISSUE THREAD

**Issue by pbda** [domoticz/domoticz-android#119]
Arm Home -> Désactiver
Arm Away -> Activer
Disarm -> Désarmer 

should be

Arm Home -> "Armer partiel" or shorter "Arm. tot."
Arm Away -> Armer total" or shorter "Arm.part."
Disarm -> Désarmer 

"Désarmer" and "Désactiver" means same thing, it's confusing.

**Comment by galadril** [comment]
You can change the French translations at Crowdin:
https://crowdin.com/project/domoticz-for-android
