### ISSUE TITLE
While at search and change status, results are gone

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#12]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=68210#p68184

by dijkdj » Mon Jan 04, 2016 11:10 pm

Found one "bug". If you search for a switch and you change the status of this switch the search results are gone while the search window is still filled.

**Comment by galadril** [comment]
This is already fixed:
https://github.com/domoticz/domoticz-android/commit/3888c40743a7044284d0549cae9fd66f9c1a4992
