### ISSUE TITLE
Camera image refresh rate

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#121]
Maybe add a 'play'-menuitem button on the Cameras screen to start an auto refresh cycle?
And maybe just a single refresh button?

**Comment by RoadXY** [comment]
Seems logical to me. Still need to implement camera's in my Domoticz :(

**Comment by galadril** [comment]
I've added play and pause in the actionbar.
Play starts a refresh of the camera's every 5 seconds

![1](https://cloud.githubusercontent.com/assets/14561640/12533520/fc7cb672-c231-11e5-9307-77b8e7c1af43.png)
![2](https://cloud.githubusercontent.com/assets/14561640/12533519/fc7b2104-c231-11e5-92ec-80ed84f136ed.png)

**Comment by RoadXY** [comment]
Nice one! :+1:

**Comment by RoadXY** [comment]
It's not possible to get a reference of the action bar inside the camera's fragment?

**Comment by galadril** [comment]
Think we can close this one for now.
It's possible to get the reference in the fragment, 

but I have a better handling of timers if I do it in the MainActivity, so I now stop the timer if MainActivity switches fragment, etc..

**Comment by RoadXY** [comment]
Ok
