### ISSUE TITLE
List on wear "card" style

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#134]
@joostjdj requested this here: https://github.com/domoticz/domoticz-android/issues/106
This is just an ecstatic tip, make the switches for wear also "card" style like the app and material design

**Comment by RoadXY** [comment]
What do you guys think @galadril and @remb0

**Comment by remb0** [comment]
Larger  = more scrolling.   
But I agree to some changes in design.

**Comment by RoadXY** [comment]
The icons should fit inside the current size of a row so it stays the same

**Comment by joostjdj** [comment]
I think there is a lot more room that can be used. Or you can put 4 switches per 'page' or you can make the icons and text bigger. At least you can add cards.

[http://i.imgur.com/rud8MFp.png]

**Comment by RoadXY** [comment]
For square it's not as bad as round, it seems

![device-2016-01-26-145341](https://cloud.githubusercontent.com/assets/3482284/12582306/971494a0-c43c-11e5-83e4-44139e3572e0.png)

**Comment by joostjdj** [comment]
No extra space indeed for square, but enough space for cards it seems

**Comment by galadril** [comment]
we could do a pager.. 

page: Switches you specify via settings of that are favorite
page: Switches 
page: Scenes
page: Utilities

etc.. like the app

**Comment by joostjdj** [comment]
Completely agree! There is already a topic for this: https://github.com/domoticz/domoticz-android/issues/24

It would be really nice to be able to set the sorting as well.
So a Dashboard with switches, scenes, utilities which you can add and sort yourself. And pages on the right for switches, scenes etc.

**Comment by RoadXY** [comment]
I agree on the sorting.
The use case for your watch is totally different then your phone and your laptop/pc with web browser.

On the small screen on your watch I'd like to use this as efficient as possible.

**Comment by joostjdj** [comment]
It would also be a nice feature to add thermostat support, so one screen with the same thermostat interface as the app

**Comment by remb0** [comment]
Agree on pages and thermostat.    For lots of people smartwatch is and very nice extra
