### ISSUE TITLE
Tasker integration

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#138]
Since some requested: tasker plugin

More on this here:
http://tasker.dinglisch.net/developers.html

**Comment by joostjdj** [comment]
Good idea, but I think this is more of a later project. 
If you want to correctly implement tasker support it will cost a lot of work probably.
But it will be really nice.

**Comment by galadril** [comment]
Im splitting this off to another project
https://www.domoticz.com/forum/viewtopic.php?f=37&t=32696&p=247531#p247531

**Comment by galadril** [comment]
Some first results:

![Screenshot_2020-05-15-16-06-49-790_nl hnogames domoticz tasker](https://user-images.githubusercontent.com/14561640/82059440-53b0ad00-96c6-11ea-9905-3d52199b020b.jpg)
![Screenshot_2020-05-15-15-56-01-110_net dinglisch android taskerm](https://user-images.githubusercontent.com/14561640/82059441-54494380-96c6-11ea-9443-33892ecfd308.jpg)
![Screenshot_2020-05-15-16-06-39-719_net dinglisch android taskerm](https://user-images.githubusercontent.com/14561640/82059443-54e1da00-96c6-11ea-8aca-f90e5794fe3a.jpg)
![Screenshot_2020-05-15-16-06-46-446_net dinglisch android taskerm](https://user-images.githubusercontent.com/14561640/82059445-557a7080-96c6-11ea-9c15-3a3361869049.jpg)

**Comment by galadril** [comment]
And ive added an action for setting the state of an event in domoticz:

![Screenshot_2020-05-15-16-48-48-037_nl hnogames domoticz tasker](https://user-images.githubusercontent.com/14561640/82063786-367edd00-96cc-11ea-8677-52112a05dde5.jpg)
![Screenshot_2020-05-15-16-48-28-850_net dinglisch android taskerm](https://user-images.githubusercontent.com/14561640/82063790-37177380-96cc-11ea-9d50-fb54860f394f.jpg)
![Screenshot_2020-05-15-16-48-38-335_net dinglisch android taskerm](https://user-images.githubusercontent.com/14561640/82063792-37b00a00-96cc-11ea-95e8-0fab4bf6d256.jpg)

**Comment by galadril** [comment]
Also added the action to write a log to domoticz

![image](https://user-images.githubusercontent.com/14561640/82083697-705edc00-96ea-11ea-939e-4b60b68013ca.png)

![image](https://user-images.githubusercontent.com/14561640/82083704-748af980-96ea-11ea-869d-cc54dd769b9b.png)

**Comment by galadril** [comment]
Also implemented the possibility to set a user variabele
![Screenshot_2020-05-16-16-46-41-350_nl hnogames domoticz tasker](https://user-images.githubusercontent.com/14561640/82127293-b4b5af00-97b2-11ea-8de9-564ce1f3cf11.jpg)
![Screenshot_2020-05-16-20-19-25-689_net dinglisch android taskerm](https://user-images.githubusercontent.com/14561640/82127294-b54e4580-97b2-11ea-9c8d-c4fee15c3912.jpg)

**Comment by galadril** [comment]
I've also implemented an generic json endpoint option.. if you want some specific call to be done via api.. for example vacuum the database every night

![image](https://user-images.githubusercontent.com/14561640/82160484-06833580-9896-11ea-95b2-8eb2bc97d605.png)

![image](https://user-images.githubusercontent.com/14561640/82160487-07b46280-9896-11ea-9bb0-3a27cce93e45.png)

**Comment by galadril** [comment]
Also got a first version with websockets realtime switch changes as Tasker input

![image](https://user-images.githubusercontent.com/14561640/82228463-72fb4480-9929-11ea-8f35-ff1c85a50fb7.png)

![image](https://user-images.githubusercontent.com/14561640/82228471-768ecb80-9929-11ea-9819-24214ff0e239.png)

**Comment by galadril** [comment]
FYI a first release is available in the store
https://play.google.com/store/apps/details?id=nl.hnogames.domoticz.tasker

**Comment by rezzalex** [comment]
Hello @galadril 

It seems the "on Switch Changed" event is not detected anymore, it seems to have worked previously...
I am using Tasker 6.1.32

What did I missed ?
