### ISSUE TITLE
Support for multiple Domoticz Servers

### ISSUE THREAD

**Issue by GrmpCerber** [domoticz/domoticz-android#150]
Background: I'm in the process of deploying a new Domoticz instance at my parent's home.
Do you think it would be a nice addition to domoticz-android  to be able to manage multiple servers from the same client ?
(Or is this just very specific to me)

**Comment by galadril** [comment]
I've already started to do some work for this:
https://github.com/domoticz/domoticz-android/commit/9f73c761a29fd010ff4f162c5c536ddfae4ce996

**Comment by joostjdj** [comment]
Nice =), in the meantime you can also add the extra Domoticz instance to your own as a slave/remote domoticz client.

**Comment by galadril** [comment]
Added support for multiple servers v1
https://github.com/domoticz/domoticz-android/commit/0c604dde54c5a8063a0f421869640fb0ee2c237a

![2](https://cloud.githubusercontent.com/assets/14561640/12713705/7ef66450-c8d0-11e5-8858-162f329138f7.png)
![3](https://cloud.githubusercontent.com/assets/14561640/12713704/7ef39f5e-c8d0-11e5-822c-d6fd058c148a.png)
![1](https://cloud.githubusercontent.com/assets/14561640/12713703/7ef1d1c4-c8d0-11e5-9e87-ae9e6f779e9c.png)

**Comment by RoadXY** [comment]
Nice!
Could we use a single choice dialog for server selection?
https://github.com/afollestad/material-dialogs#single-choice-list-dialogs 

I can change to that, if agreed off course, tonight?

**Comment by galadril** [comment]
Think this is good enough for now, to close this issue right?
Then we can enhaunce this later with extra features??

**Comment by RoadXY** [comment]
Agreed!
