### ISSUE TITLE
List view Geofencs settings scrolling performance not optimal

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#16]
List view Geofencs settings scrolling performance is not optimal.

**Comment by galadril** [comment]
Is improved a lot by not getting address information in the adapter . getView method.
https://github.com/domoticz/domoticz-android/commit/1328a13e62df1e8bfe0cf9f6823cc6a0d13361c6

Close this case??

**Comment by RoadXY** [comment]
Saw that and tested it, super fast now!
Forgot to close
