### ISSUE TITLE
Geofence - optimise layout for tablet

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#164]
![screenshot_20160203-170631](https://cloud.githubusercontent.com/assets/3482284/12788132/af0f269e-ca98-11e5-91fe-76cb9664b47e.png)

**Comment by galadril** [comment]
Reworked the row:
![geo_row](https://cloud.githubusercontent.com/assets/14561640/12810264/59104146-cb25-11e5-87d3-e014c85af235.png)
