### ISSUE TITLE
Server update - optimise layout for tablet

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#165]
Text layout is not inline with rest

![screenshot_20160203-164315](https://cloud.githubusercontent.com/assets/3482284/12790852/a0447da6-caa4-11e5-8a0a-14547607552c.png)

**Comment by galadril** [comment]
I don't really see the problem here ..

**Comment by RoadXY** [comment]
The text behind the dialog and the button behind the dialog aren't aligned.
Saw this when the dialog was already there but it hasn't got anything to do with it, lol.

**Comment by galadril** [comment]
old case
