### ISSUE TITLE
Stack notifications if multiple are unread

### ISSUE THREAD

**Issue by remb0** [domoticz/domoticz-android#169]
my battery was empty of a temp zwave sensor. So domoticz send me 6 notifications at once trough pushover.
But the notification in the app shows me only 1 notification that time.

And in pushover you see a notification history which is very handy sometimes.  maybe this is an idea for the app.

**Comment by RoadXY** [comment]
I found this issue as well and intended to create an issue for it as well.
The current running notifications text should be extended with the new incoming notification.

**Comment by galadril** [comment]
Or make it a setting..
Overwrite previous notifications or Create new ones?

**Comment by RoadXY** [comment]
http://developer.android.com/design/patterns/notifications.html#guidelines

Under: "Summarize your notifications"

"If a notification of a certain type is already pending when your app tries to send a new notification of the same type, combine them into a single summary notification for the app. Do not create a new object.

A summary notification builds a summary description and allows the user to understand how many notifications of a particular kind are pending."

But that would mean we have to create a notification activity...

**Comment by galadril** [comment]
"Lock screen notifications for Android L will make it easier for users to see which notifications they received and if they are worth unlocking their phone. By setting metadata on notifications Android will be able to better sort notifications, so notifications will become more relevant for the user. The features introduced in L aren’t in the support library yet, so making use of these features already isn’t easy. I would recommend waiting until these features are available in the support library. "

**Comment by galadril** [comment]
I've done the easy fix for now..
We'll look for a nice Android 'L' notification solution !
