### ISSUE TITLE
Add selector switch type

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#17]
Add support for selector switch type:
![selector](https://cloud.githubusercontent.com/assets/14561640/12139422/c854e664-b460-11e5-8c96-c75ece661f4f.png)

Info about selector:

json calls for settings status:
OFF: /json.htm?type=command&param=switchlight&idx=203&switchcmd=Set%20Level&level=0
Level1: /json.htm?type=command&param=switchlight&idx=203&switchcmd=Set%20Level&level=10
Level2: /json.htm?type=command&param=switchlight&idx=203&switchcmd=Set%20Level&level=20
Level3: /json.htm?type=command&param=switchlight&idx=203&switchcmd=Set%20Level&level=30

devices json:
 {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "02030000",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-01-06 10:33:24",
         "Level" : 0,
         "LevelInt" : 0,
         "LevelNames" : "Off|Level1|Level2|Level3",
         "MaxDimLevel" : 100,
         "Name" : "TestSelector",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "203"
      }

**Comment by galadril** [comment]
Added!

**Comment by nayrnet** [comment]
wikid: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Selector_Switch

**Comment by RoadXY** [comment]
Nice. Thanks
