### ISSUE TITLE
Change line graph to bar/column graph for gas/electricity

### ISSUE THREAD

**Issue by ThinkPadNL** [domoticz/domoticz-android#18]
The current graph for gas/electricity usage (from P1 smart meter) uses a line graph for the month and year usage. However, these graph are not easily readable.

In Domoticz a bar/column graph is used for this kind of view. It would be nice if the app would also use these kind of charts, for a much better readability

**Comment by sonar98** [comment]
I would like the graphs in the app to resemble the graphs in domoticz more.

**Comment by galadril** [comment]
Graphs are changed a lot in last 3 months..
