### ISSUE TITLE
Logs for smoke detector not working

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#184]
https://www.domoticz.com/forum/viewtopic.php?p=73918&sid=e911f4ebcf03abffe68d812f7d094c2e#p73932

by Jango » Sun Feb 07, 2016 6:25 pm

Logs for smoke detector not working

**Comment by RoadXY** [comment]
The same user as #185 
Already asked hem access to his server

**Comment by galadril** [comment]
And? Does it actually has a log in Domoticz system?

**Comment by RoadXY** [comment]
Have been working on the SeekArc. The next thing I'm focused on will be logs for smoke detectors.

**Comment by galadril** [comment]
That was not my intention.. I think that the log just works.
But that there is not log to show from the system

**Comment by RoadXY** [comment]
Oh, ok.
I've lost access to his server.
Send another PM on the forum to him.

**Comment by RoadXY** [comment]
Had a day access but lost access again.
Already send another PM.

**Comment by RoadXY** [comment]
Got access again. Appears that also the server hasn't got any logs.
Awaiting user answer

**Comment by galadril** [comment]
just like i said right ;)

**Comment by RoadXY** [comment]
Seems like it, yes. :-D
Send an screenshot of the empty smoke detector to the user to see if he got the same.

**Comment by RoadXY** [comment]
Solved. User expected to see an empty graph.
