### ISSUE TITLE
Magnetic open / close relays now show as switches

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#185]
https://www.domoticz.com/forum/viewtopic.php?p=73918&sid=e911f4ebcf03abffe68d812f7d094c2e#p73933

by Jango » Sun Feb 07, 2016 6:39 pm

Magnetic open / close relays now showed as switches with on/off function selection. This is not necessary for these types.

**Comment by RoadXY** [comment]
The same user as #184 
Already asked hem access to his server

**Comment by galadril** [comment]
You've fixed this issue right?
https://github.com/domoticz/domoticz-android/commit/ad982fff857559080c43f3129d299c2bc6799f07

**Comment by RoadXY** [comment]
Could use some testing but should be solved.
