### ISSUE TITLE
Thermostat setpoint jumps around

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#186]
More info and screenshots:
https://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&start=660#p73942

Steps to reproduce:

- Current setpoint: 16,5
- Click SET button (dialog opens)
- Setpoints displays as 17
- Click + button
- Setpoint value in dialog shows 17,5
- Click ok button
- Setpoint in app and server show 17,5

**Comment by kivster** [comment]
I can re-produce this also.

Current setpoint: 21'C
Click SET button (dialog opens)
Setpoints displays as 20.5'C
Click + button
Setpoint value in dialog shows 21'C
Click ok button
Setpoint in app and server show 21.5'C
Click SET button again (dialog opens)
Setpoint value in dialog shows 21'C

Reducing the setpoint by clicking the - button shows similar 0.5'C variations but in the negative direction.

**Comment by RoadXY** [comment]
Should be solved now in alpha

**Comment by galadril** [comment]
Nice!
