### ISSUE TITLE
Somfy roller shutters not showing current status

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#194]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=74949#p74910

PostSun Feb 14, 2016 11:38 am by bitjeverkeerd

Even with "instellingen/extra gegevens op.." "AAN" it's still not visible if the screens are open or closed.

**Comment by galadril** [comment]
the problem is that it takes a couple of seconds before Domoticz base system shows open or closed on the web ui.

In the app we call the action command, and refresh.. 
Maybe we need to wait for 2 seconds before refreshing?

**Comment by galadril** [comment]
Old case.. think we refresh now when we have the callback 

so this can be closed..
