### ISSUE TITLE
always on  (for a tablet on the wall)

### ISSUE THREAD

**Issue by remb0** [domoticz/domoticz-android#2]
xKingx from tweakers.net:

Hallo,

Ik zat te denken om een oude tablet te gebruiken als bedienings paneel voor mijn Domoticz setup. Om dit altijd beschikbaar te hebben zou een "always on" optie wellicht een mogelijkheid kunnen zijn zodat het scherm niet uitschakeld en je op de en of andere toch weer moet inloggen / aanzetten etc. Eventueel zou dit ook met een klok kunnen. Aan overdag, uit 's nachts, aan voor 2, 10, 15, 30 minuten etc.

**Comment by galadril** [comment]
Added this feature on alpha
