### ISSUE TITLE
Lost Humidity on Temperature tab, instead of that all of my Temp sensors have Setpoint

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#202]
http://domoticz.com/forum/viewtopic.php?p=75247&sid=66b18533a46bb7cdae3e77b9921e69af#p75247

by LouiS22 » Tue Feb 16, 2016 11:16 am

With the latest beta, I've lost Humidity on Temperature tab, instead of that all of my Temp sensors have Setpoint. What's more strange: there are a few Favourite temp/hum sensors placed on Dashboard, they now have Temp and hum, dew point, another temp (with round values (for ex 21C)), and humidity with text format (for ex wet).

![screenshot_2016-02-16-10-14-59](https://cloud.githubusercontent.com/assets/3482284/13072029/67e1d740-d497-11e5-921d-9d893cefc96c.png)

**Comment by galadril** [comment]
We've indeed expanded the information on the Dasboard page.
We now show more if it's available in the Device json

**Comment by RoadXY** [comment]
But should it show a setpoint for every temp item?

**Comment by RoadXY** [comment]
???
