### ISSUE TITLE
Implement mydomoticz.com

### ISSUE THREAD

**Issue by remb0** [domoticz/domoticz-android#21]
The new service:   mydomoticz

https://my.domoticz.com/mydomoticz/login
chimit will and can help us to implement this great new feature.

**Comment by rkluwen** [comment]
Sure, I already cloned the code locally.
I don't have much time now the new year is starting and everybody wants their projects running. But yes, I could come up with a pull request some time.

**Comment by RoadXY** [comment]
I assume your chimit on the forum then?

**Comment by remb0** [comment]
true.

**Comment by galadril** [comment]
@rkluwen do you have some time for this implementation?

**Comment by galadril** [comment]
@rkluwen do you have some time for this implementation?
Would love to integrate my.domoticz.com on the app

**Comment by chatis** [comment]
Hello, 

I also have the same problem... I'm myself developper. If you don't have time to do it, can you tell me where in the code I can check to help on it ?

Because I really really need it as soon as possible... I'm moving in a new home without a provider giving me a way to open port for outside connection

**Comment by galadril** [comment]
I would love to do this, but i need the dev of mydomoticz to work with me.

**Comment by galadril** [comment]
@rkluwen could i implement myDomoticz into the mobile apps?? can I route all the api's through myDomoticz?
Can you assist me?

**Comment by chatis** [comment]
Perhaps @gizmocuz could help with that too?

**Comment by galadril** [comment]
@rkluwen how are your? still going strong with my.domoticz.com?
Can we implement this in the app??

**Comment by chatis** [comment]
> @rkluwen how are your? still going strong with my.domoticz.com?
> Can we implement this in the app??

Yeah it should very helpfully
