### ISSUE TITLE
Widgets - wrong buttons/switches

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#214]
https://www.domoticz.com/forum/viewtopic.php?p=75552&sid=8d7788beff5a85cf984df121adf9e83d#p75552

by StanHD » Thu Feb 18, 2016 5:45 pm

Widgets that have changed since Playstore Update today:-

Version 0.1.234 (paid version)
Galaxy S6 Edge
Android 5.1.1

![screenshot_2016-02-18-15-28-23](https://cloud.githubusercontent.com/assets/3482284/13212677/5d0ac862-d943-11e5-9a6a-da4d60302c26.png)

The top Widget functions as expected and turns a group On & Off.
The wide Widget is a Selector which appears to "inherit" the "Off" button from the top switch. If used it performs that function - "All Lighting Auto Off"
The other 2 Widgets both appear to "inherit" the same "off" button from the top switch, thus setting "All Lighting Auto Off".

The off buttons do not appear immediately when the Widget is created but a short time after.

**Comment by galadril** [comment]
I've reworked alot for widgets in the last release!
Think it's just a matter of recreating the widgets

![selectorwidget](https://cloud.githubusercontent.com/assets/14561640/13213873/351882d2-d94c-11e5-9a43-a5faec513808.png)


Selectors are readyonly widgets at this moment
(the top widget in my example screen is a selector)

**Comment by RoadXY** [comment]
Asked the user to recreate them:
https://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=76135#p76135

**Comment by galadril** [comment]
Think this is already fixed..
