### ISSUE TITLE
GCM - Check if server supports GCM notifications

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#215]
https://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=76102#p75734

by asjmcguire » Sat Feb 20, 2016 6:39 am

I'm just wondering. The Play Store page says the update features GCM notifications, I see a bit in the settings for GCM but when I press the option to push my registrationid to domoticz I just immediately get a message that "could not save your registration id in Domoticz". What am I missing? I'm now running version v2.4625 of Domoticz and version 0.1.234 of the app.

**Comment by galadril** [comment]
at this moment, the AddMobileDevice method from the Domoticz class just gets the next json result:

```
{
   "status" : "ERR"
}
```

Maybe we should just pust the mobile device UUID every times when the app starts. (request by Rob, so he sets the lastseen datetime in Domoticz for that device).

Then it doesn't do anything when the server doesn't support it.. but when it does support notifications you have a lastseen date per device

**Comment by RoadXY** [comment]
Did "AddMobileDevice" ever work?

**Comment by galadril** [comment]
You're receiving GCM Notifications right..?
So yes the AddMobileDevice method works :+1: 

but we should call that more then once per install/update apk

**Comment by RoadXY** [comment]
AppController.getInstance().StartEasyGCM(); is already in MainActivity so that's already fixed.

**Comment by galadril** [comment]
no
the method 'sendRegistrationIdToBackend' is now only called when an ID is newly generated by Google (after apk update or now install)..

**Comment by RoadXY** [comment]
Aha.
