### ISSUE TITLE
Change graphs from dialog to activity

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#216]
Since we have multiple issues with a dialog we should change to an Activity for logs.
Another advantage is that more screen space is used when using an Activity.

**Comment by RoadXY** [comment]
Related:
Issue #160
Issue #153

**Comment by galadril** [comment]
I've reworked this dialog to an activity
(no functional changes yet...)

**Comment by RoadXY** [comment]
Nice!

**Comment by galadril** [comment]
Added filter feature to the Graph activity.

![1](https://cloud.githubusercontent.com/assets/14561640/13349471/563d507e-dc7a-11e5-8a10-13a01b71c154.png)

![2](https://cloud.githubusercontent.com/assets/14561640/13349472/57f98068-dc7a-11e5-960e-8816ec1f67f1.png)

**Comment by galadril** [comment]
## Question of the day...
Which taskbar-icon do you see in my screenshot ;-) (the castle one :+1: )

haha
