### ISSUE TITLE
NFC integration

### ISSUE THREAD

**Issue by remb0** [domoticz/domoticz-android#23]
nfc stickers to activate scenes or switches.
dromotica has this option in the paid version, and some users bought it because of this function.

a example scenario:
nfc sticker near my bed can activate the scene everything off.

**Comment by rkluwen** [comment]
Yeah, pretty cool. I'm not sure if this is the place to discuss this. But possibly the Domoticz app can even be added as "Hardware" in Domoticz, so you can use the NFC controller and other sensors that your device might have in Domoticz.

**Comment by RoadXY** [comment]
I prefer not to discuss this here.
Please continue discussion on the hardware exchange here: https://github.com/domoticz/domoticz-android/issues/25

**Comment by galadril** [comment]
Implemented in Alpha: 
https://github.com/domoticz/domoticz-android/commit/e11640cec7521476bbb3011fe526c905fec97ccc
