### ISSUE TITLE
Geofence - keep retrying to set switch on error/timeout

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#240]
http://www.domoticz.com/forum/viewtopic.php?p=77233&sid=da90d2c031d19df1f96b3f4132780a4f#p77400

by MarcelMAH » Tue Mar 01, 2016 8:07 pm

Today my cable connection got upgraded again, which broke my connection until I rebooted my router.
I connect using Domoticz app on me and my wife's phone using NAT loopback (so I use my external URL also when I'm on my internal WiFi).

Me and my wifi both use geofencing to control is someone is home / nearby which controls my central heating.

She left before I did when the local Internet was still down. She did not trigger the virtual switch that she left home.
When I woke up I first rebooted my router so when I left my virtual switch did switch but I noticed the heating not turning off.

I would expect Domoticz app to keer retrying to switch (with increased interval, to maximum of every hour?) so when this happens it would rectify itself when both are online again (and the interval timer triggers a resend).

**Comment by galadril** [comment]
So we need to stack action commands.. first in first out.. ?

**Comment by RoadXY** [comment]
Yes, I guess.

**Comment by galadril** [comment]
i dont wanna retry on calls from geofences.. 
what if a call gets retried for x-times because of lack of network.. but if triggers when we're outside range already...
