### ISSUE TITLE
Tablet - Should not use back/home arrow

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#244]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&e=1&view=unread#p78087

Postby marktn » Sat Mar 05, 2016 8:53 pm

I am using a tablet and phone.
Also i see a arrow in the upper left corner with no function!?

![tab 4](https://cloud.githubusercontent.com/assets/3482284/13554483/4576ce38-e3a9-11e5-8dd0-0ea8ecf43038.png)

**Comment by galadril** [comment]
i dont have a tabblet to test :(

**Comment by RoadXY** [comment]
That's why I assigned it to me ;-)
