### ISSUE TITLE
Android hardware as device in Domoticz

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#25]
By @rkluwen 

Possibly the Domoticz app can even be added as "Hardware" in Domoticz, so you can use the NFC controller and other sensors that your device might have in Domoticz.

**Comment by RoadXY** [comment]
And what did you have in mind for use cases for this @rkluwen ?
I'm really intrigued by this idea really!

**Comment by rkluwen** [comment]
Like was suggested in the other thread: Control Domoticz with the NFC hardware of your phone. E.g. at night, you put your phone on your night cabin, which has an NFC sticker. The lights will automatically snooze. Also some phones have temperature sensors and even barometers, which can be utilized. And the GPS receiver can be used to determine when exactly your are half an hour away from your home, so the heating can be turned on.
Geofencing is already there, and can be used to disarm an alarm.
You could use your phone's proximity sensor.
The notification subsystem can be used to send Google Cloud Message notifications (they are free). But also other event-notifications in json format or something.
The camera of your phone can function like a domoticz-camera.
Domoticz can log incoming and/or outgoing calls. If I am correct, this already works for FritzBox devices, so why not your cell phone?
The bar/qr code scanner can be used for whatever someone feels like using it for (e.g. for programming particular settings: Go on a business trip, set vacation-mode, come back, set at-home mode.
Intents can be chained, enabling starting a variety of apps, depending on I don't know what (e.g. activating a scene). Or the other way around: Your app can receive events (e.g. making Domoticz turn off the music when you start your mp3 player).
Your phone can be used to relay sms messages of Domoticz notifications.

Well... I'm sure other people can come up with more inventive things. These were just things that I could come up with, while writing this post. Even if some of them also can be implemented without "Domoticz hardware".

**Comment by RoadXY** [comment]
Nice!
Will be most certainly be looking into this!
Thanks!

**Comment by galadril** [comment]
the android device is now a mobile device under settings in domoticz
