### ISSUE TITLE
NFC fault and some wishes

### ISSUE THREAD

**Issue by remb0** [domoticz/domoticz-android#264]
I bought some NFC stickers that worked well with nfc tools and tasker etc.

but when I program on with the domoticz app and put my gsm on the sticker I got a choose at the bottom of my screen:
een actie selecteren
Domoticz
Nieuwe tag registreren

When I choose domoticz, domoticz starts but no switch affected.  I registered different devices like doorbell, lights etc   but nothing actuall switch.

I have also some other wishes regarding nfc:
use names instead of numbers.   switch 240 is paired with an nfc but don't know witch switch is 240 when I use 10 stickers :)

The only thing to register a new switch is deleting a registration and do it again. no edit function.

**Comment by galadril** [comment]
> The only thing to register a new switch is deleting a registration and do it again. no edit function.

You can edit/change the switch, The only thing you can't edit now is the name of the tag.. 
I dont' see that as a big problem.


> use names instead of numbers.

Good point, todo


> When I choose domoticz, domoticz starts but no switch affected

Weird, im trying 3 diffent types of NFC tags, and they all work!

**Comment by RoadXY** [comment]
@remb0, do you know what kind of tags you have?
