### ISSUE TITLE
"Hide Off Level" is ignored in app for "Selector Switch"

### ISSUE THREAD

**Issue by gfolkersma** [domoticz/domoticz-android#273]
The Multi-level selector switch has an option to hide the off level. This is useful when you want to name all states. In the app however, the off state is always visible as a separate switch, even if "Hide Off Level" is selected. 

Expected behavior: Separate switch is hidden when "Hide Off Level"  is enabled.
System: Raspberry Pi
App: 0.1.243 (Premium)

**Comment by galadril** [comment]
Wel spotted!

**Comment by galadril** [comment]
Will be fixed in next release

**Comment by gfolkersma** [comment]
I saw the fix in the changelog, but this does not seem to be fixed. I still see the on/off button on my phone, while the "hide off level" setting is enabled in Domoticz.
