### ISSUE TITLE
App doesn't work when domoticz API resides in a subdirectory

### ISSUE THREAD

**Issue by Jaap-Jan** [domoticz/domoticz-android#31]
The app has no option to enter a subdirectory name. This would come in handy when the Domoticz API is served via a reverse proxy and made available in a subdirectory.

**Comment by Jaap-Jan** [comment]
This seems to do the trick in a straight forward way. My Polish is a bit rusty, though.

**Comment by RoadXY** [comment]
If your not sure about the translation, leave it out. People which native language is Polish will translate else the (maybe) wrong translation will not stand out and might be wrong for a long time.

Could you create a pull request to the Development Branche, please? 
Code is looking really good! Thanks!

**Comment by RoadXY** [comment]
Tested: all fine.
We'll have to figure out a way that this settings is not mandatory and only for special cases

**Comment by galadril** [comment]
so this can be closed?

**Comment by RoadXY** [comment]
Changed the layout a bit:

![device-2016-01-08-144002](https://cloud.githubusercontent.com/assets/3482284/12199096/e697bf46-b615-11e5-94d3-b9d7e71aa416.png)
