### ISSUE TITLE
Unable to show week graph

### ISSUE THREAD

**Issue by HomeServ** [domoticz/domoticz-android#320]
For every sensor and or switch I'm unable to show a week graph. If trying to open week graph, it will go back to previous screen. 
Day, month or year graph is working fine.

**Comment by yoyodsl** [comment]
Same for me

**Comment by galadril** [comment]
Can you actually see a week graph in Domoticz itself?

**Comment by HomeServ** [comment]
Only for some of the items. Mainly Utilities.
Yes, these items work in the app.

But why show the week option if it doesn't work for a specific item?

**Comment by galadril** [comment]
I've reworked the app. only some types shows a week graph now..
closed
