### ISSUE TITLE
Bug : show utility electrical daily weekly month graph.

### ISSUE THREAD

**Issue by yoyodsl** [domoticz/domoticz-android#321]
y scale : 1KWh =1000WH
The x scale is unclear even with the zoom. (Imprecise 3 hours min)

![screenshot_20160511-235343](https://cloud.githubusercontent.com/assets/19314969/15198179/0b695aba-17d6-11e6-8cd1-50cbbe2361e6.png)
![daily](https://cloud.githubusercontent.com/assets/19314969/15198183/0fe6e828-17d6-11e6-9526-067b85258f05.jpg)
![daily](https://cloud.githubusercontent.com/assets/19314969/15198319/f525a8c0-17d6-11e6-8750-ceb08e74c9b1.png)

Some other graphic have same bug.

**Comment by yoyodsl** [comment]
![daily](https://cloud.githubusercontent.com/assets/19314969/15198283/af9c2874-17d6-11e6-9542-240c6516d41c.png)

**Comment by galadril** [comment]
Can you please check this issue with the latest version?
I;ve reworked all the graph's

**Comment by galadril** [comment]
No reaction on my  question.
