### ISSUE TITLE
Screen not refresh when hardware not responds

### ISSUE THREAD

**Issue by medusanet** [domoticz/domoticz-android#344]
When actuator is not responding ,the switches screen does not refresh and keeps white

**Comment by galadril** [comment]
Please explain more.. maybe with screenshots?

**Comment by medusanet** [comment]
In domoticz web interface when one device in not returning ack for example
is a remote plug and is not conected.you see (see image )
but in domoticz app when you try to switch you get the switches screen
empty .see pictures .
