### ISSUE TITLE
NFC problem

### ISSUE THREAD

**Issue by fibigod** [domoticz/domoticz-android#351]
When i use a NFC tag. I can register the tag in the app. And assign a switch to it. But when I scan the tag after registration it says unknown tag or empty tag.  When i use the tag with nfc tools or tasker it works normally.

I use a NFC type 2. "NXP MIFARE Ultralight (Ultralight C) - NTAG203".

With a galaxy S5.

**Comment by fibigod** [comment]
P.s. when i read the tag in nfc tools app, it says the tag is empty. That explains the empty tag error. And when i go back to the nfc section in the domoticz app. It says it's already registered.

**Comment by galadril** [comment]
Please write the next text / url to the nfc tag:
http://www.domoticz.com/app

We've implemented this filter so calls for domoticz get redirected to the domoticz app right away without dialog..


described in the forum:
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&start=1040#p89135

**Comment by fibigod** [comment]
Dear Galadril,

You're the best. It works now. I somehow overlooked it on the forum. Thanx.

**Comment by galadril** [comment]
Np, great!
