### ISSUE TITLE
Time-out epipe

### ISSUE THREAD

**Issue by rkuijer** [domoticz/domoticz-android#354]
After changing the server address the app doesn't start any more. 
Just a blank screen and a short time out message.
You can access the config setting to change the server address.
![timeout](https://cloud.githubusercontent.com/assets/1587273/17077356/242e9ce6-50ce-11e6-90a7-dafc1dfea4a4.png)

**Comment by RoadXY** [comment]
See forum

**Comment by rkuijer** [comment]
Address of forum?

Op 23 jul. 2016 1:16 p.m. schreef Robin van Kekem <notifications@github.com>:

See forum

**Comment by RoadXY** [comment]
I thought you were the same guy as a post here:
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&start=1100#p91531

Seems to be a problem with the latest Domoticz server beta (not the app!)

**Comment by galadril** [comment]
At a disconnect, the domoticz server should still be abel to show the settings screens for adjustments right?

**Comment by rkuijer** [comment]
The app only shows a blank white screen. Even if the phone is in flight modus.
How can this be a problem of the Domaticz server?
Attached are the 2 error messages.

I can't access the app setting screen to change the server address.

Regards,
Remco

Op 23 jul. 2016 1:31 p.m. schreef HNO Mobile <notifications@github.com>:

At a disconnect, the domoticz server should still be abel to show the settings screens for adjustments right?

**Comment by rkuijer** [comment]
![screenshot_20160723-134734](https://cloud.githubusercontent.com/assets/1587273/17078646/94ac64ec-50f8-11e6-8b30-9d18d8d9b935.png)
![screenshot_20160723-134742](https://cloud.githubusercontent.com/assets/1587273/17078647/9a8f7ca0-50f8-11e6-9cbe-94bfa1f7c11c.png)

**Comment by galadril** [comment]
Fixed this
