### ISSUE TITLE
Subdirectory url setting - infinite loop when wrong directory is specified

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#36]
Domoticz for Android goes in an infinite loop when specifying the wrong directory.
Don't know why it keeps on retrying though.

Errors are:
01-08 13:44:43.126 1895-13046/nl.hnogames.domoticz.premium E/Volley: [138] BasicNetwork.performRequest: Unexpected response code 404 for http://server:port/wrong_dir/json.htm?type=command&param=getversion

More details:
https://gist.github.com/RoadXY/4cd561ef057c6059e91d

**Comment by Jaap-Jan** [comment]
That doesn't seem to be an issue specifically related to subdirectories:

`01-08 19:49:20.003 22067-22067/nl.hnogames.domoticz I/GRAPH: url: http://10.0.0.222:80/json.htm?type=graph&idx=38&range=day&sensor=YouLess counter`
`01-08 19:49:20.013 22067-22613/nl.hnogames.domoticz E/Volley: [9170] BasicNetwork.performRequest: Unexpected response code 400 for http://10.0.0.222:80/json.htm?type=graph&idx=38&range=day&sensor=YouLess counter`

Offtopic: The sensor name should be "counter", but even then, the graph isn't right.

**Comment by Jaap-Jan** [comment]
The wrong value was passed in the method call so the retry counter never reached zero.

**Comment by RoadXY** [comment]
Thanks!
Never meant to point the directories as guilty.
Only found the issue and, for historical knowledge, created an issue for it so the issue is known.

**Comment by Jaap-Jan** [comment]
No problem, I didn't take it personal, anyway. I just added that comment so someone investigating the problem would know that it wasn't only limited to that directory thingy.

**Comment by RoadXY** [comment]
Tested and worked great!
Closed.
