### ISSUE TITLE
Modify a Variable ?

### ISSUE THREAD

**Issue by sylvainar** [domoticz/domoticz-android#372]
Hey !

So I've got a variable that specifies the target temperature of the room. However, it's not possible to modify it directly via the app. Is this feature missing or am I doing it wrong ?

Thanks !

**Comment by galadril** [comment]
Was not implemented yet..

**Comment by galadril** [comment]
Added this feature in the next upcoming beta

**Comment by galadril** [comment]
![1](https://cloud.githubusercontent.com/assets/14561640/18302598/fc830c0c-74d8-11e6-8543-21b50846f264.png)
![2](https://cloud.githubusercontent.com/assets/14561640/18302597/fc809792-74d8-11e6-8aa1-1bca5fd7bf50.png)

**Comment by sylvainar** [comment]
Nice work, can't wait to test it !
Thanks a lot ! :+1:
