### ISSUE TITLE
Domoticz is not responding

### ISSUE THREAD

**Issue by gartensofa** [domoticz/domoticz-android#376]
After installing the app, on first start the app only displays a white screen, after some time android gives  "Domosticz is not responding...". When answered with "wait" after some more time the setup screen appears. After setting up the same delay happens each time the app is started.
Also happens when in airplane mode.

Happens on Android 6.0.1 xperia z3 compact

**Comment by gartensofa** [comment]
ok, nvm. it worked itself out and is not reproduceable by reinstalling.
Thanks for a great app btw :-)

**Comment by gartensofa** [comment]
And its back..
Anyone else seeing this behavior?

**Comment by galadril** [comment]
i really don't have it.. nexus 5x, nexus 5, moto g, amazone kindle fire.. (so enough devices to test it ;) )

**Comment by allan-gam** [comment]
Same here. Only a blank screen.  On Android 6.0.1 xperia z3 compact.

**Comment by galadril** [comment]
latest version? check if you can browse your domoticz system from your phone..
Reset the app data and reconnect?

**Comment by allan-gam** [comment]
Yes, I've deleted the app data and cache. I removed the app completely, rebooted the phone and reinstalled. Same result. It was working a few weeks ago.

**Comment by allan-gam** [comment]
Also,  Domoticz is accessible through the web interface. Anyway the app has no data after its been reset and isn't yet associated with my Domoticz server.

**Comment by gartensofa** [comment]
I may be a little late in thinking of it, but i'm running a modified version of Sony's rom:
http://forum.xda-developers.com/z3-compact/development/rom-slimm-t3359831
Du you use the same by any chance?

**Comment by allan-gam** [comment]
Yes I am. Good thought. I'm on SLiMM V2. 5. I'm not sure if it's relevant but it has among other features "optimized SQlite databases" whatever that means. I've been using this ROM for more than a year and never had sent issues that I'm aware of.

**Comment by allan-gam** [comment]
Maybe some error handling and debug output in the app could help us to further investigate what's causing the problem so that it can be resolved. A white screen isn't very helpful.

**Comment by gartensofa** [comment]
Guess the first step would be to revert to stock rom to see if that solves the problem. We cant really expect to get error support for every custom rom..
I planned to do that over the weekend, but forgot. I will come back to you when i got around to it.

**Comment by galadril** [comment]
> Maybe some error handling and debug output in the app 
There is a settings under advanced settings to enable some debug information in the app..

**Comment by allan-gam** [comment]
> There is a settings under advanced settings to enable some debug information in the app..

I can't access anything within the app due to the blank screen.

**Comment by gartensofa** [comment]
It will start after a long while, which i used to check the debug-screen, but nothing showed there.
The problem does not come up on stock rom.
I also fixed it under the slimm custom rom by doing this: 
http://forum.xda-developers.com/z3-compact/development/rom-slimm-t3359831/post69260867#post69260867
Which fixes some problem with google play services.
If the domoticz app interacts with those somehow there might be something to look into, otherwise i could close the ticket.

**Comment by galadril** [comment]
Thanks! We do use quite some google services 👍

**Comment by allan-gam** [comment]
> If the domoticz app interacts with those somehow there might be something to look into, otherwise i could close the ticket.

Thanks for your efforts. Now Wajk has abandoned his work for the D5803/D5833 so I will probably resolve the issue by installing a different ROM. It's way OT but maybe You can recommend something stable. 

Cheers and thanks again!

**Comment by gartensofa** [comment]
@galadril: i did the resetting because google auto said something like "google services dont seem to be available right now" or something like that. Allan could probably tell you exactly if he installed it ;-)
So maybe you could implement a check like that..

@allan: would if i could, friend. I looked around a bit yesterday, but seems like im gonna stay on slimm for now. Maybe open my bootloader if we get some aosp nougat in the future..

**Comment by galadril** [comment]
So this can be closed?

**Comment by allan-gam** [comment]
@galadril I reinstalled my phone using a stock firmware and it solved the problem. The firmware that I've used had also blocked some other functions in other programs but I was unaware of that. I believe this issue can be closed. Thanks for your kind help.
