### ISSUE TITLE
New Feature - Different Ring notification based on arrived message

### ISSUE THREAD

**Issue by dimitribellini** [domoticz/domoticz-android#377]
Dear Developer,
thanks for your great app! I use it everyday, i want ask you if it possible to add a specific ringtone based on the incoming message. I ask that because i saw that you already know the possible message (from Clear Notification option) so i think is also possible to have a specific tone for every message.
Thanks so much and good work

**Comment by galadril** [comment]
No sorry, wont do this in near future... :(

**Comment by dimitribellini** [comment]
Is not a good news ;-) I hope in a near future development because it will be a possible solution to replace the physical siren equipment.
Best regards
