### ISSUE TITLE
Notifications get sent to all users

### ISSUE THREAD

**Issue by dannyvanderzande** [domoticz/domoticz-android#379]
I set domoticz up so I receive notifications when the doorbell rings or my server case gets too hot (etc etc) and this works just fine. The problem is my girlfriend (using a different domoticz user and google account) receives the same notifications but she's not interested in the same things I want notifications for.

I can't seem to find it in the settings so I presume this is a bug in the app. Can anyone else confirm?

By the way, thanks for all the hard work, I love the app!

**Comment by galadril** [comment]
I know about this... this needs to be solved in Domoticz system, not in the app.

I register all devices individually.. and there should be a config screen on Domoticz wheren you can configure notifications per device.

Please submit as issue/feature request on Domoticz:
https://github.com/domoticz/domoticz
