### ISSUE TITLE
Weather Sun Radiation not displayed correctly

### ISSUE THREAD

**Issue by Catfriend1** [domoticz/domoticz-android#380]
I have a weather underground sensor WU-Sonne in W/m² as a domo device.
App shows radiation symbol on the left, next to it the following text:

Allgemein
0.0 Watt/m20.0 Watt/m20.0 Watt/m20.0 (...) and so on.

Bug 1) If I pull up to refresh the list, another "0.0 Watt/m2" is added to the existing text, so it would be 0.0 Watt/m20.0 Watt/m20.0 Watt/m20.0 Watt/m2 next time.

Problem 2) Watt/m20.0 should be Watt/m2[SPACE]0.0

I am using newest app version on android. older versions already had this problems for month.

**Comment by Catfriend1** [comment]
![screenshot_20161002-114056](https://cloud.githubusercontent.com/assets/16361913/19421205/84dcc142-93fb-11e6-871a-38102c020d00.png)

**Comment by galadril** [comment]
👍

**Comment by Catfriend1** [comment]
Problem solved.

**Comment by planetloli** [comment]
please delete issue
