### ISSUE TITLE
Bad UI for selector switch

### ISSUE THREAD

**Issue by dantman** [domoticz/domoticz-android#381]
Selector switches have a bad UI in the app.

At first look a selector switch looks like a dimmer instead of a set of radio options:
![screenshot_20161022-140346](https://cloud.githubusercontent.com/assets/53399/19622529/f3203a26-9860-11e6-939d-c7af1579b3f2.png)

However if you try moving the slider, instead of the state updating a dialog pops up:
![screenshot_20161022-140630](https://cloud.githubusercontent.com/assets/53399/19622531/104cb8ae-9861-11e6-951d-0c9300f44fb7.png)

The slider doesn't make sense, the slider opening a dialog instead of acting like a slider makes less sense, and the dialog seems unnecessarily heavy itself.

I think the UI for a selector should simply be a dropdown button/select:
https://material.google.com/components/buttons.html#buttons-dropdown-buttons

**Comment by galadril** [comment]
Ill look into it

**Comment by galadril** [comment]
Upcoming in next beta, revised Selector

![screenshot_2016-11-03-14-46-11](https://cloud.githubusercontent.com/assets/14561640/19970001/e6d31b5c-a1da-11e6-9450-8a11731e6757.png)
