### ISSUE TITLE
Geofence switch behaviour

### ISSUE THREAD

**Issue by ernorv** [domoticz/domoticz-android#383]
The behavior of the Geofence switch seems to have changed to TOGGLE instead of ON/OFF depending on inside/outside location. This is normally not a problem, until one has to restart his phone, resulting in (off course depending on the behavior attached) switching lights off etc. 

A second thing I noticed, if the attached switch is Hidden in Domoticz Server, it is not operated anymore, disabling the normal operation.

**Comment by galadril** [comment]
I've changed the toggle to depend on inside/outside location.
