### ISSUE TITLE
Blinds toggle shown as on/off 

### ISSUE THREAD

**Issue by kooimens** [domoticz/domoticz-android#384]
The blinds toggle is shown as on/off instead of open/close. The status information is correct (open or closed).

**Comment by galadril** [comment]
Is this still the case with the latest beta? (see change of nvdweem)

**Comment by apazga** [comment]
Yep, latest beta -0.1.352 (1903)- shows on/off
![screenshot_20170114-191354](https://cloud.githubusercontent.com/assets/6894350/21957008/1b1394e6-da8e-11e6-9ac2-1d31ee03c7f3.png)

**Comment by galadril** [comment]
I've did quite some fixing on blinds in the last release

**Comment by galadril** [comment]
please check
