### ISSUE TITLE
Android Permissions

### ISSUE THREAD

**Issue by TimelessNL** [domoticz/domoticz-android#388]
Hi,

More and more Android phones support selective permissions. But when permissions like location are denied the Domoticz Application just exits instead of working with limited functionality. 

This is not very user friendly. I know that there are some uses for location and such. But it is not something that should stop the application from working.

Please use the Android permissions where they are made for and don't just force them.

Regards,

**Comment by galadril** [comment]
Good point ill look into this

**Comment by galadril** [comment]
Should be fixed in the upcoming beta..

**Comment by TimelessNL** [comment]
Great work! And fast as well.

So is it correct to assume that the permissions are only requested when they are needed?

At least thats what I see in the code. Only did a partial scan. So therefor my question.

**Comment by galadril** [comment]
> So is it correct to assume that the permissions are only requested when they are needed?

Yes.. and it won't request again when you tell it to, if denied nothing crashes anymore.

I've also added an explanation per permissions why we need them, so you know which feature can't be used when you denie the permissions..

**Comment by galadril** [comment]
See screenshots:

![screenshot_20161213-153442](https://cloud.githubusercontent.com/assets/14561640/21144128/d2e16c82-c149-11e6-8882-34b4f39e7572.png)

when denied:

![screenshot_20161213-153446](https://cloud.githubusercontent.com/assets/14561640/21144135/d7295aac-c149-11e6-8883-ede4b7209bbb.png)

**Comment by TimelessNL** [comment]
_Ah another dutch speaking individual :)_

Great, that's exactly what an Android application should do.
Last question: `<string name="permission_desc_storage" `mentions `"needed for saving cache file"`. I could imagine that this cache file could be important. What happens if declined?

**Comment by galadril** [comment]
I can't load cached data.. so that makes the app slower.
Then you see the api responses when it comes back from the server.

now > 
1 load cache
2 call domoticz api for data (background process)
3 update screens with new data (background process)
4 save latest data in cache files

without the permission:
1 call domoticz api for data 
2 update screens with new data

**Comment by TimelessNL** [comment]
But if only used for cache files why not use: [getCacheDir](https://developer.android.com/reference/android/content/Context.html#getCacheDir()) and save cache files to the apps local storage? There is no permission necessary to write to the apps internal storage.  See: `Apps require no extra permissions to read or write to the returned path, since this path lives in their private storage.`

**Comment by galadril** [comment]
Ill look into that..
