### ISSUE TITLE
List scrolls up after click

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#39]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=68908#p68908

by maluko » Fri Jan 08, 2016 4:12 pm

When we open any tab like switch which have a lot devices and if you want turn off and next turn on( like reboot) the screen goes always to the beginning, next have to scroll or "find".
this happen too when i want to open or close the blinds (not all because have a scene), i have ordered all next to each other.

**Comment by jvandenbroek** [comment]
Same goes for when filtering some items,  after switching the filter is lost and the whole screen is shown. Would be nice if it keeps the filter active after toggling.

**Comment by galadril** [comment]
" after switching the filter is lost" > this is fixed
https://github.com/domoticz/domoticz-android/commit/3888c40743a7044284d0549cae9fd66f9c1a4992

**Comment by galadril** [comment]
Also turning switches on / off doesn't goes back to the beginning anymore.
