### ISSUE TITLE
Only on button visible on scenes/groups widget

### ISSUE THREAD

**Issue by jvandenbroek** [domoticz/domoticz-android#391]
Since last update there is no longer a off button on scenes/groups widgets.

**Comment by galadril** [comment]
Hi

bring back :) ./... i was looking through the code but it looks like on / off switches always had 1 toggle button:

```
switch (s.getSwitchTypeVal()) {
                        case DomoticzValues.Device.Type.Value.ON_OFF:
                        case DomoticzValues.Device.Type.Value.MEDIAPLAYER:
                        case DomoticzValues.Device.Type.Value.X10SIREN:
                        case DomoticzValues.Device.Type.Value.DOORLOCK:
                        case DomoticzValues.Device.Type.Value.PUSH_ON_BUTTON:
                        case DomoticzValues.Device.Type.Value.SMOKE_DETECTOR:
                        case DomoticzValues.Device.Type.Value.DOORBELL:
                        case DomoticzValues.Device.Type.Value.PUSH_OFF_BUTTON:
                        case DomoticzValues.Device.Type.Value.DIMMER:
                        case DomoticzValues.Device.Type.Value.SELECTOR:
                            withButton = 1;
                            break;
                    }

```


But please check the latest beta if that looks better for you (i now check the setting indeed)

Thank for the issue request~!

**Comment by jvandenbroek** [comment]
Hi,

Sorry that I wasn't clear, I meant the on/off buttons for group widgets (and possibly not scenes, thought they were handled the same ;)). My first statement about switches was wrong, they were indeed just 1 toggle.. Thanks for the changes, will check out the next beta as soon it's published!

**Comment by galadril** [comment]
Ok, that should also be fixed 👍

**Comment by galadril** [comment]
Great thanks
