### ISSUE TITLE
Geo-fences are lost during Android phone reboot

### ISSUE THREAD

**Issue by bazsodombiandras** [domoticz/domoticz-android#395]
Tested with AllView X3 Soul Pro running Android 6.0 and Domoticz app v0.1.343:

1. I set up one or more geo-fences.
2. I walk in and out of the geo-fence perimeters and the geo-fences are properly triggered and the associated switches are properly switched.
3. If I kill the Domoticz app the geo-fences still work properly (thank God!)
4. If I reboot my phone, the geo-fences are lost and they won't trigger anymore when I walk in and out of the geo-fence perimeters.
5. If I open the Domoticz app after the reboot of the phone, the geo-fences still won't work.
6. If I go to Settings -> Configure Geofencing in the Domoticz app, the geo-fences are restored automatically (without actually changing anything in the geo-fence settings) and start  working properly again (until the next reboot).
--------------------
Tested with AllView X3 Soul Pro running Android 6.0 and Domoticz app v0.1.360 (2104):

0. Mobile data on, Location on, phone screen on, App Manager set to auto-start Domoticz app on boot. Create geofence in Domoticz app while being inside the fence -> Entering current area event triggered. OK!
1. Walk out of the geofence -> Leaving current area event triggered. OK!
2. Walk into the geofence -> Entering current area event triggered. OK!
3. Turn off phone's screen.
4. Walk out of the geofence -> Leaving current area event triggered. OK!
5. Walk into the geofence -> Entering current area event triggered. OK!
6. Kill the Domoticz app.
7. Walk out of the geofence -> Leaving current area event triggered. OK!
8. Walk into the geofence -> Entering current area event triggered. OK!
9. Turn off mobile data and Location, wait for 30 sec, then turn back on mobile data and Location.
10. Walk out of the geofence -> Nothing happens. Bad!
11. Walk into the geofence -> Nothing happens. Bad!
12. Enter the Setting/Configure geofencing section of the Domoticz app. Entering current area event triggered instantly. OK!
13. Walk out of the geofence -> Leaving current area event triggered. OK!
14. Walk into the geofence -> Entering current area event triggered. OK!
15. Rebooot phone. After the boot is completed (still inside the geofence) the Entering current area event is triggered instantly, BUT...
16. Walk out of the geofence -> Nothing happens. Bad!
17. Walk into the geofence -> Nothing happens. Bad!
18. Enter the Setting/Configure geofencing section of the Domoticz app. Entering current area event triggered instantly. OK!
19. Walk out of the geofence -> Nothing happens. Bad!
20. Walk into the geofence -> Nothing happens. Bad!
21. Kill the Domoticz app.
22. Walk out of the geofence -> Leaving current area event triggered. OK!
23. Walk into the geofence -> Entering current area event triggered. OK!
24. Disable Domoticz app auto-start on boot in App Manager.
25. Reboot the phone. After the boot is completed (still inside the geofence) nothing happens, no event triggered this time. Suspicious...
26. Walk out of the geofence -> Nothing happens. Bad!
27. Walk into the geofence -> Nothing happens. Bad!
28. Enter the Setting/Configure geofencing section of the Domoticz app. Entering current area event triggered instantly. OK!
29. Walk out of the geofence -> Leaving current area event triggered. OK!
30. Walk into the geofence -> Entering current area event triggered. OK!
31. Reboot the phone. After the boot is completed (still inside the geofence) nothing happens, no event triggered this time. Suspicious...
32. Walk out of the geofence -> Nothing happens. Bad!
33. Walk into the geofence -> Nothing happens. Bad!
34. Enter the Setting/Configure geofencing section of the Domoticz app. Entering current area event triggered instantly. OK!
35. Walk out of the geofence -> Leaving current area event triggered. OK!
36. Walk into the geofence -> Entering current area event triggered. OK!

Conclusions:
A) Turning off the Location and mobile data kills the geofences. This is even worse than the reboot problem because obviously the data and Location cannot eb kept on all the time (because of battery consumption and data plan reasons).
B) Rebooting the phone kills the geofences.
C) Going to the Settings/Configure geofences section of the Domoticz app seems to correctly restore the geofences (except for steps 19 and 20 where it seems that this failed too)
D) One time after reboot it seemed that the geofences were restored, but they didn't actually work when walking in/out of the fence.
--------------------
Update for version v0.1.360 (2104) tested with AllView X3 Soul Pro running Android 6.0:
A full update of every app on the phone has solved most of the problems described above. there is just one major geo-fencing bug remaining: the geo-fences are lost when the Android location is turned off until the Setting/Configure geofencing section of the Domoticz app is open again, at which point the geo-fences are restored. This is still a big problem, the location cannot be kept permanently on because the GPS antenna drains the battery. The reboot is working fine now, the geo-fences are restored on reboot.

**Comment by bazsodombiandras** [comment]
I'm happy to help with phone logs or whatever if necessary.

**Comment by galadril** [comment]
do you have quickboot enabled on your phone?
I've found a fix for quickboot not enabling all geofences..

**Comment by galadril** [comment]
Im going to upload a new beta, please check if it works better on your phone after the update

**Comment by bazsodombiandras** [comment]
Unfortunately I don't know what quickboot is, so I would guess that it's not enabled... I'll check the beta.

**Comment by bazsodombiandras** [comment]
Is there anythings special that I need to do to get the beta, or a simple updating of my app through Google Play will get the latest beta? I'm guessing by default Google Play does not update apps to beta state...

**Comment by bazsodombiandras** [comment]
I've done some more extensive testing with version 0.1.360 (2104) of the app and I've updated the original problem description accordingly. Please see above. In short the app's geofences seem to be neutralized by briefly turning off the location and/or mobile data and also by the reboot of the phone. In addition they seem to behave chaotically.

**Comment by bazsodombiandras** [comment]
Update for version v0.1.360 (2104) tested with AllView X3 Soul Pro running Android 6.0:
A full update of every app on the phone has solved most of the problems described above. there is just one major geo-fencing bug remaining: the geo-fences are lost when the Android location is turned off until the Setting/Configure geofencing section of the Domoticz app is open again, at which point the geo-fences are restored. This is still a big problem, the location cannot be kept permanently on because the GPS antenna drains the battery. The reboot is working fine now, the geo-fences are restored on reboot.

**Comment by galadril** [comment]
Did some major rework on geofencing mechanism..
Enabling/disabling locations, disabling whole geofence feature.. everything should work better now..

**Comment by galadril** [comment]
(beta not yet build.. maybe tomorrow)

**Comment by bazsodombiandras** [comment]
That is awesome news! Thank you! I'll be sure to test it as soon as you release the beta!
Andras

**Comment by galadril** [comment]
Can we close this issue with the latest beta??

**Comment by bazsodombiandras** [comment]
Yes, geo-fence related funtionality now works flawlessly! Can be closed.

**Comment by galadril** [comment]
Thanks!
