### ISSUE TITLE
SQL Query error reported in CWebServer::RType_HandleGraph

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz-android#401]
While browsing the data from the Domoticz android app, I'm getting some SQL error :

2017-01-18 19:28:49.855 Error: SQL Query("SELECT Value, Date FROM MultiMeter_Calendar WHERE (DeviceRowID==20 AND Date>='2017-01-11' AND Date<='2017-01-18') ORDER BY Date ASC") : no such column: Value

The device is a "FIBARO System FGWPE Wall Plug"

Issue already discussed with @gizmocuz, see https://github.com/domoticz/domoticz/issues/1137

**Comment by galadril** [comment]
This is a Domoticz system issue.. please report there or on the forums.

**Comment by gizmocuz** [comment]
No, it seems this does not happen with the default web gui... thats why it is reported here

**Comment by galadril** [comment]
Can you create a viewer account on your system so I can debug?

**Comment by sbouchex** [comment]
@galadril difficult as it's inside my home-LAN. The domoticz bug (mentioned above) contains a domoticz database you can play with.

**Comment by galadril** [comment]
When does it happen
 - when you check the switches screen? 
 - utilities screen? 
 - do you get the exception when you toggle a switch or check the graphs?

under the advance settings, there is also a possibility to enable debugging..
You can then easely copy the debug info on the extra panel by long pressing that window.

**Comment by sbouchex** [comment]
When I check the switches screen, everything is fine. I'm able to switch on & off my Fibaro switch
In the utilites screen, I do see the current consumption, so everything is fine.

If I click on "Day", I do see a graph with the daily usage
If I click on "Month", I do see a graph with the daily usage
If I click on "Week", I do not see a graph and domoticz is reporting an error : 2017-01-23 11:13:06.865 Error: SQL Query("SELECT Value, Date FROM MultiMeter_Calendar WHERE (DeviceRowID==16 AND Date>='2017-01-16' AND Date<='2017-01-23') ORDER BY Date ASC") : no such column: Value

**Comment by galadril** [comment]
Is there actually a week graph availble at the domoticz website?

**Comment by sbouchex** [comment]
No and it seems to be the default case.

**Comment by galadril** [comment]
@gizmocuz I don't use sql queries on the app.. i call the json api.

So probably there is no week graph data available, but I call the json:
/json.htm?type=graph&sensor=counter&idx=58&range=week

the json should not throw an sql exception, but should return 'no value available'..

**Comment by gizmocuz** [comment]
Thats correct, not all graphs have week graphs

**Comment by sbouchex** [comment]
Why not hiding the "Week" button if the graphs is not available ? Is there a way to know that ?

**Comment by galadril** [comment]
I show the graph buttons on the overview page (utilities, temperature, etc) .. 
and i don't really want to check all switches for all 4 types of graphs (day, week, month and year) if they have data or not...

**Comment by gizmocuz** [comment]
Thats also an option, if no data... no show

**Comment by galadril** [comment]
il remove the week graph for temperatures..
