### ISSUE TITLE
Latest update broke all widgets

### ISSUE THREAD

**Issue by apazga** [domoticz/domoticz-android#405]
Hi,

I'm a beta user. Latest update broke all widgets and they had to be re-added. 0.1.370 (2352)
E.g.: temperature widgets showing button:
![screenshot_20170214-110743](https://cloud.githubusercontent.com/assets/6894350/22924793/cc28aafc-f2a6-11e6-9f88-e4a6e1d7b59b.jpg)

Light widgets showing as blinds:
![screenshot_20170214-111509](https://cloud.githubusercontent.com/assets/6894350/22924855/fa9efdb4-f2a6-11e6-8465-1ab893b6294d.jpg)

Regards

**Comment by galadril** [comment]
Stil the case with the latest updates?

**Comment by apazga** [comment]
Just re-added some of them. Waiting for the next beta update to see it.

**Comment by galadril** [comment]
and? can we close this.

**Comment by galadril** [comment]
(no awnsers)

**Comment by apazga** [comment]
Sorry for the delay, but it just happened again (Also in my wife's phone).
![screenshot_20170326-113136](https://cloud.githubusercontent.com/assets/6894350/24522305/721b24f2-158f-11e7-95fa-3c6cf21023ba.png)

**Comment by apazga** [comment]
On the other hand, widgets with buttom are working fine.

![screenshot_20170330-212914](https://cloud.githubusercontent.com/assets/6894350/24522545/322c095a-1590-11e7-826a-14a6e67601a9.png)
