### ISSUE TITLE
Allow several Server connections in Settings

### ISSUE THREAD

**Issue by davidiluvatar** [domoticz/domoticz-android#406]
Hello!
I think it would be very useful to allow configuring more than one server connection, and choosing the one you want to use in a dropdown list. In my case, I have 2 houses, and when I want to access one or the other, I need to reconfigure the host:port fields. This could be a premium feature.

Thank you,
David.

**Comment by galadril** [comment]
Thats already implemented, see multi server settings (premium)

**Comment by davidiluvatar** [comment]
Great! I didn't notice this. Purchased the premium version!

Thank you for your great work!
