### ISSUE TITLE
Notifications issue

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz-android#407]
Two things, I'm not sure if they are related, but both have to do with notifications.  When I was using Domoticz version 3.5877 (current stable release) the notification would only pop up on my app if all the notification types in Domoticz were enabled.  This is annoying because some notifications I want to pop up on the phone and some I want it to also send and email.  However, I can either get one or the other, not both.  If I enable email then it must send an email or I get no notification on my phone.

Also, the second issue, not sure if it's related is that I had to upgrade to the beta version to get certain features.  However, notifications totally stopped on my phone.  The funny thing is I can go and view the recent notifications in the app.  So the app is seeing them but choosing to not display them.  Another interesting thing is that if I use the "send message" feature in Domoticz it works and does pop up on my phone!

**Comment by galadril** [comment]
"When I was using Domoticz version 3.5877 (current stable release) the notification would only pop up on my app if all the notification types in Domoticz were enabled. "

The latest beta introduced a new notification type called gcm .. that's the notification type to send notifications to your phone.

"Also, the second issue, not sure if it's related is that I had to upgrade to the beta version to get certain features."

I had the same issue.. the latest beta of Domoticz introduces a setting to turn on / off phone notifications..  Please check if it's turned on..  
https://github.com/domoticz/domoticz-android/wiki/Troubleshooting----GCM-Notifications

**Comment by Ittiz** [comment]
Yep work thanks a bunch!

**Comment by galadril** [comment]
Great!
