### ISSUE TITLE
location geofence beta

### ISSUE THREAD

**Issue by Markjgabb** [domoticz/domoticz-android#408]
hi guys 
galaxy s5  when i set geofence i get warning permission denied   
thhese location permissions are needed for geogencing and to get the wifi ssids around you

guessing a element is missing under location module

**Comment by galadril** [comment]
Can you do a printscreen?

**Comment by Markjgabb** [comment]
![screenshot_2017-03-07-21-35-09](https://cloud.githubusercontent.com/assets/25454521/23652848/7d9761b0-037e-11e7-91f6-201bd0b17671.png)

**Comment by Markjgabb** [comment]
this occurs as soon as click on the click in the map screen when confirming address

**Comment by galadril** [comment]
what android version are you on?

**Comment by Markjgabb** [comment]
Android 6.0.1

**Comment by galadril** [comment]
Still the case with the latest version?
can you make a screenshot of the app/settings/permissions screen of android?

**Comment by galadril** [comment]
This should be fixed already.. no reponse on my question, so Ill close this case for now..?
