### ISSUE TITLE
SetPoint change min and max values

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#409]
For the thermostat, some users want setpoints not to be between 0 / 30 celcius.

I've added new settings within the app so you can set the min and max yourself, even minus values are allowed

**Comment by galadril** [comment]
Changed screens:



![screenshot_20170307-113505](https://cloud.githubusercontent.com/assets/14561640/23652914/e2e640bc-032a-11e7-896d-f36f6c337049.png)

![screenshot_20170307-113515](https://cloud.githubusercontent.com/assets/14561640/23652913/e2e3dd36-032a-11e7-9343-15091bef3e85.png)

**Comment by Fraisdos** [comment]
Hi,

How to do this with latest Android version 0.2.110(5871) ?
Impossible to increase the max value.  

Many thanks.
