### ISSUE TITLE
Weird geofence behavior

### ISSUE THREAD

**Issue by IvorNL** [domoticz/domoticz-android#412]
Randomly the app would decide i left the house (while I'm still inside)
Already set the range to 2KM, but doesn't help. 

Almost always happens when the phone is idle and thus not connected to the local WiFi..

Using app version 0.1.389 (2730)
Running on Samsung S7, Android 7.0, Kernel 3.18.14 (all stock, non rooted)

**Comment by galadril** [comment]
Do you get the notification that you've entered a region?
Do you have your location services enabled?
No battery save service enabled?

**Comment by IvorNL** [comment]
I get the notification, location service is on. Not sure about battery saving service, all settings are stock and no external battery saving apps are installed.

I use domoticz in conjunction with Homewizard, their app also uses geofencing and doesn't show this kind of behaviour.

**Comment by galadril** [comment]
hmm maybe the other apps use a different api then the Google Geofencing Api...

**Comment by galadril** [comment]
Geofence enter and leave in the same minutes couple of times #421
