### ISSUE TITLE
Switch type selector not manage

### ISSUE THREAD

**Issue by bueno79** [domoticz/domoticz-android#413]
Just add Qubino to manage the radiator for towel in the bathroom. So it has a pilot cable. This radiator is able to receive 6 order (ON, Off, temp, winter, temp -1, temp -2, temp -3.5 degree celcius). Si I use a virtual switch, with the type selector.

this type of switch is not manage very well on the apps. It could be great to have the button always display. 

Currently I need to go in setting, activate option to see ON/Off button (whyyyy?); then I type ON, a combo box appear and I have to choose the mode...not very cool. If I don't change this and I pass the switch on ON...white screen, no action on the radiator...well it is not working.

Bueno

**Comment by galadril** [comment]
Can you add screenshots to explain more?

**Comment by bueno79** [comment]
yes I have the screen shoot of my switch in domoticz...do you need screen from android app too ? 

![image](https://cloud.githubusercontent.com/assets/27161702/24885695/3eb2f418-1e50-11e7-86e3-159232060629.png)

**Comment by bueno79** [comment]
hi, 

did you were able to reproduce the problem ?

regards

**Comment by galadril** [comment]
Do you have the latest beta?
Ive reworked the selectors, So no more on/off button.. Only the combobox to
set the modes

Op 13 apr. 2017 9:20 p.m. schreef "bueno79" <notifications@github.com>:

**Comment by galadril** [comment]
Fixed in the latest beta, it's now a combobox to select the mode or off, it's always visible.

**Comment by bueno79** [comment]
arg no I have the stable  :( how can I test the beta to help you ?

**Comment by galadril** [comment]
It's described on my website:
http://hnogames.nl/domoticz.html

> 
> Beta testers?
> You could start helping us with beta testing the latest features..
> https://play.google.com/apps/testing/nl.hnogames.domoticz.premium
>

**Comment by galadril** [comment]
(you need a premium version to run the beta's)

**Comment by bueno79** [comment]
ok so now I'm a tester :) I'm waiting the update . Thx for your support. So impatient to test eh IOS version

**Comment by bueno79** [comment]
hi Galadril,

the fix is very good. It work on slector type perfectly. I've test on 5 devices android with differents Android version. Script and event are reflect on the selector, refresh is ok, I've try to pass an order from 4g  then another another one on wifi very fast...no error. 

You can see this as solved for me. Do you need specific test on this point ?

regards
