### ISSUE TITLE
Multi platform app

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#414]
Im building a multi platform version of this app
This is just a placeholder to see my progress:

# Android screenshots  
![9](https://cloud.githubusercontent.com/assets/14561640/25740717/001d374a-3188-11e7-8cda-9b702f25644a.png)  
![1](https://cloud.githubusercontent.com/assets/14561640/25740723/0041dcb2-3188-11e7-9da6-ad71d6aaf315.png)  
![2](https://cloud.githubusercontent.com/assets/14561640/25740722/0040836c-3188-11e7-8005-499785b7c293.png)  
![3](https://cloud.githubusercontent.com/assets/14561640/25740724/004410ea-3188-11e7-9872-23425fc2509d.png)  
![4](https://cloud.githubusercontent.com/assets/14561640/25740720/003acc4c-3188-11e7-8118-442f530f0d0e.png)  
![5](https://cloud.githubusercontent.com/assets/14561640/25740718/003866e6-3188-11e7-8324-bdb17063c3bf.png)  
![6](https://cloud.githubusercontent.com/assets/14561640/25740727/005274fa-3188-11e7-9ec6-75f2863c2821.png)  
![7](https://cloud.githubusercontent.com/assets/14561640/25740725/004f0810-3188-11e7-82a8-e0b31cd54379.png)  
![8](https://cloud.githubusercontent.com/assets/14561640/25740726/004f9bcc-3188-11e7-8282-e2e9b425d351.png)  
![10](https://cloud.githubusercontent.com/assets/14561640/25740719/00392c3e-3188-11e7-9d6d-59520523070a.png)  

# iOS screenshots  
![simulator screen shot 5 may 2017 02 06 16_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741260/373756dc-318a-11e7-9cc8-8ce0b317f673.png)
![simulator screen shot 5 may 2017 02 06 39_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741258/3733119e-318a-11e7-8acb-578eb27793d5.png)
![simulator screen shot 5 may 2017 02 06 51_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741259/373375ee-318a-11e7-9ec2-5eb45578263d.png)
![simulator screen shot 5 may 2017 02 06 56_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741265/3753dc3a-318a-11e7-8275-0f489fc87bbc.png)
![simulator screen shot 5 may 2017 02 07 19_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741264/37533de8-318a-11e7-9eae-5e2b45ad6ede.png)
![simulator screen shot 5 may 2017 02 35 42_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741266/375b1a22-318a-11e7-90d5-92008a25e677.png)
![simulator screen shot 5 may 2017 02 35 53_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741262/374a86ee-318a-11e7-8831-81a6a9c07044.png)
![simulator screen shot 5 may 2017 02 05 58_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741261/374a7a96-318a-11e7-811d-e4318b94349c.png)
![simulator screen shot 5 may 2017 02 06 11_iphone7jetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25741263/374f4d14-318a-11e7-9b72-67b4034c7c1b.png)

**Comment by pierre-guillot** [comment]
Is that mean you have remove all the Google Play Service dependancies? :) Some guy (like me) use only Fdroid on their Android devices, and it will be lovely if i can directly download Domoticz on it.

**Comment by galadril** [comment]
don't think so.. sorry 👍

**Comment by galadril** [comment]
ill be posting my progress here.. 
## 
added filtering
![60d489e1-251b-4027-b53b-c1e5d333f74b](https://cloud.githubusercontent.com/assets/14561640/25009971/d1b8082e-2068-11e7-87a0-e95b752a107f.png)

**Comment by bueno79** [comment]
really nice. ping me once you need a alpha or beta test.

**Comment by galadril** [comment]
Added new features / settings:
- Filter devices on Plan
- Settings (startup screen, extra data on dashboard, etc)

# Screenshots
![1](https://cloud.githubusercontent.com/assets/14561640/25275605/74fea834-2696-11e7-9acc-dbbb606336d1.png)
![2](https://cloud.githubusercontent.com/assets/14561640/25275607/76d3beec-2696-11e7-8667-3cf4567dea3f.png)
![3](https://cloud.githubusercontent.com/assets/14561640/25275608/77e1e502-2696-11e7-9e3a-d3714e61c9cf.png)
![4](https://cloud.githubusercontent.com/assets/14561640/25275611/790518fa-2696-11e7-948c-cb13b36ab0ff.png)

**Comment by SMARoovers** [comment]
Any chance this could also be implemented into a Windows 10 UWP app?

**Comment by galadril** [comment]
that's indeed also an idea.. but has less prio then ios at this moment..

**Comment by galadril** [comment]
Started on implementing different views per device type..
Selector> with combobox
on off switches > with buttons
etc..

only the selectors work fully at this moment..


![99757160-0633-4574-a867-363bdb24f715](https://cloud.githubusercontent.com/assets/14561640/25385662/1e316938-29c5-11e7-82f4-f95af4c9add8.png)  

![screenshot_20170425-143656_framed](https://cloud.githubusercontent.com/assets/14561640/25385682/1fc21f4a-29c5-11e7-9887-03449f245407.png)

**Comment by galadril** [comment]
Here the new iphone screenshots:

![simulator screen shot 25 apr 2017 23 32 42_iphone7plusjetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25421252/3aa03314-2a5c-11e7-8369-e52aec1975fa.png)
![simulator screen shot 25 apr 2017 23 33 01_iphone7plusjetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25421253/3aa0336e-2a5c-11e7-9c14-705349e270e1.png)
![simulator screen shot 25 apr 2017 23 33 21_iphone7plusjetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25421254/3aa32d6c-2a5c-11e7-932d-158f0a2a72da.png)
![simulator screen shot 25 apr 2017 23 33 31_iphone7plusjetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25421250/3a9f9878-2a5c-11e7-95ff-d631c02a9802.png)
![simulator screen shot 25 apr 2017 23 32 32_iphone7plusjetblack_portrait](https://cloud.githubusercontent.com/assets/14561640/25421251/3aa00e48-2a5c-11e7-81da-11e4e4457193.png)

**Comment by galadril** [comment]
Most of the switches, toggles, dimmers, sliders, and functions looks to work :-)!!

![d76957de-331d-427a-b0fe-4f269977344e](https://cloud.githubusercontent.com/assets/14561640/25533713/d21e1d10-2c31-11e7-8c68-cd3fa195706a.png)

**Comment by galadril** [comment]
lots of new changes, see first post
- Timers
- Notifications
- Logs
- More options/settings
- Layout fixes

**Comment by galadril** [comment]
Working on 
- Show switches as buttons or switch
- Support for protected switches
- Layout fixes

**Comment by bueno79** [comment]
Awesome. So release of beta 1 is for end of may ? :)

**Comment by galadril** [comment]
Im going fast.. but probably not that fast ;)

**Comment by galadril** [comment]
Done:
    Show switches as buttons or switch
    Support for protected (password) switches
    Add User variables screen
    Add Server logs screen

![logs](https://cloud.githubusercontent.com/assets/14561640/26143643/0f4c7296-3ae6-11e7-9b38-28c4ee7d3236.png)
![uservars](https://cloud.githubusercontent.com/assets/14561640/26143644/0f4ccd2c-3ae6-11e7-92ca-a8d98ceca033.png)

**Comment by galadril** [comment]
Done:
    Add Events screen
    Fixed some issues (multiple times reloading/slow screens)
    New Xamarin Forms updates

![7637c949-3592-4254-9bf3-54812cf23ae1](https://cloud.githubusercontent.com/assets/14561640/26354709/08c01600-3fc6-11e7-9d4c-8d1fc2ad82c8.png)

**Comment by galadril** [comment]
Reworked the whole project to work with theme resources

![theming](https://cloud.githubusercontent.com/assets/14561640/26488121/76b07c8e-4202-11e7-9566-28fbe196c7f9.png)

**Comment by galadril** [comment]
Notifications!!! 

![9ae04eb5-547e-4220-802d-14b273cbd709](https://cloud.githubusercontent.com/assets/14561640/26617043/33afa2f0-45d3-11e7-95ac-887977372156.png)

**Comment by rkluwen** [comment]
Awesome!

------ Origineel bericht ------
Van: "HNO Mobile" <notifications@github.com>
Aan: "domoticz/domoticz-android" <domoticz-android@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Verzonden: 31-5-2017 7:32:05
Onderwerp: Re: [domoticz/domoticz-android] Multi platform app (#414)

**Comment by galadril** [comment]
Next added security panel support:
(not yet the countdown feature>.)

![untitled](https://cloud.githubusercontent.com/assets/14561640/26698640/0e66d7f8-4717-11e7-8790-9099551d84dd.png)

**Comment by galadril** [comment]
Adding graphs

![1](https://user-images.githubusercontent.com/14561640/27277723-79fc91e4-54df-11e7-9826-445f0dc27d49.png)
![2](https://user-images.githubusercontent.com/14561640/27277725-7a1f8456-54df-11e7-82f1-547cdc857b82.png)

**Comment by galadril** [comment]
ios graph screens:

![iphone7plusjetblack_landscape](https://user-images.githubusercontent.com/14561640/27278151-d2236608-54e0-11e7-9c38-e399cb91eeb2.png)
![iphone7plusjetblack_landscape2](https://user-images.githubusercontent.com/14561640/27278154-d2422cd2-54e0-11e7-861f-5876f32f1ecd.png)

**Comment by galadril** [comment]
Continue here
https://github.com/domoticz/domoticz-xamarin
