### ISSUE TITLE
Temperature/Humidity improvements

### ISSUE THREAD

**Issue by jasperslot** [domoticz/domoticz-android#415]
For a little while I  have created a temperature/humidity sensor by using the mysensors framework. This is working great in domoticz, but I see some improvements for the app.

1. On the 'temperature' tab, the sensor displaying correctly, but there is no 'last seen' as on the dashboard. It's pretty weird that I have to go to the dashboard to see more info...
2. When on the 'temperature' tab, I can tick a sensor to go to the graphs, but on the dashboard I can't...
3. The graphs should have thicker lines (or adjustabe by settings), because these lise are very very thin.
4. The temperature & humidity are sharing the same y-axis, I would suggest to put temperature left and humidty right, so the lines come closer together, this looks nicer, but also saves empty screen space (since humidity can go up to 100%). Now they are way to much apart from each other.
5. The graphs have very weird scaling on the x-axis. Why times like 9:33, 10:48? It would be much nicer if this will be 9:00, 10:00... Same goes when using dates in the week/month view. 
6. The graphs have 12H notation on the x-axis, this makes it difficult to see if it's night or day. Please use 24H notation.
7. When I tick somewhere on the graph line, please show a pop-up for the detail information.

The app is great, but when it comes to these functions, I still open domoticz in the browser (on my smartphone) for a better experience.

**Comment by galadril** [comment]
as a reaction on your points:

    When on the 'temperature' tab, I can tick a sensor to go to the graphs, but on the dashboard I can't....
_That's on purpose.. just like the web=ui you need to go to the temperature screen to get the details / graphs_

    The graphs should have thicker lines (or adjustabe by settings), because these lines are very very thin.
_Ill see if I make then thicker_


    The temperature & humidity are sharing the same y-axis, I would suggest to put temperature left and humidty right, so the lines come closer together, this looks nicer, but also saves empty screen space (since humidity can go up to 100%). Now they are way to much apart from each other.
_You can select which line you like to see via the menu butto_n

    The graphs have very weird scaling on the x-axis. Why times like 9:33, 10:48? It would be much nicer if this will be 9:00, 10:00... Same goes when using dates in the week/month view.
_I just post all the logs to the graph api and that scales and show axis..._

    The graphs have 12H notation on the x-axis, this makes it difficult to see if it's night or day. Please use 24H notation.
_I think i can fix this_

**Comment by galadril** [comment]
there is another graph issue thread
