### ISSUE TITLE
Latest beta update broke again all widgets

### ISSUE THREAD

**Issue by apazga** [domoticz/domoticz-android#417]
Galaxy S6 Edge (Android 6.0.1)
- First and last: common switches (first using normal widget, second using reduced widget)
- 2nd and 3rd: Temperature/Humidity sensors. Now showing "battery-level" and a clock icon.

![widgeterror](https://cloud.githubusercontent.com/assets/6894350/25619209/57614db0-2f4a-11e7-8910-664552dca2bb.png)

**Comment by galadril** [comment]
If you keep them this way.. do they cure themself after some time?

Another question, What do you prefer:
1) Remove the widgets totally from the app until I've implemented a correct way of handling widgets?
2) Keep the widgets as they are until I find the fix (or someone who knows more about widgets)??

**Comment by apazga** [comment]
Nope, never cure themself after some time. It happened to me many times. Today I was using default launcher (to see if the problem was related to it).

Obviously second option. It's a beta version. If you want to remove them, do it from the stable version while the community can contribute to fix this issue in beta version.

Anyway, I'm trying to find some time to try to add some work to widgets. I used them some time ago in another app, and I would like to find some time to debug this issue. Hopefully soon.

Thanks for great work in any case @galadril ;).

**Comment by galadril** [comment]
Would be great 👍 
Im not really used to the widget development...

**Comment by galadril** [comment]
I've added a switch in the settings screens to enable/disable widgets so people know that they are in beta and can have some problems

**Comment by galadril** [comment]
I've fixed some widget related stuff today.. lets see if this still happens from v0.2.129 (6183) onwards...

**Comment by galadril** [comment]
Is this still hapening with the latest versions??
