### ISSUE TITLE
Graphic bug with dimmer

### ISSUE THREAD

**Issue by GoranLundberg** [domoticz/domoticz-android#418]
The slider for dimmers is overwriting "last seen" text. Design issue. 
https://i.imgur.com/IWsw4BW.png

**Comment by galadril** [comment]
on the dashboard? or switches screen?

**Comment by GoranLundberg** [comment]
Both. When switched on. When off the slider is not visible.

**Comment by GoranLundberg** [comment]
Using latest version in Google Play

**Comment by galadril** [comment]
Weird that it shows good for me... ill do some other tests

**Comment by GoranLundberg** [comment]
Did you try with a switch name that's on two lines? See the screen shot. Might be the cause.

**Comment by galadril** [comment]
Should be fixed in next beta
![image](https://cloud.githubusercontent.com/assets/14561640/26647629/38035988-4640-11e7-88d8-9d18d645cf6d.png)
