### ISSUE TITLE
Events in Android APP

### ISSUE THREAD

**Issue by trixxor** [domoticz/domoticz-android#419]
Hi,,

For some reason turning events on or off doesnt work in the app.

The current status ( active or inactive ) is shown with no issues, but toggling the event just returns an error.
Im using the newest version app on my Samsung Galaxy S5, with Android v. 6.0.1

**Comment by galadril** [comment]
Do you have the latest beta van f domoticz system? It only works on the
beta

Op 24 mei 2017 1:04 p.m. schreef "trixxor" <notifications@github.com>:

**Comment by trixxor** [comment]
Thank you very much xD
