### ISSUE TITLE
Custom port makes app fail on device switch

### ISSUE THREAD

**Issue by ehallq** [domoticz/domoticz-android#420]
When using another port then 8080, in my case, 80, the app is able to fetch devices, but not switch them. This have never worked for m,has been a bug from day one. Mentioned it in domoticz forum thread long time ago.

**Comment by galadril** [comment]
can you give me a test account?
Im also using custom port without issues.. so

**Comment by galadril** [comment]
???

**Comment by ehallq** [comment]
Yes I can, could I send you it in a private message somehow?

**Comment by galadril** [comment]
heinis.mark@gmail.com (ill remove this post after you email me)

**Comment by galadril** [comment]
Thanks, ill try it out (can be in the next couple of days because im also really busy ;) )

**Comment by galadril** [comment]
I've ran some test.. but I have no clue what hapens..
The app takes the port without any issues..

so if I toggle the switch via web it calls:
http://SERVER/json.htm?type=command&param=switchlight&idx=224&switchcmd=Off&level=0&passcode=
if i toggle via the app it calls:
http://SERVER/json.htm?type=command&param=switchlight&idx=224&switchcmd=Off&level=0&passcode=

which is EXACLTY the same.. and it works on most system..
I do get an exception:

_BasicNetwork.performRequest: Unexpected response code 501 (The HTTP 501 Not Implemented server error response code) _


It looks like it's an issue with the server handling POST request (getting the devices is a HTTP GET request, but updating an device is an POST request)


So it seems more like a server issue than an app issue if you ask me..
I don't get a lot of other users also with this problem...

**Comment by ehallq** [comment]
So what you mean is that the app does POSTs instead of GETS to the api?

**Comment by galadril** [comment]
Sorry not a POST:

For toggling switches it's a PUT request
For getting devices it's a GET request

**Comment by galadril** [comment]
Ill test if the PUT is needed. maybe a GET would also work..

**Comment by galadril** [comment]
That was the fix.. now it works..
thanks for the testing account!

Ill upload a new beta app today
