### ISSUE TITLE
Geofence enter and leave in the same minutes couple of times

### ISSUE THREAD

**Issue by kuipers250** [domoticz/domoticz-android#421]
Hi,

I am running on my Samsung S7 Nougat 7.0. Sometimes when the phone is laying next to me I got a couple of notifications very fast after eachother. Enter/leave.

My fence is 500m from home.

Tried every setting for GPS, GPS+Wifi etc.
Furthermore I am sure Domoticz is excluded from powersafe options.

For now its now usable.

**Comment by galadril** [comment]
Can be a lot of things... device, settings, network/gps strenght on your location, security phone settings, batterij phone settings.. ill close this issue for now.

**Comment by kuipers250** [comment]
Hi

Today i got a new beta version.
It doesn't work anymore. Please help.

Even after reseting app settings,  configure server url again.  It connects
but then a circle.

Please help

Gert

Op wo 21 aug. 2019 11:40 schreef HNO Mobile <notifications@github.com>:

**Comment by galadril** [comment]
Please check
https://github.com/domoticz/domoticz-android/issues/582


Change auth to login page instead of basic auth (thats gettings removed)

**Comment by kuipers250** [comment]
Security wise a good thing.
Will try it tomorrow.
Problem could be that my scripts have trouble login in now.

Groet,
Gert

________________________________

**Comment by kuipers250** [comment]
Unfortunately,  changing to loginpage and restart system didnt help.

Groet,
Gert

[Image][Image][Image][Image][Image][Image]
________________________________

**Comment by galadril** [comment]
Couple of questions

Did you update the beta again? There a new update.

Whats the error that you see? (screenshots?)

What version os domoticz do you run?


Else.. Could you create an account for me to test on your system, and send
the details to domoticz@hnogames.nl


Op za 2 mei 2020 09:57 schreef kuipers250 <notifications@github.com>:

**Comment by kuipers250** [comment]
Hi,

Now I upgraded my server domoticz it seems to work fine ☺

But can you help me with this?
I cannot edit the scripts anymore?


[cid:image001.png@01D62077.0BD00EB0]
