### ISSUE TITLE
com.android.volley.TimeoutError 

### ISSUE THREAD

**Issue by Miesje** [domoticz/domoticz-android#423]
Hi Developer,

I have installed the Lite version and the paid version.
The Lite version does always work without any problem but the paid version does have a connection problem. It seems that the app cannot connect to the server: 

Debugging info
Connection OK
Timeout or no Connection
com.android.volley.TimeoutError 

Sometimes it does work shortly when I deleted the app from my phone because there is new verion of the app. Then it works one time and stop working after that.
My Phone is a: Oneplus 3T with android 
I have given all permission to the app 7.1.1
All connection details are the same like the in the Lite version.

With kind regards,
Mies

**Comment by galadril** [comment]
still an issue?

**Comment by mvroosmalen1970** [comment]
Hi,
I've solved this by disabling the update check in advanced settings. Works perfect now. With this option on it took roughly 5sec before domoticz showed update check failed.. com.android.volley.TimeOutError..
Next the app showed the status of the switches.

Mark
