### ISSUE TITLE
Graph for Utility Sensors is not works

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz-android#425]
I have many utility sensor (Type General, Subtype Alert).
In application, when I click graph (day, etc) is nothing happend.

**Comment by F43RY** [comment]
Same here.

**Comment by JoostvdB94** [comment]
I have this same problem. 
I think this is the primary reason not to buy the premium version for me.

**Comment by F43RY** [comment]
For me 2. I installed lite versione for test but after these issues I don't thing to buy pro version... :-/

**Comment by F43RY** [comment]
For me 2. I installed lite versione for test but after these issues I don't thing to buy pro version... :-/

**Comment by galadril** [comment]
What utility is not working??
Can you give the full json spec of the device?
and what json url does the web ui do to get the graph data?

**Comment by F43RY** [comment]
Specs of jsons are here: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s
Swnsors I cant get working are Voltage (7.18) and Alert (7.20). Both not working graph from android app and correct work from web interface.

**Comment by szczukot** [comment]
I have this same problem :) With Alerts and Voltage.

**Comment by JoostvdB94** [comment]
I have this issue with a custom device I created that displays my internet information (up,down, ping)

**Comment by F43RY** [comment]
Custom device doesn't work for me neither. I created an autonomy battery discharging time with minutes in Y.

**Comment by galadril** [comment]
Sorry graphs are not that easy for me...


Please give me the next information:

Open Firefox with firebug opened (f12 on firefox), open the Console tab
1) Login to your domoticz web system
2) Go to >http://domoticzurl:port/json.htm?type=devices&filter=utility&used=true&order=[Order]&plan=0
3) Give me the json part of the device that's not working  (see example below)
4) Go to the graph page that's not working, and check the Console tab of firebug..
5) I need the json url that that page is using, like:
http://domoticzurl:port/json.htm?type=graph&sensor=counter&method=1&idx=58&range=day
(i need to know what sensor type it's using to get the graph data)
6) I then need the json result on that graph url, (see example below)
http://domoticzurl:port/json.htm?type=graph&sensor=counter&method=1&idx=58&range=day







**_Example device json_**

` 
{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "21.0",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "001411B",
         "LastUpdate" : "2017-08-12 18:38:07",
         "Name" : "ThermostaatTest",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SetPoint" : "21.0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "SetPoint",
         "Timers" : "false",
         "Type" : "Thermostat",
         "TypeImg" : "override_mini",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "204"
      }
`

**_Example graph data_**

`{
   "ValueQuantity" : "",
   "ValueUnits" : "",
   "counter" : "14192.000",
   "result" : [
      {
         "c" : "4918.000",
         "d" : "2016-11-08",
         "v" : "2.000"
      },
      {
         "c" : "4920.000",
         "d" : "2016-11-09",
         "v" : "1.000"
      },
      {
         "c" : "4921.000",
         "d" : "2016-11-10",
         "v" : "0.000"
      },
      {
         "c" : "4921.000",
         "d" : "2016-11-11",
         "v" : "7.000"
      },
      {
         "c" : "4928.000",
         "d" : "2016-11-12",
         "v" : "3.000"
      },`

**Comment by galadril** [comment]
https://github.com/domoticz/domoticz-android/wiki/Graph-information

**Comment by F43RY** [comment]
Ok, now I'm away for a couple of days (only android app available). I'll send you such details as soon as I'm going back home.

**Comment by szczukot** [comment]
Ad 2.
{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "1",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Integra",
         "HardwareType" : "Satel Integra via LAN interface",
         "HardwareTypeVal" : 58,
         "HaveTimeout" : false,
         "ID" : "41",
         "LastUpdate" : "2017-08-31 10:53:49",
         "Level" : 1,
         "Name" : "Zone:Altanka",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : [ 7 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Alert",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Alert",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "51",
         "YOffset" : "0",
         "idx" : "85"
      },

And this is not graph on www. I see list of alerts only.

**Comment by szczukot** [comment]
Ad 2. For Voltage type
{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "1174 mV",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "1wire",
         "HardwareType" : "1-Wire (System)",
         "HardwareTypeVal" : 12,
         "HaveTimeout" : false,
         "ID" : "0001",
         "LastUpdate" : "2017-09-01 10:08:44",
         "Name" : "nasłonecznienie",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Voltage",
         "Timers" : "false",
         "Type" : "RFXSensor",
         "TypeImg" : "current",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "128"
      },

**Comment by galadril** [comment]
@szczukot  
Think i've fixed the graph for Voltage in the next beta... (can't test it ..)

**Comment by galadril** [comment]
Also Lux graphs (value, min, max and avg) are added in the next version

**Comment by szczukot** [comment]
Ok. I will test it.
What with Alert Devices ?

**Comment by F43RY** [comment]
Hi, I'd like to test latest changes. When the update will became available in google paly store?

**Comment by galadril** [comment]
I've fixed the voltage and lux graph, that should already be in the store

**Comment by szczukot** [comment]
I don't have new version.

**Comment by F43RY** [comment]
Me neither. Istill have the same version 0.1.413(3272)

**Comment by galadril** [comment]
sry.. new version coming today

**Comment by szczukot** [comment]
In the newest version Voltage graph works.
Alert still not.

**Comment by galadril** [comment]
that's not that easy.. because i assume there there are graph data.. not log texts..

**Comment by szczukot** [comment]
Is it not this same type of log, as on switches ?

**Comment by F43RY** [comment]
Updated. Thanx.
Percentage is now working but "alert" and "custom sensor" still not. I set custom sensor as battery discharging time of my UPS battery. I'd see minutes of battery life when AC mains miss.

**Comment by galadril** [comment]
i fixed the graph for barometers in the next release

**Comment by szczukot** [comment]
But "Alert" still not works :(

**Comment by galadril** [comment]
I added the log button for Alerts in the next release
