### ISSUE TITLE
Both Geofencing and NFC shows switches and scenes, but you cannot select a scene

### ISSUE THREAD

**Issue by JVaassen** [domoticz/domoticz-android#427]
If I first select a switch in geofencing/NFC, it is selected. And it works.
The scene that you click on is just not overwriting the switch.
Selecting a scene at first means there is no association between tag and scene, it doesn't show up after restarting the app either.

**Comment by galadril** [comment]
![blockly](https://user-images.githubusercontent.com/14561640/30053871-85a43e56-922a-11e7-957c-2b001660b941.png)
![blockly - copy](https://user-images.githubusercontent.com/14561640/30053872-85a81b70-922a-11e7-9a91-5ec740f52efe.png)

**Comment by galadril** [comment]
should be fixed allready

**Comment by JVaassen** [comment]
Hi Galadril,

Thanks for feedback. I did some more testing, with latest version of the App. Some scenes can be selected OK), some can't (NOK): 
Scene 1: "bezoek" =  OK
Scene 2: "Slapen Jos" =NOK
Scene 3: "Slapen Marjan" = OK
Scene 4: "Douchen" = OK
[etc]. 
Changing names doesn't help.
As a attempt I made some new Scenes, but again not all can be selected.

I checked the Domoticz configuration table, and found a very interesting correlation:
All scenes that have an Id-number, where that same Id is also available for a Device, will be selectable.
Scenes that have an Id-number that is not in the device-Id-list (gap in the list), will not be selectable.
So in the list above: Device Id 1,3,4 are present, 2 isn't.

So probably (educated guess) when selecting a scene, the code verifies whether the device-Id exists, instead of checking whether the scene-Id exists.

Let me know if you need more data....
Regards

Jos
