### ISSUE TITLE
Devices list empty when one of sensors run out of batteries

### ISSUE THREAD

**Issue by choxnox** [domoticz/domoticz-android#438]
I have several temperature sensors and if one of them runs out of batteries then when I go to the "Temperature" activity the whole list is empty. I can't get readings from other temperature sensors which are still working.

Same thing happens if I have temperature sensor in a room plan and if that sensor runs out of batteries I can't see any other devices in the same room plan.

Example:

![screenshot_2017-10-29-09-18-51-839_nl hnogames domoticz](https://user-images.githubusercontent.com/1287099/32141825-7c39fc0e-bc8a-11e7-817d-293492a37cbf.png)

If I recharge/replace batteries then application functions as it should.

Domoticz version: 3.8153
App version:  0.1.414
Android version: 7.0

**Comment by galadril** [comment]
could i maybe test this issue with your server?

**Comment by galadril** [comment]
Still the case? i cant reproduce this..
Ill close the case for new, please provide me a test / debug system

**Comment by choxnox** [comment]
Sorry I've completely forgotten about this issue. I don't know if anything changed in the Android codebase since I reported issue but now I've checked it and I also can't reproduce the error which seems like it has been fixed.
