### ISSUE TITLE
Ads on lite version?

### ISSUE THREAD

**Issue by pierre-guillot** [domoticz/domoticz-android#439]
I recently update my domoticz lite APP on my fire (thanks YALP!) and i notice there is now an ads on the bottom of the app.
For my mind it's very "nasty" to see an ads on an android app for domoticz, a open source software...

**Comment by rkluwen** [comment]
There's an easy way out of that, right? Get the full version! I don't understand your complaint.
Open source software is free as in speech, not free as in beer.
