### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by bryan117** [domoticz/domoticz-android#440]
Hi,
I'm trying to compile the latest source with the latest Android Studio, but I get the error:
Error:(1, 0) You appear to have guava-jdk5 on your project buildScript or buildSrc classpath.
This is likely a transitive dependency of another gradle plugin.Run the buildEnvironment task to find out more.
See https://issuetracker.google.com/38419426#comment8 for a workaround.

I've been trying to fix this, but so far I have been unable to do that. The workaround doesn't seem to work for me.

I would like to add the use of bluetooth buttons (see iTracing example) to the core, but I can't even compile the base.

Can anyone help me?

Regards,

Bryan

**Comment by galadril** [comment]
You've updated the gradle version also?
from
classpath 'com.android.tools.build:gradle:2.3.3'
to
classpath 'com.android.tools.build:gradle:3.0.1'

because then you get this issue.. not with the older gradle version 
(still on my list to fix.. :( )

**Comment by galadril** [comment]
you are working form the latest alpha branch right?

**Comment by bryan117** [comment]
That was it.
