### ISSUE TITLE
Graphs with wrong timestamps

### ISSUE THREAD

**Issue by aveenema** [domoticz/domoticz-android#441]
When a graph is created, time values are shifted 12 hours. Noon starts with 0.00 in stead of 12.00. Personaly I would like 24h scale. Or selectable.
![screenshot_20171231-161705](https://user-images.githubusercontent.com/34985325/34462614-eebc5bb6-ee47-11e7-8ede-1eba122ee315.png)

**Comment by aveenema** [comment]
I think this can be resolved by using Calendar.HOUR_OF_DAY instead of Calendar.HOUR. Or you have to do something with AM and PM. For example in file Fragments/Graph.java

**Comment by aveenema** [comment]
Created pull request #442 for this

**Comment by galadril** [comment]
Looks good, but we only develop via the alpha development branch.
Ill add your change to that branch
