### ISSUE TITLE
Security Panel delay

### ISSUE THREAD

**Issue by Hexagon** [domoticz/domoticz-android#447]
The security panel does not work as expected, the API call (setsecstatus) is currently sent _after_ the 30 second delay. This delay is built in into domoticz itself and shouldn't be handled by the client.

As a result of this, if you dont wait for the countdown to complete (close the app or press cancel) the alarm is never armed. Also it takes 60s instead of 30s to arm.

You can of course keep the countdown, but just as an indicator.

Version: Paid app, 0.1.420

**Comment by galadril** [comment]
Ill test this

Op 7 jan. 2018 20:00 schreef "Hexagon" <notifications@github.com>:

**Comment by Hexagon** [comment]
Thanks for the quick response! But Hmm, guess you can put this on hold. This is just an inconsistency between domoticz built in security panel and the android app.

To clarify: the delay is not build into domoticz, just my personal implementation, as the web interface panel arms immediately.

**Comment by Hexagon** [comment]
A quick look at old forum threads indicate that the api call is supposed to be fired instantly lile the built in panel, to allow (as an exanple) the system to play a sound while arming etc.

So the bug is still relevant.

**Comment by Hexagon** [comment]
After further research: Removed previous comments, that was totally wrong :)

**Comment by Hexagon** [comment]
Simplest way to test is to create a dzVents-event and watch the logs. App will countown for 30s, then it will take another 30s before the event is fired. (or 45+45 if you change the delay in settings).

[code]
return {
	on = {
		security = {
		   domoticz.SECURITY_ARMEDHOME,
		   domoticz.SECURITY_ARMEDAWAY,
		   domoticz.SECURITY_DISARMED
		}
	},
	execute = function(domoticz, device)
	    domoticz.log(domoticz.LOG_INFO)
	end
}
[/code]
