### ISSUE TITLE
Google Assistant integration

### ISSUE THREAD

**Issue by apazga** [domoticz/domoticz-android#449]
Hi,

Just asking if is there any plan to integrate the app with "Google Assistant" via the new "Actions on Google":
https://developers.google.com/actions/extending-the-assistant

Best regards!
Abel.

**Comment by galadril** [comment]
Sry don't see how to integrate with domoticz at this moment

**Comment by Lyr3x** [comment]
You should use the google assistant setup provided via controlicz instead

**Comment by galadril** [comment]
Yea controlicz works super!
