### ISSUE TITLE
YouLess graphs are messed up

### ISSUE THREAD

**Issue by Jaap-Jan** [domoticz/domoticz-android#46]
I think the Domoticz Youless plug-in returns information in a way different from other energy monitors.

An item looks like this:
      {
         "c" : "70074.904",
         "d" : "2015-12-15",
         "v" : "2.434"
      },

"c" is the meter reading. If you'd have an electricitity meter with a single tariff, this would be the value you'd read. "d" is the date of cause and "v" represents the amount of electric energy consumed on that date.

In the graph "c" is mapped to COUNTER and v is mapped to the percentage.

The graph looks like this.
![device-2016-01-09-002625](https://cloud.githubusercontent.com/assets/804104/12212201/e7a366ea-b667-11e5-8bfd-5f32f774f857.png)

Complete example output: https://gist.github.com/Jaap-Jan/902626c8be6da40195c1

**Comment by galadril** [comment]
RoadXY you've fixed this right??

**Comment by RoadXY** [comment]
No, Youless want working at all when I looked at it.

**Comment by Jaap-Jan** [comment]
With the [patch of Inversion-NL](https://github.com/domoticz/domoticz-android/commit/0ce0ce90d2768bb8c0cc18098879b9f384d4e8ae) it should at least do something, but now you have the problem I described...

**Comment by RoadXY** [comment]
Inversion-NL is my dev account :D

**Comment by RoadXY** [comment]
Unfortunately I don't have a Youless so it's very difficult to troubleshoot.

**Comment by Jaap-Jan** [comment]
https://vdvn.net/domoticz/
User: dev
Pass: test

But I don't think the problem is fixing this, but making sure other stuff doesn't break.

**Comment by galadril** [comment]
Think we can close this case.. we've improved graphs and you can now filter which lines you like to see
