### ISSUE TITLE
Log for a dummy sensor doesn't work

### ISSUE THREAD

**Issue by vahempio** [domoticz/domoticz-android#462]
I have several dummy sensors in domoticz (mainly distance_level & temperature) which are updated every 1 minute.

It is impossible to see logs of these sensors (neither day/week/month/year), the screen of the app blinks and nothing is displayed. No issues for "classic" sensors.

Thank you!

**Comment by galadril** [comment]
Can you send me a viewer account on your system so I can debug against your system?
domoticz@hnogames.nl

**Comment by galadril** [comment]
(sry for the late response)

**Comment by galadril** [comment]
no info
