### ISSUE TITLE
Request: Small 1x1 widget for temperature sensors

### ISSUE THREAD

**Issue by MiloshCZ** [domoticz/domoticz-android#464]
Hi,
Ïs it possible to add small (1x1) widget for temperature devices?

Thank You

**Comment by galadril** [comment]
It became a 2x1 widget for temperatures, hope your happy with it ;)

![Screenshot_2019-08-01-08-46-06-665_com miui home](https://user-images.githubusercontent.com/14561640/62271840-e9ca5e00-b439-11e9-8188-c83c44c2dc86.png)
