### ISSUE TITLE
Implement .fit() to load camera images

### ISSUE THREAD

**Issue by sboele** [domoticz/domoticz-android#465]
When selecting a camera in the app it doesn't fit the camera image completely. Especially in portrait mode. Picasso has a .fit() function to fit the image to the view.

Zoom in/out and moving functionality would also be nice to have to make the camera feature more useful.

**Comment by galadril** [comment]
you could make me a pull request for this

**Comment by galadril** [comment]
The camera screen is already changed in the latest version
