### ISSUE TITLE
RGB, WW, RGBW Color Picker

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz-android#466]
Since the new color picker is implemented in the latest beta. (https://github.com/domoticz/domoticz/issues/2078)
The Android App should give the possibility to set the White Temperature 👍

**Comment by galadril** [comment]
Trying to improve on this... see first results:

### RGB Dialog
![screenshot_2018-10-12-11-15-14-830_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/46860374-99353600-ce10-11e8-9448-3eea2f04ebe8.png)


### WW Dialog 
![screenshot_2018-10-12-11-15-24-159_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/46860380-9afef980-ce10-11e8-9707-f84b3f97ba91.png)

**Comment by Lyr3x** [comment]
Sweet!

**Comment by galadril** [comment]
The ww switch still doesn't work 100%, still working on it...

But on the same topic, i've added full light and night light buttons to the info dialog of the color/rgb switches:

![screenshot_2018-10-15-11-51-37-654_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/46943871-eadbfb80-d070-11e8-9815-1c43a60b6a3a.png)

**Comment by Lyr3x** [comment]
For my HUE lights, the night light switch aint do anything. Is it correct that the WW-switch is not available in the latest beta?

**Comment by galadril** [comment]
Does your domoticz web ui has the same nightlight/ full light options>? and do they work?
I use the same domoticz api, and think that they work the same. 

(So maybe they are intended to work via events/scripts??)

and yes WW should be in the latest version

**Comment by Lyr3x** [comment]
> Does your domoticz web ui has the same nightlight/ full light options>? and do they work?
I use the same domoticz api, and think that they work the same.

Will check this later.

> and yes WW should be in the latest version 

Cant access the new picker for my Hue lights.

**Comment by galadril** [comment]
hmm.. i have RGB.. and WW.. but not the combination 🗡

**Comment by galadril** [comment]
Think this is better then

![screenshot_2018-10-24-20-13-02-321_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/47452093-a4ea0a80-d7c9-11e8-8176-73720c5f7138.png)
![screenshot_2018-10-24-20-13-06-349_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/47452095-a61b3780-d7c9-11e8-91f9-9cd5c434b234.png)

**Comment by Lyr3x** [comment]
Thank you I'll test as soon as possible!

**Comment by galadril** [comment]
As discussed on Discord, ill keep it with the slider for now.

**Comment by galadril** [comment]
Woops.. hit the close button as soon as you closed it :) so it became a reopen button
