### ISSUE TITLE
selector switch buttons are corrupt

### ISSUE THREAD

**Issue by balintkozma** [domoticz/domoticz-android#467]
Selector switch buttons are corrupt because of domoticz issue #2389. See the end of the thread, it is corrupted the same way as the dashboard widget was.

![image](https://user-images.githubusercontent.com/15109984/40445899-c368a4a0-5ecd-11e8-9cad-fa47507efcec.png)

It was fixed on the dashboard in this diff
https://github.com/domoticz/domoticz/commit/cac7ba3bfc4b00e755338c200eb383548ca931f7#diff-875fd2c68ba82f04d7b9b437a689d84f

**Comment by galadril** [comment]
i see.. thanks for the report.
ill fix this tomorrow and i'll push new version on the play store.

**Comment by galadril** [comment]
it looks like that the selectors settings pages on Domoticz also look weird:

![afbeelding](https://user-images.githubusercontent.com/14561640/40483768-69f6d162-5f59-11e8-989c-ef64dae1c231.png)

**Comment by balintkozma** [comment]
Ctrl + F5 fixed that for me, using the latest beta. I use a dummy selector switch.

**Comment by balintkozma** [comment]
![screenshot from 2018-05-24 13-55-10](https://user-images.githubusercontent.com/15109984/40483926-1a6f5f28-5f5a-11e8-8ec9-15239bfeb7f5.png)

**Comment by galadril** [comment]
true.. after clearing my refreshes the settings looks good

**Comment by galadril** [comment]
There is a new version pushed to the app store with the fixed selector switches. 
Closing this issue 👍
