### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by nayrnet** [domoticz/domoticz-android#47]
Domoticz needs love on the home TV, each room in my house has an affordable Nexus Player (Android 6.x) wired into the LAN yet no good way to access Domoticz through a simple bluetooth remote.

Missing out on a golden opportunity by focusing on touchscreen devices only.

**Comment by RoadXY** [comment]
The thing is, there aren't a lot of Android TV's around.
But @galadril already made an first attempt but to create a real nice interface, will need quite a lot of work.

**Comment by nayrnet** [comment]
Google Nexus Player
Amazon Fire
Nvidia Shield
some models of Sony/Sharp/Samsung and Phillips all have Android TV built in
and there is more

most android apps run just fine if I sideload them and use a bluetooth touchpad, usually the only missing is the ability to navigate using a directional pad.. I'll see if I can sideload domoticz-android.

**Comment by RoadXY** [comment]
Already made Domoticz for Android TV.
It's just not ready and there are bugs to fix

**Comment by nayrnet** [comment]
Sweet, this would really help me out.. in Domoticz I have switches to select video inputs on my receiver. I would love to be able to change directly to a desired input from the nexus player.

**Comment by RoadXY** [comment]
If you know how to build you could build the leanback branch yourself and play with it

**Comment by RoadXY** [comment]
If got a build version ready:
https://drive.google.com/file/d/0B_V5YXKQnKIaWG5acVJFcDR5dUE/view?usp=docslist_api

Don't share and don't report any bugs please.
A mouse is required to fully control the app on Android TV.

**Comment by nayrnet** [comment]
looks good, its almost there.. was able to use d-pad for most things.. alot more usable than the web app with merely a remote.

I am thinking it needs a different view/style to utilize the big-screen better.. like devices displayed in a grid much like apps sort video for the TV.. I know from my little bit of android experience its pretty easy to get the leanback launcher to display an alternate style from the mobile app.

**Comment by galadril** [comment]
https://www.domoticz.com/forum/viewtopic.php?f=37&t=12955
