### ISSUE TITLE
(Feature Request) simple notification mailbox

### ISSUE THREAD

**Issue by MaartenJB** [domoticz/domoticz-android#479]
Hi,

It would be (very) nice if it was be possible to have a simple notification mailbox like NotifyMyAndroid (NMA) used to be, so it is possible to read back messages that have been sent. I had NMA setup with different ringtones depending on the notification priority. This was working great until the nma service stopped. Would be great if a similar function was included in this domoticz android app.

Best regards,

Maarten 

for reference:
![notify-my-android-1](https://user-images.githubusercontent.com/16285840/42683779-9881597e-868e-11e8-9a5c-8db0e5a0dd05.jpg)

**Comment by galadril** [comment]
There is already the possibility to read all the last Notifications u der
de Notification settings.

Is that what you mean?




Op vr 13 jul. 2018 11:20 schreef MaartenJB <notifications@github.com>:

**Comment by galadril** [comment]
I wont be dont this feature request.. It looks like Android Q has a notification inbox/assistant build in..
So it would be better to let Android OS handle the notifications fully.

**To read on Android Q**
https://www.computerworld.com/article/3333807/android-q-notification-inbox.html
https://www.computerworld.com/article/3390668/android-notification-assistant.html

**Comment by galadril** [comment]
Just so you know, im reworking the notification history page.. so its a bit of a notification inbox

![Screenshot_2020-02-05-10-27-05-070_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/73828903-5c116600-4802-11ea-86a3-b9d177c1d64b.jpg)

![Screenshot_2020-02-05-10-27-09-924_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/73828908-5ddb2980-4802-11ea-8ec2-f731765281aa.jpg)
