### ISSUE TITLE
Camera picture is not visible in Domoticz android app

### ISSUE THREAD

**Issue by Milan1989** [domoticz/domoticz-android#484]
Hi,

I add a hikvision IP camera in Domoticz (V4.9700). It is working properly.
The picture of the camera in Domoticz android app is not visible.

Please help me what additional settings are necessary.

**Comment by iffen5** [comment]
have you try With admin rights?  I found issue's to use user or viewer.

**Comment by Milan1989** [comment]
Sorry I don't understand. Where should I use admin right? The camera is working properly on Domoticz server, only the Domoticz android app is the problem.

**Comment by iffen5** [comment]
yes. you have to be admin to see cameras in app. This doesn't matter on the PC It's Only affect the App

**Comment by iffen5** [comment]
the user you logged in with

**Comment by Milan1989** [comment]
Ok, only one user is in my Domoticz. It is admin.

**Comment by Milan1989** [comment]
This problem has been solved by the Domoticz android app update.
