### ISSUE TITLE
Ads are too big (or view is not scrolling far enough)

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz-android#485]
Ads are too big (or view is not scrolling far enough).
In my case the ads below in the app is blocking a slider from a dimmer/shutter control.
So I cannot set my shutters to a specific percentage.

See screenshot:
![screenshot_20181004-140129](https://user-images.githubusercontent.com/25199588/46472860-ce250580-c7de-11e8-8a8f-e222071a73c2.png)

**Comment by galadril** [comment]
Ill test this in the next big release
