### ISSUE TITLE
does not vibrate upon receiving a notification

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#491]
I have a G4 motorola and for many versions it does not work the option to vibrate when receiving a notification.
Greetings,

**Comment by galadril** [comment]
Notifications do vibrate if you configure that within the app settings via your system phone settings.
So within the app, go to settings/notification settings then click on the 'Settings' button

That takes you to the app settings of your android system. There you can configure various options for the notifications (like vibrate) 

![screenshot_2018-10-22-09-55-25-904_com android settings](https://user-images.githubusercontent.com/14561640/47282768-c045f180-d5e0-11e8-9010-e99be2a1f433.png)

**Comment by turin400** [comment]
I close it because I think it is not a problem of the application because other notifications of other applications do not vibrate either.
Thanks for all. Greetings.
