### ISSUE TITLE
problem with the English language in version 0.2.4 (4820)

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#492]
When I enter the temp target option, when I click on set, two buttons that are not in English come out. It also happens when changing the value in user variables.

Greetings,

**Comment by galadril** [comment]
Can you maybe add screenshots of this issue?

**Comment by turin400** [comment]
![screenshot_20181021-224643](https://user-images.githubusercontent.com/42274403/47272359-c1e1cc00-d584-11e8-9cca-ba04d46e1f4e.png)

**Comment by turin400** [comment]
previous window:

![screenshot_20181021-230249](https://user-images.githubusercontent.com/42274403/47272408-83004600-d585-11e8-8dc2-a5c46eeb1c9b.png)

**Comment by turin400** [comment]
In Spanish the button with the word "DEIINIR" appears in two pieces badly written . That's why I switched to English and found what I mentioned earlier.

![screenshot_20181021-230525](https://user-images.githubusercontent.com/42274403/47272457-539e0900-d586-11e8-8737-6748ac9cf603.png)

**Comment by galadril** [comment]
Cant reproduce.. ive set the language to english while system language = dutch. and it's correctly translated by me

**Comment by turin400** [comment]
I have put the language of the system in English and the language of domoticz tb and this is the result.
I do not know what more information to offer, my phone is android 7.0 moto g4. Whatever you need, tell me.

![screenshot_20181024-234319](https://user-images.githubusercontent.com/42274403/47463813-9d395e80-d7e7-11e8-8370-5880c91b80db.png)
![screenshot_20181024-234333](https://user-images.githubusercontent.com/42274403/47463816-a0cce580-d7e7-11e8-8739-a57aae2731a1.png)
![screenshot_20181024-234337](https://user-images.githubusercontent.com/42274403/47463824-a5919980-d7e7-11e8-8262-e3f6007a5b8e.png)

**Comment by turin400** [comment]
The language I have in the system is usually Spanish and as I said I changed it to English because they did not get the word "DEFINIR" complete in some buttons and I found this problem.
A greeting.

**Comment by turin400** [comment]
I have tried the lite version on my wife's phone and this problem does not occur. It's an android 7.1.2, so the problem is my terminal.
