### ISSUE TITLE
Temperature and weather location

### ISSUE THREAD

**Issue by Lyr3x** [domoticz/domoticz-android#493]
I really like the new design but putting _temperature_  and _weather_  devices under the _switches_  activity feels weird to me. There is nothing to switch so they should get their own activity again. 

If you decide to do this, it would be nice to put the remaining three buttons centered

**Comment by galadril** [comment]
dont really know about this.. i thought that it maked sense to put the most used device screens next to eachother.. maybe the naming 'switches' should be something different then

**Comment by galadril** [comment]
Thanks

**Comment by Lyr3x** [comment]
I really like the new structure 👍

**Comment by galadril** [comment]
Thanks.. next release also contains custom drag / drop sorting  as the next big feature

Are you a beta tester already?

**Comment by Lyr3x** [comment]
> next release also contains custom drag / drop sorting as the next big feature
interesting! Just local sorting or will it update the order in domoticz itself?

> Are you a beta tester already?
Yeah sure!

**Comment by galadril** [comment]
Local device sorting.. so it doesn't change the server sorting.

See the first demo gif here;
https://user-images.githubusercontent.com/14561640/47802675-1b8a8900-dd31-11e8-96cc-1a6b1e3dd96e.gif

and another gimic on scrolling down (hiding the action bar for better visibility):
https://user-images.githubusercontent.com/14561640/48126841-86344b00-e282-11e8-9738-247aa8cd0d04.gif

**Comment by Lyr3x** [comment]
Nice feature. Looking forward to test it 👍
