### ISSUE TITLE
camera is not visible för user rights "user" and "viewer"

### ISSUE THREAD

**Issue by iffen5** [domoticz/domoticz-android#495]
I can't see the cameras when I am user or viewer.

 I can only see camera If I am admin this works on a PC but not on my Android in the App.

**Comment by iffen5** [comment]
is there anyone who can fix this issue?  If this bug can be eliminated we can use Domoticz to all of our member in our club. (100 people).
anyone?

**Comment by iffen5** [comment]
"Ops something went wrong
Invalid user information"

I think I use viewer drives on this user I will try it tomorrow to use user rights and I will try and send send you a message again If I get the same error message but if I use admin rights I don't have this problem it works perfectly without any problems regards Ingemar

Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: T-bond <notifications@github.com>
Datum: 2018-12-12 21:27 (GMT+01:00)
Till: domoticz/domoticz-android <domoticz-android@noreply.github.com>
Kopia: iffen5 <ingemar_from@hotmail.com>, Author <author@noreply.github.com>
Rubrik: Re: [domoticz/domoticz-android] camera is not visible för user rights "user" and "viewer" (#495)


What is happening when you try to watch the cameras?
Any error message or log?

**Comment by iffen5** [comment]
I tried to change to my user to rights "user" from Viewer but the results is the same 

" OPS 
Something Went wrong
Invalid useri nformation"

**Comment by T-bond** [comment]
What is your application version?

**Comment by iffen5** [comment]
0.2.40 (5189)





Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: T-bond <notifications@github.com>
Datum: 2018-12-16 19:15 (GMT+01:00)
Till: domoticz/domoticz-android <domoticz-android@noreply.github.com>
Kopia: iffen5 <ingemar_from@hotmail.com>, Author <author@noreply.github.com>
Rubrik: Re: [domoticz/domoticz-android] camera is not visible för user rights "user" and "viewer" (#495)


What is your application version?

**Comment by galadril** [comment]
I've changed the app for better user management. 
You dont see the options camera/events/log/uservariable if your not an admin.

**Comment by iffen5** [comment]
No?

I need to see camera pics  even if I'm user or viewer

just now it's only admin who can see camera pictures and this is not ok.

I'm admin and 50 user at my flightclub who will check out our cameras.

regards ingemar



Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: HNO Mobile <notifications@github.com>
Datum: 2019-01-16 09:15 (GMT+01:00)
Till: domoticz/domoticz-android <domoticz-android@noreply.github.com>
Kopia: iffen5 <ingemar_from@hotmail.com>, Author <author@noreply.github.com>
Rubrik: Re: [domoticz/domoticz-android] camera is not visible för user rights "user" and "viewer" (#495)


I've changed the app for better user management.
You dont see the options camera/events/log/uservariable if your not an admin.

**Comment by iffen5** [comment]
Hi
I did some test and it's still don't working.  I have the latest version of domotizc app. I'm beta tester.
Version 0.2.70 (5422)

I have a user named "hanso" first I gave him clearence to all device and user "user" 
He couldn't se Pictures of cameras. Instead it's was errortext of "Ops. Something Went wrong. "

I changed user hanso to "Viewer" and the result is the same

I changed user hanso to "admin" and Everything works

Regdards Ingemar

**Comment by T-bond** [comment]
I think I get what is the problem.
An user with viewer permission has no access to the cameras' list. (https://host:443/json.htm?type=cameras) gives 403 (forbidden).
But if you attach a camera image to a switch you can query that camera even with viewer permission. (https://host/camsnapshot.jpg?idx=2&count=358?t=1548169366835 )

So I think not showing the cameras in the Android App is the correct solution, so this issue should be closed.

I also understand that you would like to give access to the people with viewer rights to view the cameras, but I think this should be changed on the Domoticz server first, and only reflect these changes in the app after that.

(I also noticed, that you can access cameras with the given link, when it is not attached to a switch, so it maybe can be considered as a security issue and should be fixed also on the Domoticz server, or give users right to access all the cameras)

**Comment by T-bond** [comment]
Yes. If you login with an user account, and try to access then `/json.htm?type=cameras` you will get a 403 on the Domoticz server itself.

**Comment by galadril** [comment]
Are you going to create an issue request on Domoticz github? and can we close this one?

**Comment by iffen5** [comment]
Can you help me with this I tried to open in issue at domotics Forum but I never got any Attention Can you help me to create an issue with this best regards Ingemar



Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: HNO Mobile <notifications@github.com>
Datum: 2019-02-04 19:57 (GMT+01:00)
Till: domoticz/domoticz-android <domoticz-android@noreply.github.com>
Kopia: iffen5 <ingemar_from@hotmail.com>, Author <author@noreply.github.com>
Rubrik: Re: [domoticz/domoticz-android] camera is not visible för user rights "user" and "viewer" (#495)


Are you going to create an issue request on Domoticz github? and can we close this one?

**Comment by iffen5** [comment]
You can close this . I open a new issue in #3059 Bugs in user rights for cameras in domoticz/domoticz

**Comment by gizmocuz** [comment]
Made a new JSON call in the code:

[414dfe3](https://github.com/domoticz/domoticz/commit/414dfe3d6608dd3587bc145be0ade6bf8321ebd4)

/json.htm?type=cameras_user

With this you now get the enabled camera's with IDX and Name

Could you work with this ?

**Comment by iffen5** [comment]
yes of course but i have not a clue where to put the code :) Sorry
You mean to update the code and downloade it on thr RPI?

Where to put  /json.htm?type=cameras_user???

Can you give me a hint

**Comment by galadril** [comment]
@iffen5  i think that i need to use that url/json call to get the cameras for which the user has enough rights for

**Comment by gizmocuz** [comment]
@galadril , we can think about this... but maybe a 'user' should be able to see them, and a viewer not ?
Or maybe both
The problem with the previous json call is that it returned also the username/password, ip address etc
that is not needed with the new call, you get the 'idx' which you can use to take snapshots

If someone is allowed to login, should he/she be allowed to see the camera's ?

I can think of some camera's i would like to keep private ;)

**Comment by galadril** [comment]
Maybe it could be handy if you can assign cameras to a user, just like you get assign all, or specific switches to a user?

**Comment by gizmocuz** [comment]
@galadril , that's a great idea ! have to see how this could be done
At the moment, you can assign switches to a camera... and when you do so, there will be a camera icon on the top right of the widget you can click to view the camera
For example a doorbell switch, with the door camera
Maybe this mechanism could be used to identify if a user has the right to view the camera
