### ISSUE TITLE
Invalid searchable metadata

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#50]
system_process W/SearchableInfo: Invalid searchable metadata for nl.hnogames.domoticz.premium/nl.hnogames.domoticz.WidgetConfigurationActivity: Search label must be a resource reference.
system_process W/SearchableInfo: Invalid searchable metadata for nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity: Search label must be a resource reference.
system_process W/SearchableInfo: Invalid searchable metadata for nl.hnogames.domoticz.premium/nl.hnogames.domoticz.WidgetConfigurationActivity: Search label must be a resource reference.
system_process W/SearchableInfo: Invalid searchable metadata for nl.hnogames.domoticz.premium/nl.hnogames.domoticz.MainActivity: Search label must be a resource reference.

**Comment by RoadXY** [comment]
This should solve it:
http://developer.android.com/guide/topics/search/searchable-config.html

**Comment by galadril** [comment]
This already works...
