### ISSUE TITLE
switch door contact state on app

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#500]
I found that you can change in the app the status of the door contact interuptors when they are only to display the status. I do not know if I'm right.
My app version is 0.2.40 (5189).

**Comment by galadril** [comment]
Please explain the issue a bit more with some screenshots

**Comment by turin400** [comment]
In the app the door contact switch can be changed by clicking on the (red circle) while in Domoticz you can not change the state by clicking on it. It is considered as a contact.
I think you should not be able to change the status in the app, it is not logical that you force the open or closed state of a window, I think it should be read only. As in Domoticz. Thank you.


I have updated to version 0.2.41 (5189) and the same thing happens.


Thank you.


![captura1](https://user-images.githubusercontent.com/42274403/50160993-d8817680-02da-11e9-93c5-a97092bc6e23.JPG)
![captura](https://user-images.githubusercontent.com/42274403/50160999-dc14fd80-02da-11e9-8351-2a982d1c5663.JPG)

**Comment by galadril** [comment]
I've changed the door lock inverted type in last release. Does this also fix your problem (probably not)

**Comment by turin400** [comment]
No, it does not solve the problem. The switch door contact is different from the switch door lock , the first one is like the switch motion sensor (it does not change the state when you click on it), it only shows the status.
![captura](https://user-images.githubusercontent.com/42274403/51265384-f82ebc00-19b8-11e9-8a65-1e9000b2a5cd.JPG)
![inkedscreenshot_20190116-174638_li](https://user-images.githubusercontent.com/42274403/51265558-5b205300-19b9-11e9-8d79-7f52ddc0fa8c.jpg)

**Comment by galadril** [comment]
Thank you for your patience, should be fixed in the next version

**Comment by turin400** [comment]
Do not worry it was not a serious problem, the important thing is that it is already solved. Thank you so much for everything.
A greeting.
