### ISSUE TITLE
Update the new Timer types

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#502]
**Describe the bug**
The list of timer types is updated in Domoticz, please also adjust in the app

**To Reproduce**
1. Create a timer with on of the new types
2. Check in the app

**Screenshots** !!!
![image](https://user-images.githubusercontent.com/14561640/50834088-6d641680-1353-11e9-9f06-e6281d3e221c.png)

**Comment by SyedOmar** [comment]
Hello @galadril , can we contact on email or something. Want application development.

Thank You

**Comment by galadril** [comment]
domoticz@hnogames.nl
