### ISSUE TITLE
on android 5.x

### ISSUE THREAD

**Issue by phicarre** [domoticz/domoticz-android#504]
Hi,
Does this app run on Android 5.02 (Lollipop) ?
I installed the lite version, started it and received a message: domoticz is stopped

**Comment by galadril** [comment]
it should work on android 5 yes, ill quickly do some tests if i made an issue last release..!

**Comment by galadril** [comment]
I've tested the app also on Android 5.0 and I have not encountered any issue.
Please make screenshots of your issue

**Comment by phicarre** [comment]
![img_20190112_134927](https://user-images.githubusercontent.com/194631/51073473-892c2d00-1671-11e9-9de7-72e97c9b8d10.jpg)

**Comment by galadril** [comment]
ill upload a new beta today, are you a beta user, so could you test this?

**Comment by galadril** [comment]
To enable beta testing:
https://play.google.com/apps/testing/nl.hnogames.domoticz.premium

**Comment by galadril** [comment]
Version 0.2.58 (5359)

**Comment by phicarre** [comment]
Same problem with the version 0.2.61 (5365)

**Comment by WilcoVertegaal** [comment]
I see it right after configuring the app, and then every time as soon as I try to re-open it.

**Comment by phicarre** [comment]
For me, just after the installation

**Comment by phicarre** [comment]
0.2.63 (5379): not better

**Comment by galadril** [comment]
Can you maybe retrieve the crash report?

**Comment by WilcoVertegaal** [comment]
How can we do that?

**Comment by galadril** [comment]
You could do it via:

Via a catlog app like described here:
https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/

Or via adb:
https://www.loginworks.com/blogs/get-crash-logs-android-applications/

**Comment by galadril** [comment]
The weird thing is that i dont see any new crash reports on the last version (btw the latest version is 0.2.70)

**Comment by galadril** [comment]
or maybe its because of your domoticz home setup, i could test against your system if you create a view account for me and send the details to my email domoticz@hnogames.nl

**Comment by WilcoVertegaal** [comment]
> or maybe its because of your domoticz home setup, i could test against your system if you create a view account for me and send the details to my email [domoticz@hnogames.nl](mailto:domoticz@hnogames.nl)

Done!

**Comment by WilcoVertegaal** [comment]
Domoticz app connected to the same server is running fine on my Android 8.1 Nexus 5X btw.

**Comment by galadril** [comment]
Its indeed not your domoticz system

**Comment by WilcoVertegaal** [comment]
It seems that the overnight app update has solved the problem for me. Could that be possible? I just tried to produce a crash report, but instead it just opened ... Can't find any problems currently.

**Comment by galadril** [comment]
great to hear!
I did fix as much as crash reports that i could find yesterday 🗡

**Comment by galadril** [comment]
Thanks, im closing this issue because the crashes are resolved.
(Please leave a review on the play store if your happy with my assistant 👍  )
