### ISSUE TITLE
problem with -loglevel in domoticz

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#516]
When I start domoticz with the option -loglevel status,error 
I do not have any messages in the records window.

it only works with the option -loglevel normal

I have version 0.2.7.8 (5584)

**Comment by galadril** [comment]
So the generic domoticz log?
Any ideas if the api is giving different results then also?

We use the next url for getting the system log:
json.htm?type=command&param=getlog

**Comment by turin400** [comment]
the api has changed in the latest versions and as indicated if the loglevel is not indicated the default is normal and I have only activated -loglevel status, error that is why I think it shows nothing.
I think it would be nice to have several tabs in the app registry with the normal loglevel, status and error and request them domoticz with the new api.

[https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Retrieve_Domoticz_logfile_information
](url)

You can get the last couple (fixed at max. 100) of logmessages with: 
/json.htm?type=command&param=getlog&lastlogtime=LASTLOGTIME&loglevel=LOGLEVEL 

 LOGLEVEL 1 = normal
          2 = status
          4 = error
  268435455 = all
 LASTLOGTIME  starting with logmessages in LASTLOGTIME seconds since last epoch ( 0 = all available)   

(In older versions &loglevel is ignored and the system will return all types) Somewhere around V3.9580 this changed and without the loglevel set, the system will only return type 1 messages

**Comment by galadril** [comment]
It's coming today on a new beta version

**Comment by turin400** [comment]
perfect, I wait for the download and I'll tell you. A greeting

**Comment by turin400** [comment]
It looks good. I have only found one small thing, when you select the error filter for example and you do not have errors in the Domoticz log, a window is generated that indicates that there is no data in the server, correct, but when you choose another filter again example "All" does not reload the window and to go back out the log you have to exit and enter again in the option of records.

**Comment by turin400** [comment]
it happens whenever you do not find data in the server for example if in domoticz you have the option "-loglevel status, error" if you select the filter "normal" indicates that there is no data in the server and when pressing the filter "status" the same window continues to come out , you have to leave and enter again the option of records.

**Comment by galadril** [comment]
Should be fixed
