### ISSUE TITLE
Timeout error 

### ISSUE THREAD

**Issue by mvroosmalen1970** [domoticz/domoticz-android#517]
Hi,
After the recent update (0.2.78(5584)) the domoticz app is not working anymore. With debug on, the app reports connection OK and after 30sec or longer it reports a timeout. No switches etc. Before this version everything worked perfectly except when I had the update check on. This also caused delays and sometimes timeout errors, however still with all switches etc updated. Next to this problem it also causes domoticz(4.9700) to crash, most of the time when I refresh in the app (with the timeout interval).

Any suggestions?? or can you send me the old version of this APP? I've tried already with a fresh install. This is no solution.

Mark

**Comment by galadril** [comment]
Ive noticed the bug also today.. Ill try to work on a fix this weekend.
To solve it temporarily go to settings and import your previous settings again (if you exported it before the issue)

It's a hard bug to fix because it has no clear cause yet.. :(

**Comment by mvroosmalen1970** [comment]
Pitty I've no export :-(. Will wait for a solution. can I revert back to
the version before the weekend?

Mark

Op vr 1 feb. 2019 om 18:13 schreef HNO Mobile <notifications@github.com>:

**Comment by galadril** [comment]
Reset settings and reconfigure also works

Op vr 1 feb. 2019 18:53 schreef mvroosmalen1970 <notifications@github.com:

**Comment by mvroosmalen1970** [comment]
Done, but didn't solve the issue.... Open Domoticz app, settings, advance
settings, Opnieuw instellen-->OK. App closes. Wizard>> local IP with
HTTP--> devices found--> dashboard, oeps:-( timeout...schakelaars selected,
again wait..... nothing


Op vr 1 feb. 2019 om 18:54 schreef HNO Mobile <notifications@github.com>:

**Comment by mvroosmalen1970** [comment]
settings--> debug>> connection OK--> crash send feedback done. Domoticz on
Raspi not responding...

Op vr 1 feb. 2019 om 19:01 schreef Mark van Roosmalen <
mh.van.roosmalen@gmail.com>:

**Comment by galadril** [comment]
Weird, i've not been able to test this issue. 
Could not reproduce it this weekend.

**Comment by mvroosmalen1970** [comment]
checked again. domoticz crashes...

maybe it's the build 4.9700. this is what I get with the app on debug.

mark

Op ma 4 feb. 2019 16:15 schreef HNO Mobile <notifications@github.com:

**Comment by galadril** [comment]
Could be, can you Send me an account on your system to test? Domoticz@
hnogames.nl

Op ma 4 feb. 2019 19:09 schreef mvroosmalen1970 <notifications@github.com:

**Comment by mvroosmalen1970** [comment]
The solution works, though connection is slow. Takes 15sec before the app is loaded with switch info. This problem I've seen in the past with update check on (settings advanced). Would nice if we can find a solution for the slow loading of the data. Thanks for the help so far.

**Comment by galadril** [comment]
I've uploaded a new beta 2 seconds ago, to see if we can speed up the app startup.
And if wifi/remote is working correctly again

**Comment by mvroosmalen1970** [comment]
Hi,

I've tested the new beta, still the delay (roughly 15-30sec) is noted with
both internal (wifi on 192.168....) as well as external (wifi or 4g)
network connections.

Mark

 do 21 feb. 2019 20:21 schreef HNO Mobile <notifications@github.com>:

**Comment by mvroosmalen1970** [comment]
today the delay is not there anymore. is this due to the recent update? if
not it's likely resolved after the reboot of my router....

Op za 23 feb. 2019 15:04 schreef Mark van Roosmalen <
mh.van.roosmalen@gmail.com>:

**Comment by galadril** [comment]
Nothing changed..

Op za 9 mrt. 2019 18:21 schreef mvroosmalen1970 <notifications@github.com>:
