### ISSUE TITLE
Blinds Open/Closed

### ISSUE THREAD

**Issue by Hydci** [domoticz/domoticz-android#525]
Hello,
For the support of shutters (blinds) in domoticz on Android is it possible to have Open / Close instead of On / Off which would be more logical ? 

Shorty my english is bad i'm french.

![screenshot_20190303_123004](https://user-images.githubusercontent.com/36527391/53694719-23c40500-3db3-11e9-8bc9-749ebb070a02.jpg)

**Comment by sailmich** [comment]
I agree and already asked for that on domoticz 2.0 app. Didn't get an answer yet. I hope I will get an answer here.

**Comment by galadril** [comment]
ill see what i can do

**Comment by Hydci** [comment]
Hello, In place of open closed we could have a symbol like this ⬆️⬇️ or🔺🔻

**Comment by galadril** [comment]
I hope that this looks better for you guys
![Screenshot_2019-07-30-09-18-28-954_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/62108817-41868f00-b2ab-11e9-80e0-9f29c00c6f60.png)
![Screenshot_2019-07-30-09-18-36-297_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/62108818-41868f00-b2ab-11e9-976b-c0003e558cbb.png)

**Comment by Hydci** [comment]
Hello, it's perfect ! I hope to see the maj arrive quickly to try

**Comment by sailmich** [comment]
Fantastic, thx.

HNO Mobile <notifications@github.com> schrieb am Di., 30. Juli 2019, 09:20:

**Comment by galadril** [comment]
Ill upload a new beta probably tomorrow!

Op di 30 jul. 2019 om 09:24 schreef Hydci <notifications@github.com>:

**Comment by galadril** [comment]
v0.2.127 (6112) is pushed to the app store.. should be able to update to the new version within an hour.. Ill close this issue, you can reopen if it doesn;'t work as expected
