### ISSUE TITLE
Dashboard not working - Value nan at DewPoint of type javal.lang.String cannot be converted to long

### ISSUE THREAD

**Issue by csegedicsaba** [domoticz/domoticz-android#528]
Dashboard not working, getting excpetion: Value nan at DewPoint of type javal.lang.String cannot be converted to long

![Screenshot_20190422-143524](https://user-images.githubusercontent.com/33460858/56500737-5b764000-650c-11e9-8188-bb8f460c29c0.png)

1. Starting Dashnboard

**Smartphone:**
 - Device: Huawei P9 lite
 - OS: Android 7.0
 - Domoticz version 0.2.107 (5856)

**Comment by galadril** [comment]
Should be fixed in next version
