### ISSUE TITLE
The top menu disappears

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#533]
**Describe the bug**
When I scrooll the screen to find more switches the top menu disappears, correct. But if I press the back key of android, the bottom three of the right (see photos), the application takes me to the previous screen but I have no access to the menu and I can not retrieve anything but out of the application .

It always happens with the Plans start screen, because it has few fields and it is not necessary to scroll.
In dashboard, etc, it also happens but when you scroll because there are many fields you can recover the top menu.

**To Reproduce**
1. Go to switch, log, etc
2. Scroll the screen until the top menu disappears.
3. press back to return to the previous screen

**Screenshots** !!!

![Screenshot_20190504-180138_Domoticz_LI](https://user-images.githubusercontent.com/42274403/57222776-1bcb5000-7004-11e9-9a05-0124c236a3fe.jpg)

![Screenshot_20190504-180150_Domoticz](https://user-images.githubusercontent.com/42274403/57222780-1ec64080-7004-11e9-8695-6c46a5fd6d4e.jpg)
The last window is the one that appears after pressing back. As I can not scroll because there are few fields I do not recover the top menu.

**Smartphone (please complete the following information):**
 - Device: Galaxy s9
 - OS: Android 9
 - Version 0.2110(5871)

a greeting

**Comment by galadril** [comment]
Fixed in next version
