### ISSUE TITLE
Set temperature SetPoint

### ISSUE THREAD

**Issue by maresob** [domoticz/domoticz-android#534]
Hi,
I have found a bug.
I have: 
Host: RaspberryPi 2B+ with Domoticz  4.9700
App: Domoticz for Android 0.2.110(5871)
Thermostat: LanCube EQ-3 MAX!
 When I have use SetPoint(thermostat) from www I'm able to change temperature, using this same SetPoint from phone, I'm not able to change temperature.
On logs i don't have any errors...

**Comment by galadril** [comment]
Can you create a view account on your system, and send me your system info (connection url/user/pass)

Then ill debug this against your system.

(ps im going on holiday after tomorrow>..)

**Comment by galadril** [comment]
Can you supply me a test account on your system?"
