### ISSUE TITLE
Problems of visualization of the devices in the application

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#537]
**To Reproduce**
1. Go to screen switches
3. Scrolls up and down several times

Entering the screen of switches and with enough to scroll up and down you can see that they overlap and do not remain clean.

It only happens if the option of "show additional data on the board" is deactivated.

![Screenshot_20190716-191555_Domoticz_LI](https://user-images.githubusercontent.com/42274403/61321419-c2ee1400-a80b-11e9-83a8-7a847c06f6ce.jpg)

**Smartphone (please complete the following information):**
 - Galaxy s9
 - OS: Android 9
 - app versión 0.2.121 (6048)

**Comment by galadril** [comment]
hmm weird issue.. ill test this

**Comment by turin400** [comment]
Hi.
I have also seen that the temperature icons do not change color depending on their value when they are displayed on the "Plans" tab.
However in the "Temperature" tab if they change color depending on their value.

 "Plans" tab
![InkedScreenshot_20191019-014915_Domoticz_LI](https://user-images.githubusercontent.com/42274403/67135141-e9f72000-f216-11e9-855f-119085ca677d.jpg)

"Temperature" tab
![InkedScreenshot_20191019-014924_Domoticz_LI](https://user-images.githubusercontent.com/42274403/67135146-ecf21080-f216-11e9-82ad-f96ca7757ad7.jpg)

**Comment by turin400** [comment]
sorry arriva photos are changed, the first is the "temperature tab" and the second is the "plans tab"

Version: 0.2.143 (6317)

**Comment by turin400** [comment]
Any progress on the topic of visualization of the devices?
Thank you
