### ISSUE TITLE
Auto refresh does not work in item Plans

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#538]
When I enter a pentaña defined in Plans the auto refresh does not work.

Here it seems that it works but there are only the links to the sub window

![Screenshot_20190716-191512_Domoticz](https://user-images.githubusercontent.com/42274403/61583929-75d9ad00-ab3f-11e9-87f3-f0865cf3a5b9.jpg)

Within this subwindows of Plants for example does not work.
But none really works inside the item plans.

![Screenshot_20190716-191530_Domoticz](https://user-images.githubusercontent.com/42274403/61583986-5727e600-ab40-11e9-90ae-df98e83985b5.jpg)

 - Device: Galaxy s9

 - OS: Android 9
 - Version 0.2.125 (6091)

**Comment by galadril** [comment]
Thanks for the report, should be fixed in the next release
