### ISSUE TITLE
v0.2.127 (6112) crashed on pixel 3a

### ISSUE THREAD

**Issue by sailmich** [domoticz/domoticz-android#540]
Pixel 3a newest android
Domoticz newest beta
Domoticz app v0.2.127 (6112)

Http connect with 192.xxx.xxx.xx not permitted There are no settings where I could set a password and I don't have a password in my Domoticz server.

**Comment by galadril** [comment]
hmmm i see.. ill look into this quickly!

**Comment by galadril** [comment]
hmm looks like its because ive updated the gradle/os versions
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by galadril** [comment]
Ive pushed a new version to the app store:
0.2.131, please let met know via this issue if this solves it!

**Comment by sailmich** [comment]
You got it, thx for your work!

**Comment by galadril** [comment]
Pfiew, sorry for the fuckup

Op do 1 aug. 2019 21:25 schreef sailmich <notifications@github.com>:
