### ISSUE TITLE
Problem with low autorefresh values

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#544]
I have been testing 2 and 1 second values ​​with these inconveniences:

- The circular animation of the temperature values ​​has not finished the route and is already updating again without having finished.
I suggest that the animation do the whole tour once and only do it again when the temperature value has really changed.
This situation worsens as the temperature value is higher since it takes longer for the animation to make its journey

![Screenshot_20190807-231810_Domoticz_LI](https://user-images.githubusercontent.com/42274403/62660194-b58cfb00-b96d-11e9-8c6a-871b1f757528.jpg)

- 
Another thing that happens is with respect to the drop-down menus of the selectors. When the app refreshes if the menu is displayed, it closes and you don't have time to choose the position of the selector. I have seen that they can also be closed with the back key, I suggest that you only close with this key.

![Screenshot_20190807-231754_Domoticz_LI](https://user-images.githubusercontent.com/42274403/62660458-5da2c400-b96e-11e9-91fc-06acf8931eca.jpg)

Greetings and thanks for the work.

**Smartphone (please complete the following information):**
 - Device: Galaxy s9
 - OS: Android 9.0
 - Domoticz system version 4.11062
 - Domoticz app version 0.2.132(6183)

**Comment by galadril** [comment]
Good point.. 

i see multiple possibilities
- Dont animate the temp-circles on auto-refresh
- Dont refresh the screen if a control is opened?? (the refresh of a ui-control makes it closed)
- And maybe don't allow auto refresh timers below 3 seconds..?

**Comment by turin400** [comment]
The not update when there is an open dropdown seems correct, you are waiting for the window and do not look at the rest of things.


The temperature animation is very visual and if it changed only the first time and when the value changes it would be fine because it tells us that something has changed on the page, as you say it would not be appreciated if the temperature changes and however it is changing.

If you can do what I suggest first and later limit the time to > = 3 s if it does not improve.
I think it is good to have a rate of less than 3 s, it gives agility to the application.

What you see

**Comment by turin400** [comment]
I have seen that the problem of animation has been corrected, good work. However, disappearance of the drop-down continues to occur when the values ​​are refreshed, I don't know if you're still with them. thanks for everything.

**Comment by galadril** [comment]
After some testing, i have to come to a conclusions.. that i have no idea on how to keep the combobox open on a refresh.....

so what are the options else... set a min value?:

**Comment by turin400** [comment]
Disable automatic update when the submenu is displayed and enable it again when closed, I think it is the best option. I don't know if it can be done.

Right now I have a value of 5s that I think was the default value and in the photo that I attached, it is difficult for me to select without closing the drop-down for the refreshment.
![Screenshot_20190904-151848_Domoticz](https://user-images.githubusercontent.com/42274403/64261427-cc068200-cf2c-11e9-9cee-1db529fab9a5.jpg)
