### ISSUE TITLE
No access to application after error like No route to host

### ISSUE THREAD

**Issue by tootai** [domoticz/domoticz-android#545]
I use Domoticz Lite 08/2019 version on a Android 7 Asus Tablet. It was working well during monthes. Now my ISP changed my IP address and I can't use Domoticz anymore: launching the application I get "Oops something went wrong, timeout or no connection. No route to host".
![Oops_no_route_to_host](https://user-images.githubusercontent.com/6564304/63109463-930c6a80-bf89-11e9-9a46-e5eb476e30d1.jpg)
No access to menu implies no parameters, I have no possibility to correct network parameters.
I tried to uninstall/re-install the application, no luck.

At least, when a problem occurs we should be able to access parameters to correct the problem-s

Daniel

**Comment by galadril** [comment]
Please try to clear the cache and data of the app.. (dont reinstall) and then reopen the app..
it will ask you to reconfigure

**Comment by galadril** [comment]
Have you tried cleaning app data/cache via android app settings? the new version also contains a fix for tablets... ill close this case.. please re-open if the issue still occures
