### ISSUE TITLE
Thermostat setpoint SET function wrong units

### ISSUE THREAD

**Issue by lbdroid** [domoticz/domoticz-android#546]
**Describe the bug**
I have temperatures set up to degrees FARENHEIT.
In the dashboard, I see Set point: 76.0, which is correct. When I press the SET button, it shows a label of 30.0 ^C and a circular shaped widget with a range of 10.0 to 30.0 degrees C.

**To Reproduce**
Set domoticz to display temperature in FARENHEIT.

**Expected behavior**
Since my Domoticz instance has temperature units set in FARENHEIT, this too should be in FARENHEIT, with a sensible range, like 40-120.

**Comment by galadril** [comment]
I've tried to test this.. I've set my settings in Domoticz from Celcius to Fahrenheit.. and this is how my temperature dialog looks like:

![Screenshot_2019-08-21-11-21-34-928_nl hnogames domoticz premium](https://user-images.githubusercontent.com/14561640/63420101-4ea82100-c406-11e9-9117-6d5217c04190.png)

**Comment by galadril** [comment]
So it does show the Fahrenheit symbol... but the min = 0 and the max is still 30.. you can change these min/max settings in the app settings:

![Screenshot_2019-08-21-11-22-17-704_nl hnogames domoticz](https://user-images.githubusercontent.com/14561640/63420162-6ed7e000-c406-11e9-998d-868c224c7a39.png)


![Screenshot_2019-08-21-11-22-25-842_nl hnogames domoticz](https://user-images.githubusercontent.com/14561640/63420167-71d2d080-c406-11e9-9574-adc736ef7866.png)

**Comment by galadril** [comment]
Please try to set these values, and let me know if it works for you. 

If not, please add screenshots!
