### ISSUE TITLE
Adding the app to F-Droid?

### ISSUE THREAD

**Issue by hkemal** [domoticz/domoticz-android#549]
Hi guys,

Domoticz is open source and the App also.
Why not get it uploaded to F-Droid repository?

BTW Are there building instructions anywhere to be found?

Regards
Kemal

**Comment by galadril** [comment]
- I could upload the free app to F-Droid indeed, ill think about it!
For now I choose the Play Store because of the extra feature that gives me as a dev

- No building instructions. It's just a normal Android projects so you can build it with Android Studio
Should be straight forward

**Comment by hkemal** [comment]
It would be great to see the app in the F-Droid!
Until then I will try to build it myself :)!

Regards
Kemal

**Comment by anonimno1** [comment]
Hi,

have you thought about it :)?
I use the app without Play Services and it works fine (for what I need) but it keeps on complaining that Play Services are not there.
If not uploading to F-Droid, maybe then just making a switch to disable the warning?

Regards
K
