### ISSUE TITLE
Graphs for weather in App look very "crude"

### ISSUE THREAD

**Issue by JVaassen** [domoticz/domoticz-android#552]
When looking at rainfall data in the App, it always occured to me that it seems there are only a few datapoints in the graph (daily graph for example).

The daily overview on the domoticz website shows way more detail.
I was analyzing this, and found it looks like an explicit/design behaviour in the app.
There is a factor 4 in Weather.java.
intent.putExtra("STEPS", 4);
So the daily data collected (30 points collected from domoticz server) is divided by 4, meaning 7 points remaining.

I would like to change that back to 1 or 2, but this must have been done for a reason.
I tried it in a debug environment, and it looked good to me.
 
Since I don't want to break the app:  can anyone tell me why this was done ? 
And whether that reason is still valid..

My request would be to change it back to 1. I can do it myself, but before doing it, would like some feedback.

Other option : offer the setting config-settings of the app.

Thanks

Jos

**Comment by galadril** [comment]
I've disabled the steps property in the latest beta
