### ISSUE TITLE
Netatmo problem setpoint you do not have permission

### ISSUE THREAD

**Issue by Hydci** [domoticz/domoticz-android#558]
**Describe the bug**
Problem setting thermostat with user account on the application I receive as a message "you do not have the rights" so I made a new user and it still does not work, with the same user on the web page domoticz the setting of the thermostat works
I tried to remove the app cache that did not work

If need other information ask me
With an admin account on the app it works

No work via app (domoticz lite version: 0.2.17 (6381)
![thermostatnowork](https://user-images.githubusercontent.com/36527391/68083845-12ddfe80-fe2e-11e9-8655-1a121a687473.jpg)

Work domoticz webpage
![Capture1](https://user-images.githubusercontent.com/36527391/68083842-12456800-fe2e-11e9-8f58-f932b914a343.PNG)
![Capture2](https://user-images.githubusercontent.com/36527391/68083843-12456800-fe2e-11e9-9a90-ab6214ad47a2.PNG)
![Capture3](https://user-images.githubusercontent.com/36527391/68083844-12ddfe80-fe2e-11e9-847a-b13b73b3cad4.PNG)

User
![user](https://user-images.githubusercontent.com/36527391/68083970-a6fc9580-fe2f-11e9-95d4-71a9072e6870.PNG)

 - Domoticz system version [stable 4.10717] no work
 - Domoticz app version [beta 4.11455] no work

**Comment by galadril** [comment]
So with an admin account it works.. but with an other user account it doesn't work..
are  you sure that you have enough rights on the device?

**Comment by galadril** [comment]
Found the issue.. should be fixed in the next release. Thanks for the great information provided
