### ISSUE TITLE
Geofence stopped working on Android 10

### ISSUE THREAD

**Issue by sammyke007** [domoticz/domoticz-android#559]
Hi

Since updating my Oneplus 6 to Android 10, geofencing stopped working. The only available location permission is "when app is opened". The option "always" is gone? 

![Screenshot_20191111-234250](https://user-images.githubusercontent.com/33524412/68627898-46302580-04df-11ea-9cb4-6b4f2c05694f.jpg)

**Comment by galadril** [comment]
My devices still didn't received Android 10 update, so its hard to test with just emulators.
Ill see if i can arrange a test device for this (but its gonna take more time to fix)

**Comment by sammyke007** [comment]
> My devices still didn't received Android 10 update, so its hard to test with just emulators.
> Ill see if i can arrange a test device for this (but its gonna take more time to fix)

Tnx for the quick follow-up!
If you need me to try anything, just let me know.

**Comment by galadril** [comment]
Please check on the app settings that the app has no battery restrictions, and auto-start enabled.

Also check if you have disabled the smart power feature> 
https://oppo.custhelp.com/app/answers/detail/a_id/3597/~/power-saver-features
(as it restricts background services)

**Comment by sammyke007** [comment]
> Please check on the app settings that the app has no battery restrictions, and auto-start enabled.
> 
> Also check if you have disabled the smart power feature>
> https://oppo.custhelp.com/app/answers/detail/a_id/3597/~/power-saver-features
> (as it restricts background services)

All of these are 100% disabled. No optimization, no smart battery, ...
I have a TADO for controlling my house temperature. The TADO app also uses geofencng to decide the house temperature, and that app is working fine.

**Comment by galadril** [comment]
Thanks for the info

**Comment by galadril** [comment]
I think it works a bit better now, and i've added a new permissions needed for android 10... ill push a new  build to the beta channel.

To subscribe to the beta channel>
https://play.google.com/apps/testing/nl.hnogames.domoticz.premium

**Comment by galadril** [comment]
Should be in v > 0.2.180 (6474)

**Comment by sammyke007** [comment]
Ok, I'll test ASAP and will keep you updated!

**Comment by sammyke007** [comment]
![Screenshot_20191114-204717](https://user-images.githubusercontent.com/33524412/68891849-f8efc600-0721-11ea-8d32-ba0a919c74c9.jpg)
Permissions seem to be ok again, will check actual geofence tomorrow! Tnx!!

**Comment by sammyke007** [comment]
Fixed, tnx!
