### ISSUE TITLE
GCM ID failure

### ISSUE THREAD

**Issue by MSe-5-14** [domoticz/domoticz-android#563]
**Describe the bug**
I'm trying to push the my Google cloud messaging Id to domoticz from my Android 10 device. The app crashes directly. I assume this is caused by GCM being no longer supported. This has been replaced by FCM. I read on the domoticz GitHub that they have replaced the API. Did you?

**To Reproduce**
1. Go to 'settings'
2. Scroll down to 'notification settings'
3. Click on 'Google Cloud Messaging ID'
4. App crashes

**Expected behavior**
I would expect my GCM ID to be added to my domoticz. This doesn't happen.

**Screenshots** !!!

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 10.0
 - Domoticz system version 4.11563
 - Domoticz app version 0.2.180 (6474)

**Additional context**
https://github.com/domoticz/domoticz/issues/3292
https://developers.google.com/cloud-messaging/faq

**Comment by galadril** [comment]
Really weird, as we already use FCM btw (its only called gcm in the domoticz web uit).

**Comment by MSe-5-14** [comment]
I tried it on 2 other Android 10 devices and I have the same issue.

**Comment by galadril** [comment]
Fyi i found the issue.. im working on a fix for it

![image](https://user-images.githubusercontent.com/14561640/72016842-ce734280-3264-11ea-8925-bb0264f39135.png)

Its not about the FCM implementation, but it's how i get a unique id for you device.. thats not allowed in Android 10 anymore (woops)..

**Comment by galadril** [comment]
I have a fix, its getting late here.
Ill push a new mobile app version tomorrow.

**Comment by MSe-5-14** [comment]
Great to hear. thanks for your time and good night :)

**Comment by galadril** [comment]
ive pushed a update to the play store, let me know when its working correctly (and close this issue)

**Comment by MSe-5-14** [comment]
Thanks, this resolved the issue.
