### ISSUE TITLE
android sensor as virtual domoticz devices

### ISSUE THREAD

**Issue by petermolnar** [domoticz/domoticz-android#566]
I have a bunch of old android devices lying around, most of them with a lot of useful sensors: lux meters, sound meters, atmospheric pressure, etc. I've set two of them up as desk clocks and set up Automate processes in the background that sends the sensor information into Domoticz with min. 1 minute delays. 

I believe this would be an extremely useful feature in the domoticz app; even better if it would set the virtual devices up automatically.

Common sensors include:
- light meter 
- microphone as sound meter 
- battery temperature (accessible as a broadcast event)
- proximity 
- accelerometer (could be used as tamper sensor)
they can all have battery level included as parameter.

Less common sensors:
- atmospheric pressure (Galaxy S4, Galaxy Nexus, etc)
- ambient temperature 
- humidity sensor
- magnetic field sensor
... and a lot more.

**Comment by galadril** [comment]
Maybe we need some kind of other app for this. This app is more like an usage / app..
Not like a hardware sensor.

It is a good idea to build a seperate app to make the Android device a sensor hardware in domoticz


But not for this project
