### ISSUE TITLE
same problems with Multi server

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#567]
Hi, I am beginning to use the multiserver function and I am having some problems.

First, I can't find a way to change the name of the DEFAULT server, only when I create a new one, I can change the name of the DEFAULT, but the app is creating a copy with the new name and when I try to delete the DEFAULT it doesn't let me and in the end I have three servers.

Second, I am not able to define different startup screens for several servers, the change affects all servers, I don't know if I am doing it wrong.

Regards and thanks for everything.

version 0.2.187(6509)

Android 9.0, galaxy s9.

**Comment by galadril** [comment]
hmm the idea is that you can have multiple servers, but one is always the default (starting server).

And the settings that you change are not server settings, but app wide settings..

**Comment by turin400** [comment]
I agree that there always has to be a selected server. What I want to comment is that you cannot change the name of the DEFAULT server to another to identify them better.

![Screenshot_20200128-182220_Domoticz_LI](https://user-images.githubusercontent.com/42274403/73292014-93c84e80-4201-11ea-96f9-a4d16385abb1.jpg)
And when you have two servers and enter the DEFAULT server configuration to change its name.

![Screenshot_20200128-182248_Domoticz_LI](https://user-images.githubusercontent.com/42274403/73292157-d2f69f80-4201-11ea-8b72-1674eb6219f6.jpg)

You change the name and a third server is created with the same configuration as DEFAULT.

![Screenshot_20200128-182357_Domoticz](https://user-images.githubusercontent.com/42274403/73292261-06d1c500-4202-11ea-89a7-2d3c42633f87.jpg)

At this point I understand that the name of the DEFAULT server should have been changed to the new one, "pueblo", but not create a third. With the only condition of always keeping at least one server on the list.

**Comment by galadril** [comment]
Should be fixed in the next release.
There is no need for a DEFAULT server anymore.. you can specify the name you like

**Comment by turin400** [comment]
I have downloaded version 0.2.211 (7339) and have reset all settings from the application to start from the beginning. Renaming the server works. But I am not able to record different Local wifi SSID's for each server. They are mixed or not recorded.

I also can't change the notification settings from Notifications + Settings. Before I could change the tone, etc.

Greetings and thank you.

**Comment by turin400** [comment]
The problem I mentioned before the notifications already works, I think it was the permissions.

But the issue of the different local wifi networks for each server I have continued to do tests and nothing. the names of the wifi networks are mixed or not recorded.

Greetings.

**Comment by galadril** [comment]
Should be fixed with the new beta

**Comment by galadril** [comment]
I did another fix for the ssid settings.. im pushing a new prod release today

**Comment by turin400** [comment]
I am having problems with the multi server and cannot verify the SSID issue.
It is the one with version 0.2.212 (7347).

- To see the problem I reset the settings and start again. Then I add a server with its remote and then local settings, I activate the multiserver and two servers appear to me, the first with a blank name and the second with the settings previously placed.
I am trying to modify the nameless server settings but cannot save them.

If I delete the nameless server and then add a new one, the application closes.

**Comment by turin400** [comment]
![Screenshot_20200506-091534_Domoticz](https://user-images.githubusercontent.com/42274403/81148768-299c1400-8f7d-11ea-8a69-0e008ddce3cd.jpg)

**Comment by galadril** [comment]
I;ve already pushed a 0.2.213 version

**Comment by turin400** [comment]
ok, I'll wait to download it and I'll tell you.
Thanks again.
