### ISSUE TITLE
Widget options are gone. Old ones stopped working. 

### ISSUE THREAD

**Issue by sammyke007** [domoticz/domoticz-android#575]
Android 10, Oneplus 6, latest beta: widgets stopped working and can't add new ones. The option is gone...

**Comment by galadril** [comment]
Yeah the widgets are giving issues for as long as i know.. and nobody could assist when i asked.

So at this point the widgets are the main topic for bad reviews in the Play Store and im fed up with them.

So maybe they'll come back when their working properly...

**Comment by sammyke007** [comment]
Ok... I understand... They were working fine here however. Status was not always correct, but I used it a lot. You mentioned Experimental clearly anyway...

**Comment by galadril** [comment]
True, but i can make screenshots of the 1-star ratings about widgets.
So i think its better to give good working features that bad ones.

So for the mobile devs on this repo 🗡 .
The widget code is still in, its only disabled.. so please create a PR.

**Comment by galadril** [comment]
What do you think of the new update? 

Notification history inbox / android 10 day night themes / updated android wear app / redesigned preferences screen.

not that major/big topics.. but a lot of work anyhow to keep it uptodate with Android 10 ;)

**Comment by sammyke007** [comment]
Maybe add a secret toggle somewhere 😆

**Comment by sammyke007** [comment]
> What do you think of the new update?
> 
> Notification history inbox / android 10 day night themes / updated android wear app / redesigned preferences screen.
> 
> not that major/big topics.. but a lot of work anyhow to keep it uptodate with Android 10 ;)

I like it a lot. Especially the dark mode and the new preferences sorting. I don't use the notifications for now. I use Pushsafer because of the ability to add pictures (doorbell) in notifications. I'll give it a try however!

**Comment by galadril** [comment]
Ill keep this topic as a reminder to once fix the widgets (with help hopefully), thanks for the comments

**Comment by NiklasOlofsson** [comment]
Show stopper for me. Running Domoticz and Home Assistant side by side but I use the widgets so extensively in my daily life so I really need them to make good use of the system. The other app changes looks very good. I'm sorry I can't help.

**Comment by galadril** [comment]
ok ill throw another ball at fixing those damned widgets :(

**Comment by sammyke007** [comment]
> ok ill throw another ball at fixing those damned widgets

Let me know if there's any testing to be done!

**Comment by galadril** [comment]
ill push a new beta today (because i also changed quite some ui elements on Wear OS app)

**Comment by galadril** [comment]
ok widgets are coming back, ill close this issue
