### ISSUE TITLE
Dimmer slider jumps back to previous percentage

### ISSUE THREAD

**Issue by AJ-99** [domoticz/domoticz-android#578]
Hi, I have a problem with the dimmer slider.

If I slide it from a random position to 0 or to 100 it doesn't dim, instead it goes back to the previous set percentage.

 - Device: Motorola Moto G6 Plus
 - OS: Android 9
 - Domoticz app version 0.2.201 (7061)
 - Domoticz system version 4.10717

Regards and thanks.

**Comment by galadril** [comment]
and it does work via the website right??

**Comment by AJ-99** [comment]
Yes it does

**Comment by galadril** [comment]
Can you provide me test account on your system? domoticz@hnogames.nl

Op za 21 mrt. 2020 18:26 schreef AJ-99 <notifications@github.com>:

**Comment by AJ-99** [comment]
How do I provide you a test account?

**Comment by BoulayMichel** [comment]
Je suis nouveau sur github et étudiant en électronique IoT ...avec le CoronaVirus j'ai un peu de temps... DONC...Comment puis-je vous fournir un compte test?

**Comment by AJ-99** [comment]
I created this screen recording https://we.tl/t-SzCqVZB3PN. Maybe it helps explaining the problem.

**Comment by galadril** [comment]
Mm i think its because you've set the 'auto refresh' on with a too low timeout.. so its refreshing just after you've set the new value. Just set the auto refresh a little bit longer to prevent these kind of situations

**Comment by AJ-99** [comment]
I changed the auto refresh time but it did not make any difference. I also noticed that if I move the slider to 99% it changes to 100%. That is a bit annoying because if I want to set the light to 100% I have to set it to precisely 99%. So maybe the value 100% does not work and that is why it changes back to a previous set percentage?

**Comment by galadril** [comment]
Really weird, as i experience no issues at all on my system or on our demo system....

Sounds like a timing issue.. maybe slow connection to domoticz.. or interference of the auto refresh feature.. no clue..
