### ISSUE TITLE
Edit server add new one instead

### ISSUE THREAD

**Issue by andreapx** [domoticz/domoticz-android#579]
**Describe the bug**
When I edit a server setting, instead of save the changes to the one I'm editing, a new one's created.

**Expected behavior**
The changes gets saved to the current server

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 10
 - Domoticz system version 2020.1 (build 11838)
 - Domoticz app version  0.2.202 (7072)

**Comment by turin400** [comment]
This issue and others I already discussed in issue # 567 but have not yet been resolved.

**Comment by galadril** [comment]
Good point, let me know if you like to send a  PR 🗡️ 
#567

**Comment by turin400** [comment]
Sorry I am not a programmer, but I have bought the application and I hope it works as well as possible.

**Comment by galadril** [comment]
Should be better in the next release
