### ISSUE TITLE
Installing the app without Google Play

### ISSUE THREAD

**Issue by rreuvekamp** [domoticz/domoticz-android#580]
It would be great to be able to use this application without having to use Google Play. 
It seems there are no build instructions and no compiled binaries. And it seems, it's not on F-Droid.

**Is your feature request related to a problem? Please describe.**

There are no build instructions and no compiled binaries.

**Describe the solution you'd like**

A way to install and use the open source version of the application without having to use Google Play.

**Describe alternatives you've considered**

 - F-Droid
 - Binaries on the 'releases' page of GitHub.

**Additional context**

**Comment by galadril** [comment]
I don't have any plans for F-Droid at the moment.. 
Ill take a note of your request and see what ill do with it.

For now ill close this issue as I dont see it as a bug or feature request for the current app as it is now
