### ISSUE TITLE
App keeps loading forever after 1 May beta

### ISSUE THREAD

**Issue by sammyke007** [domoticz/domoticz-android#582]
**Describe the bug**
Domoticz app keeps infinite loading on opening. Previously made widgets got corrupt.

**To Reproduce**
1. Open the app

**Expected behavior**
Show Domoticz devices

**Screenshots** !!!

**Smartphone (please complete the following information):**
 - Device: Oneplus 6
 - OS: Android 10
 - Domoticz system version 2020.1
 - Domoticz app version 0.2.208 (7290), todays beta.

**Additional context**
Before updating this morning, everthing was still fine. Clear cache, reboot, reinstall, nothing helps.
It shows "Logged in" in the menu tough.
Resetting all settings via the app doesn't help neither. 
Clean app installation without importing settings keeps trying to connect to my Domoticz when verifying.

**Comment by galadril** [comment]
What domoticz version are you using?

Op vr 1 mei 2020 18:25 schreef sammyke007 <notifications@github.com>:

**Comment by sammyke007** [comment]
Domoticz system version 2020.1
Domoticz app version 0.2.208 (7290), todays beta.

**Comment by galadril** [comment]
Can you set debug on via advance settings?

Op vr 1 mei 2020 18:38 schreef sammyke007 <notifications@github.com>:

**Comment by sammyke007** [comment]
The advance settings part only contains Export settings/import settings/Permissions/Reset all settings?

**Comment by galadril** [comment]
Could you try to update domoticz base system?

Op vr 1 mei 2020 18:43 schreef sammyke007 <notifications@github.com>:

**Comment by sammyke007** [comment]
I would love to, but jumbotroll stopped with the Synology packages (Jadahl). I can't upgrade to 2020.2 :-(

**Comment by galadril** [comment]
If You clear cache and test /config against demo system?

Op vr 1 mei 2020 18:53 schreef sammyke007 <notifications@github.com>:

**Comment by galadril** [comment]
Just to see if that doesn't give issues

Op vr 1 mei 2020 18:58 schreef Mark Heinis <heinis.mark@gmail.com>:

**Comment by sammyke007** [comment]
Works right away!

**Comment by galadril** [comment]
Demo is an old domoticz system, not updated this year.
Im running  2020.2 also without issues..

Could you make an user on your system and email me the details to test against your system?
Then you can remove the user when its done to remove my access..?

**Comment by sammyke007** [comment]
Offcourse, don't toggle every switch as I'm not at home, but my wife is :-D.

**Comment by galadril** [comment]
i wont toggle any.. just see if i can see / list the devices

**Comment by sammyke007** [comment]
Mail sent ;-)

**Comment by galadril** [comment]
woops typo in the email.. domoticz@hnogames.nl

(domotics but domoticz silly me)

**Comment by galadril** [comment]
Thanks i think i found it... please change the authorization method to login form..
Basic auth is going to be removed really soon, i actually though it was already gone 🗡️ 

![image](https://user-images.githubusercontent.com/14561640/80828618-e12fcf80-8be5-11ea-800c-9f9488e79d75.png)

PS, ill test the app against basic auth as well on my system.. thanks for the info

**Comment by sammyke007** [comment]
Ok, but I'll have to change a lot of domotica devices because with basic-auth I can easily log in. Is there a possibility to mail me the previous beta apk? Changing login method right now, will break a lot of things and I'm not at home...

**Comment by galadril** [comment]
I dont think so, i also use https://username:password@a;slkfjsekjlfes.com/json.html for some stuff
And that still works

I think that if you choose login page, both work

**Comment by sammyke007** [comment]
Ok, I changed it and indeed it's working fine again, tnx for the quick feedback. Curious what will be broken when I get home :-D

**Comment by galadril** [comment]
Hope not too much...

**Comment by galadril** [comment]
So now it just doesn't load forever./.. and tomorrow ill make a better error description.

I've talked with gizmo about this.. and Basic Auth is getting removed in the next update..
So i dont spend to much time on  it now

**Comment by sammyke007** [comment]
galadril, tnx for your quick support!

**Comment by galadril** [comment]
Ps for others are have issues.. make sure you also update Domoticz!!!

**Comment by Artechtronic** [comment]
Application in version 0.2.214 (7369), connects to domoticz, but nothing can be enabled / disabled

**Comment by galadril** [comment]
Im building another fix as we speak for your enable/disable issue..

its going to be 0.2.216

**Comment by Artechtronic** [comment]
Estimated, what time to finish?

**Comment by galadril** [comment]
Its pushed to google.. takes like 2 hours in average to bubble up in the play stores.. 
can be quicker if your lucky

**Comment by Artechtronic** [comment]
> Its pushed to google.. takes like 2 hours in average to bubble up in the play stores..
can be quicker if your `lucky`
ok. i keep my fingers crossed

**Comment by edje1205** [comment]
Did  update last evening can reach app again but switches will not work. Today will add  logincheck map in domoticz

**Comment by galadril** [comment]
@edje1205 could you create a user for me with rights to toggle one switch on your system and send the details to domoticz@hnogames.nl? ill try to debug the issue then

**Comment by edje1205** [comment]
Hoi

Try:

Http://92.109.141.17:2080/#/LightSwitches

1 switch Led2 achter

No pass (its MQTT investigation)

V2020.2

Otherwise

Http://92.109.141.17:4080/#/LightSwitches

V4.10717

or

Http://92.109.141.17:3580/#/LightSwitches

V 3.8153

Allversions reacheable by app but switches don't work.
Made logincheck map.


Grtz
Ed



Sent from my Samsung Galaxy smartphone including weird words done by auto translations. Apologized if so !

-------- Original message --------

**Comment by galadril** [comment]
Please set an username / password in the settings of domoticz:

![image](https://user-images.githubusercontent.com/14561640/81384553-225a3f00-9112-11ea-8cc5-b4346e6ba22b.png)

!!

**Comment by edje1205** [comment]
Ok thanks did the trick.

2 versions working again oldest version 'wrong password'.
Will investigate (it was stable but had a lot of problems in passed years.
It has a 'login page' setting but I have the idea the password is not kept or so.
Will see tot update te version.

And yes it was on the forum but was mistaken

Sorry

Ed



Sent from my Samsung Galaxy smartphone including weird words done by auto translations. Apologized if so !

-------- Original message --------

**Comment by Catfriend1** [comment]
Hi, can there please be a compatible handling of old servers that cannot update to domoticz 2020.* easily at that time? The app could - from my point of view - query the server version first and then login via form or basic auth.

**Comment by galadril** [comment]
True.. but i've been Asked to remove basic auth
