### ISSUE TITLE
Cannot login with last beta from 1 mei 2020

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz-android#583]
I did everything described in https://github.com/domoticz/domoticz-android/issues/582
I am on 4.10717 and cannot upgrade (Zwave problems)
I changed login to "Login pagina"
Manual login with url works, both external as internal.
Demo account login works.
Is there a the solution?

**Comment by galadril** [comment]
You should update domoticz.....

Op za 2 mei 2020 21:42 schreef SargonofAssyria <notifications@github.com>:

**Comment by SargonofAssyria** [comment]
But I cannot update Domoticz.
Impossible, because Zwave does not works. Both 2020.1 ans 2020.2 do NOT works.
A lot of people have Zwave problems, which still are not solved.

**Comment by SargonofAssyria** [comment]
Could I receive the previous .apk to get things working again?

**Comment by galadril** [comment]
I dont have all apk's from the past. At this moment, you could unsubscribe to beta.. but thats only saving you some time..

Im building the app against Domoticz, and they are removing Basic Auth and implement oAuth  soon. I cant just make sure that the app works also with old stables back in time... sorry


Please raise this issue on the Domoticz github please

**Comment by SargonofAssyria** [comment]
I unsubscribed from beta and got the production app. It is working.
I prevent Android from updating without my approval.
So I am good for the time being.
