### ISSUE TITLE
Please offer last premium APK compatible with domoticz 2019/05

### ISSUE THREAD

**Issue by Catfriend1** [domoticz/domoticz-android#592]
Hi,

Could you please offer the 'previous' version of the APK for download. I've paid for it and need to downgrade.

Thanks.

**Comment by galadril** [comment]
HI i dont have previous released apks, i just push them to google and done store them.

You could just build the project yourself if you really need to?


I dont distrubute apk's beyond the play store

**Comment by Catfriend1** [comment]
Thanks for your answer. In the play store, there's a section "artifact library" where the APK can still be found for download. I respect your decision. It would just be a nice service in addition if your build script could push the release APK to GitHub as well. (Doing so myself with syncthing-android that users can do early upgrade or downgrade in case the latest release play version causes some trouble).

Not sure if I may ask this or if it perhaps should go to a private support chat: I am able to build android apps, can the premium version be built on my own - shouldn't there be licensing protections in place blocking me to use it self-built?

Thanks for your time.

**Comment by galadril** [comment]
Thanks for the donation @Catfriend1
