### ISSUE TITLE
Blinds Open/Closed IOS

### ISSUE THREAD

**Issue by Hydci** [domoticz/domoticz-android#593]
Hello, at one time I asked for the android application icons close open for the shutters I now have an iphone and I see that the ios application does not have this change is it possible to have the same thing like in this number?

https://github.com/domoticz/domoticz-android/issues/525

**Comment by galadril** [comment]
You;'ve already created a Xamarin issue.. ill close this one
https://github.com/domoticz/domoticz-xamarin/issues/35

**Comment by Hydci** [comment]
sorry i didn't know where to post my request

**Comment by galadril** [comment]
no problemo. That other issue was the correct github place, so i closed this one
