### ISSUE TITLE
Switch load crashes the app

### ISSUE THREAD

**Issue by kazzelito** [domoticz/domoticz-android#603]
Application keeps crashing immediately after start (tries to load switches). Long-press on icon and choosing something else (like Temperature) loads the app, trying to change to switches -> immediate crash.

Samsung S9
App version: 0.2.233(7910)
Android 9
Domoticz version: 2020.2(build 12173)

Same problem reported by other users here: https://www.domoticz.com/forum/viewtopic.php?f=6&t=33681&p=256980#p254489

Has been working fine until today, reinstall/wipe the application does not help, this seems to be related to the switch load entirely.

br
kazze

**Comment by galadril** [comment]
Can you give me a view user on your system? so i can debug against your system? that would solve the issue the quickest.. 
Maybe Domoticz did a braking change api/device ..

**Comment by kazzelito** [comment]
> 
> 
> Can you give me a view user on your system? so i can debug against your system? that would solve the issue the quickest..
> Maybe Domoticz did a braking change api/device ..
> 
> You could send to do [domoticz@hnogames.nl](mailto:domoticz@hnogames.nl)

Check your email!

**Comment by galadril** [comment]
Actually found a weird value in your sliders > 
![image](https://user-images.githubusercontent.com/14561640/94414424-a02fed00-017c-11eb-8682-9c3da84612f2.png)

I would expect the value 100 to be the max 👍

**Comment by galadril** [comment]
I'll update the app in the app store tonight

**Comment by kazzelito** [comment]
> 
> 
> Actually found a weird value in your sliders >
> ![image](https://user-images.githubusercontent.com/14561640/94414424-a02fed00-017c-11eb-8682-9c3da84612f2.png)
> 
> I would expect the value 100 to be the max 👍

Well, those Hue lamps might be able to deliver more than 100% lights ;-)

**Comment by kazzelito** [comment]
Btw...lowering that switch below below 101 (i.e. setting it to something lower) fixes the issue (for now). But yeah, would be good if we you could accept weird values (even though that might actually imply something is wrong in Domoticz)
