### ISSUE TITLE
Stuck in loop

### ISSUE THREAD

**Issue by Cosaque** [domoticz/domoticz-android#604]
**Describe the bug**
When i setup my app, it find correctly my all devices but i got an error and app ask me to reconfigure in loop.. 

![Screenshot_20201103_173113_nl hnogames domoticz premium](https://user-images.githubusercontent.com/1151017/98013566-d2c3aa00-1dfa-11eb-9993-2416e72e2691.jpg)
![Screenshot_20201103_173152_nl hnogames domoticz premium](https://user-images.githubusercontent.com/1151017/98013616-df480280-1dfa-11eb-9939-3059274dbb31.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei mate 10 pro
 - OS: Android 10.0 
 - Domoticz system version
Version: 2020.2 (build 12554)
Build Hash: 36715b865-modified
Compile Date: 2020-11-03 16:02:27
dzVents Version: 3.0.16
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
 - Domoticz app version 0.2.253 (8141)

**Comment by galadril** [comment]
do you have specific remote and local settings, or only local?
If only local.. can you enter these settings as remote?

its actually:

default host/ip

advanced settings for
extra local+ wifi settings


maybe a bit weird..

**Comment by kl0007** [comment]
Unfortunately adding settings as local or remote server doesn't change anything. "Incorrect settings detected, please reconfigure this app" evertytime.
(Android 9)

**Comment by Cosaque** [comment]
Tryed both local / remote always same result..

**Comment by Gert-Boers** [comment]
I have the same issue as the OP after updating the Android app. 17 devices are found, but on the next page incorrect settings detected.

**Comment by boschr** [comment]
Same for me. Did an app update and after I had only an empty screen (no dashboard, switches, ...). So I deleted the app cache and storage (starting from scratch) and also get stuck in this loop.

I'm using a OnePlus 6 with Android 10.

**Comment by darkrain-nl** [comment]
I have this same issue all of a sudden, is there anything we (I) can do to help analyze this?

**Comment by galadril** [comment]
ill try to fix this and upload a new version today

**Comment by galadril** [comment]
That peace of code, was for when we changed the app from single to multi server settings.. to migrate the settings from old to new.
Weird that its giving issues now, ill remove that peace of logic (cleanup had to be done anyway)

**Comment by galadril** [comment]
New build is coming with version: 553 (0.2.256 (8148))
Please let me know asap if this fixes the issue...

**Comment by Cosaque** [comment]
Waiting deployment on play store

**Comment by galadril** [comment]
Google is having delayed due to COVID

![image](https://user-images.githubusercontent.com/14561640/98099151-824a5c00-1e8f-11eb-8193-7894e145641a.png)

**Comment by galadril** [comment]
It should be available
![image](https://user-images.githubusercontent.com/14561640/98101688-dd318280-1e92-11eb-9d98-b80ce124ec90.png)

**Comment by Cosaque** [comment]
Downloaded & tested, problem solved ☑️

**Comment by galadril** [comment]
Thanks... Sorry for the inconvenience caused 👎

**Comment by boschr** [comment]
Great job! And thanks for the fast development!

**Comment by Gert-Boers** [comment]
Yes, I can confirm it works again. Thank you for quick acting. Much appreciated.

**Comment by Cosaque** [comment]
Yes great job & nice timing ty☺️
