### ISSUE TITLE
Swap Server Button missing

### ISSUE THREAD

**Issue by geferon** [domoticz/domoticz-android#605]
**Describe the bug**
With the newest update, the "Change server" button that was on top right in the main menu has been replaced by the search device icon, no longer allowing the user to swap between servers.

**Screenshots**
The button was previously found here, on the main menu
![image](https://user-images.githubusercontent.com/7958349/98125174-73c26b80-1eb4-11eb-83d6-991b09383469.png)

This screenshot is taken on a device that has multiple servers configured on the settings, as seen her:

![image](https://user-images.githubusercontent.com/7958349/98125257-8c328600-1eb4-11eb-8956-30fb18ccba4a.png)
It is now impossible to change the current active server with the button missing.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a, Huawei Mate 10
 - OS: Android 11, Android 10
 - Domoticz system version: Multiple servers, both at 2020.2
 - Domoticz app version: 0.2.257 (8153)

**Comment by galadril** [comment]
I see that only 1 server is 'enabled'

Please also enable the other server

![image](https://user-images.githubusercontent.com/14561640/98127705-49be7880-1eb7-11eb-8ecc-5a0cb8c20182.png)

**Comment by geferon** [comment]
Ah, that's one thing I didn't know, my bad
