### ISSUE TITLE
Sorting dashboard keeps getting reset

### ISSUE THREAD

**Issue by sammyke007** [domoticz/domoticz-android#606]
**Describe the bug**
Everytime I change the order in the Domoticz app of the dashboard and open the app a again later on, the order gets reset to what it was before. 

**To Reproduce**
Open Domoticz app, change order of devices on dashboard by drag&drop. 
Open app again 30 minutes later or so
New sorted order gets lost

**Expected behavior**
Save changed order by drag&drop.
(Locking drag&drop after changing the order of devices doesn't help, already tried) 

**Smartphone (please complete the following information):**
 - Device: Oneplus 8
 - OS: Android 11
 - Domoticz system version 2020.2
 - Domoticz app version 0.2.257 (8153), latest right now

**Comment by galadril** [comment]
Thats weird, i actual have all my screens custom sorted....

**Comment by sammyke007** [comment]
This morning I had reset the app from within the settings (clearing all settings). I reconfigured from scratch and sorted my devices to my liking. After 1 hour, everything was still the same. I tought, well that got fixed finally, it was probably a bad setting somewhere.

Later today I installed the new update from today and BOOM, all my devices order got messed up again.

I tried clearing all settings again, reconfigure, ... but my order always gets messed up again.
I start the app in dark theme, list mode, geofencing enabled and start sorting, that's all...

**Comment by sammyke007** [comment]
![Screenshot_20201105-175933](https://user-images.githubusercontent.com/33524412/98288062-90d76700-1fa6-11eb-8905-9bb01e1abea9.jpg)
![Screenshot_20201105-191055](https://user-images.githubusercontent.com/33524412/98288063-92089400-1fa6-11eb-88f0-7b6d80f779c7.jpg)
![Screenshot_20201105-193029](https://user-images.githubusercontent.com/33524412/98288065-92a12a80-1fa6-11eb-86bc-b2de8de936f0.jpg)
![Screenshot_20201105-193049](https://user-images.githubusercontent.com/33524412/98288066-9339c100-1fa6-11eb-8f40-00f11316dcd8.jpg)

**Comment by galadril** [comment]
it looks like updating the app also put back some kind of old version of the sharepreference.... that would also explain why all widgets are f*cked after an update (those info is also stored in sharedpreferences)

**Comment by sammyke007** [comment]
Correct, I have to remove my widgets and readd them every time

**Comment by galadril** [comment]
For the sorting, if you export your settings, update the app, and import your settings back.. it would probably be correct
https://developer.android.com/guide/topics/data/autobackup

Ill try to disable the Android backup of the sharedpreferences

**Comment by galadril** [comment]
Ill try to set backup to false on the beta version of the play store ok ? i though you had beta on the premium verion right?

**Comment by sammyke007** [comment]
Yes, correct!

**Comment by galadril** [comment]
woops.. ive changed to 

        android:allowBackup="true"

which should be 

        android:allowBackup="false"

ofcourse....

**Comment by sammyke007** [comment]
Yah, saw that and already tought it was a strange logic 👍 ;-)

**Comment by galadril** [comment]
558 (0.2.260 (8181))

**Comment by sammyke007** [comment]
Everything sorted, exported settings to make sure it wouldn't mess up, 5 second freeze, dashboard reloads with messed up order... v260 
Before:
![Screenshot_20201106-192921](https://user-images.githubusercontent.com/33524412/98401987-d78c9600-2066-11eb-8633-a5589cece5e9.jpg)
10 seconds later:
![Screenshot_20201106-192947](https://user-images.githubusercontent.com/33524412/98401993-d8252c80-2066-11eb-8f15-e2cc9d2903fc.jpg)

**Comment by sammyke007** [comment]
If you would like to see for yourself or test yourself, I can make a temp user account for you and mail it to domoticz@hn******.nl?

**Comment by galadril** [comment]
Sorting is done locally on your phone, not on your server.. So it's not
really needed.. Thanks

Op za 7 nov. 2020 06:23 schreef sammyke007 <notifications@github.com>:

**Comment by sammyke007** [comment]
I know, but maybe you can try and see it yourself on your phone. I don't think I'm doing anything wrong. Don't have to make a big deal of it, but I can't get sorting to work correctly here...

**Comment by galadril** [comment]
I found some bugs in the sorting logic.
The beta has sorting better implemented!

It now only saves on destroy (page close) or refresh data.. so makes it way quicker

**Comment by galadril** [comment]
New beta is coming, let me know if it works better for you

**Comment by sammyke007** [comment]
Sorting order seems te stay OK for now. Will report back tomorrow! Tnx for looking in to it.

**Comment by sammyke007** [comment]
![Screenshot_20201109-154021](https://user-images.githubusercontent.com/33524412/98580414-36991780-22c0-11eb-907a-f21705abaeb9.jpg)
![Screenshot_20201109-191637](https://user-images.githubusercontent.com/33524412/98580439-3e58bc00-22c0-11eb-99fd-e0e192ebdefe.jpg)

Sorry... Was ok for 2 hours or so, but upon opening just right now, sorting is messed up again...

**Comment by sammyke007** [comment]
Always in the same messed up order. Don't understand... It's not the order of the server neither.

**Comment by galadril** [comment]
its really weird.. im actually sorting/dragging all the time and i have no issues at all with the latest version..

**Comment by galadril** [comment]
Can you maybe check the other screens then dashboard?.. 
Maybe you have some kind of double device id. (i store the sorting based on device id)

**Comment by sammyke007** [comment]
Alright, sorted switches (schakelaars) and will report later. 

After sorting I tried closing the app normally, force closing, changing settings, ... and my preferred sorting order kept intact. After opening the app after an hour or 2 it got messed up. Really strange behavior.

I still have a user account set up for you if you would like to try to connect to my server yourself.

FYI, I'm running 2020.2 stable not the latest beta of 2020.2

**Comment by sammyke007** [comment]
![Screenshot_20201109-192804](https://user-images.githubusercontent.com/33524412/98582417-3bab9600-22c3-11eb-9c2f-34578573afa3.jpg)
![Screenshot_20201109-193719](https://user-images.githubusercontent.com/33524412/98582420-3c442c80-22c3-11eb-9502-ebab309cb21e.jpg)
![Screenshot_20201109-193807](https://user-images.githubusercontent.com/33524412/98582423-3cdcc300-22c3-11eb-96eb-0992697eda1f.jpg)
![Screenshot_20201109-193819](https://user-images.githubusercontent.com/33524412/98582428-3cdcc300-22c3-11eb-9795-a5bf7aedbe1c.jpg)

**Comment by galadril** [comment]
new beta is coming again with a small fix on sorting (probably not your main issue).
Can you also check from the previous beta if widgets still get corrupted?

**Comment by galadril** [comment]
btw the new beta version also contains some big changes to get ready for targetting Android 11
https://github.com/domoticz/domoticz-android/pull/611

(rewrite the file handling, sharing camera snapshots, and import/export settings)

**Comment by galadril** [comment]
As far as i can see, the only sorting issue that remains, is when you sort.. and force close after that, it doesnt save.. because i dont get the force close events in the app.. so doing that isn't a best practise as well ;)

Thinks its already way better then it was !

**Comment by sammyke007** [comment]
I'll check it. I am already running on Android 11, is that why exporting settings crashes?

**Comment by galadril** [comment]
could be..
561 (0.2.263 (8250)) is already on beta btw

**Comment by galadril** [comment]
did you try it yesterday?

**Comment by sammyke007** [comment]
Yes. Widgets needed to be readded, but not so big problem. BUT... my sorting seems te stay ok for almost a day! Let's see if it stays this way.

**Comment by galadril** [comment]
and the import/export feature of settings also works now without crashing
right


Op wo 11 nov. 2020 om 09:24 schreef sammyke007 <notifications@github.com>:

**Comment by sammyke007** [comment]
I was afraid to test it, but I got a dialog asking where to save settings.txt and... it saved correctly!
Most important, order is still ok! I guess you found it!

**Comment by galadril** [comment]
That would be cool..

Op wo 11 nov. 2020 om 11:07 schreef sammyke007 <notifications@github.com>:

**Comment by galadril** [comment]
I need an Android 11 device... my device didn't received the update yet...
I would love to implement this new Android 11 feature
https://github.com/domoticz/domoticz-android/issues/599

But this feature isn't available in an Emulator......

**Comment by sammyke007** [comment]
Looks nice... What device do you have. I'm a huge Oneplus fan.

**Comment by galadril** [comment]
I have a Poco F2 Pro currently, and a Mi A2 / Mi 8 to test/use

Op wo 11 nov. 2020 om 11:37 schreef sammyke007 <notifications@github.com>:

**Comment by sammyke007** [comment]
Since latest beta, sorting keeps OK/saved and exporting settings works fine without crashing. Don't know what the last thing was that you changed, but I guess that did it (for me). Tnx!

**Comment by galadril** [comment]
cool.
Ill make a new prod release then ;)

Op do 12 nov. 2020 om 12:59 schreef sammyke007 <notifications@github.com>:

**Comment by sammyke007** [comment]
Fine! You can always contact me for testing on Android 11 (or other things).

**Comment by galadril** [comment]
Cool tx

Op do 12 nov. 2020 om 13:12 schreef sammyke007 <notifications@github.com>:

**Comment by galadril** [comment]
Hi Sammy,

Im working on the External Controls feature of Android 11.
Would you like to try something out on your device?

can you send me an email?

**Comment by sammyke007** [comment]
Offcourse! Where to?

**Comment by galadril** [comment]
domoticz@hnogames.nl
