### ISSUE TITLE
Cannot show available Wi-Fi networks 

### ISSUE THREAD

**Issue by ricmail85** [domoticz/domoticz-android#609]
I have a problem with domoticz for android. The problem came out when I moved to a new device (xiaomi redmi 8) with Android 10.

When I try to set the server settings, the app doesn't show the list of available Wi-Fi networks. So I cannot select my home Wi-Fi and configure the server. 

On previous Android everything was working correctly. 

Thanks in advance for your support

**Comment by galadril** [comment]
Please check the app permissions. It asked for Location permissions to scan the WIFI SSID's

**Comment by ricmail85** [comment]
Thanks for your reply.

I've given all these permissions to the app but when I tap on local SSIDs nothing is showed... So the app cannot scan the available Wi-Fi. 

I've also done a reset of the app but still not working.

**Comment by galadril** [comment]
You could also manually enter your ssids via the manual button

**Comment by ricmail85** [comment]
Yes I've tried to manually input the SSID but it doesn't work at all... At the moment the only way to access Domoticz from my Wi-Fi is by using a browser.

**Comment by galadril** [comment]
I've reworked the method on how we show SSIDS in the list in the next release.
We still need the location permissions btw..
