### ISSUE TITLE
Android Auto integration

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-android#623]
Lets continue the discussion here, instead of on the PR > 
https://github.com/domoticz/domoticz-android/pull/614

@flobz i just read this article:
https://www.autoevolution.com/news/google-officially-announces-android-auto-closed-testing-apps-153248.html

Does this mean that we can now test this without rooted devices?
Or can we now just upload them to closed beta testing, but not use them yet..?

**Comment by galadril** [comment]
Actually, i think that Domoticz is not allowed as Android Auto app..

**Parking and Charging** 
The app must provide meaningful functionality in its category relevant to driving
If a parking app is displaying a list of locations next to a map (e.g the Place List Map template), then the locations in the list can only be parking spots. Similarly, for a charging app, the locations must be charging stations.

**Comment by flobz** [comment]
Yes, they will probably refuse the app because the category mismatch. It can be interesting to ask them though.

**Comment by galadril** [comment]
ive put the code on different branch for now.. until we know more in the future (ill put this issue on hold for now)

**Comment by peterselieman** [comment]
Well, i saw yesterday that samsungs smartthings app is on my AA screen. So i think that it is allowed.

**Comment by flobz** [comment]
That's a good news! Thanks

**Comment by galadril** [comment]
hmm.. maybe ill try again with the play store then!

**Comment by flobz** [comment]
I ask google play developer support some clarification one week ago but no answer yet...

**Comment by galadril** [comment]
I've reworked the implementation a bit to support more devices, and allow for setting your custom 6 items via settings.

**Comment by galadril** [comment]
We could also add a search bar, so that people can find any device from Domoticz >

![image](https://user-images.githubusercontent.com/14561640/107915711-4bdbad00-6f65-11eb-980d-c5d56e1176ff.png)

**Comment by flobz** [comment]
Thanks, I will try that!
For the search bar, I'm not sure but google can refuse the app for that. Because I think that virtual keyboard aren't allowed during driving. So you need to check if the car is moving to enable the search bar.

**Comment by galadril** [comment]
as i read it, the keyboard is automatically disabled during driving.. the user only has access to filters (earlier search values)

**Comment by galadril** [comment]
Btw im still getting rejected for the Android Auto implementation:

![image](https://user-images.githubusercontent.com/14561640/108177097-1371d580-7103-11eb-82ac-7595eb09c3a1.png)

**Comment by flobz** [comment]
> as i read it, the keyboard is automatically disabled during driving.. the user only has access to filters (earlier search values)

I'didn't know that.

**Comment by flobz** [comment]
I retrieve the android Manifest from Samsung smart things and the category isn't specified : 
```
 <service android:enabled="true" android:exported="true" android:name="com.samsung.android.oneconnect.androidauto.services.StCarAppService" android:process=":Core">
             <intent-filter>
                  <action android:name="com.google.android.car.action.CAR_APP"/>
              </intent-filter>
  </service>
```

**Comment by galadril** [comment]
I just keep getting rejected in the play store:
" we are only accepting apps within the Media or short form Messaging categories for Android Auto. Media apps that use Text-To-Speech engine readout for content are not permitted at this time."

**Comment by flobz** [comment]
I had news from Google support 5 months later :
During review, we were unable to accept your app, Domoticz Home Automation Lite (nl.hnogames.domoticz), for Wear OS. 

For example, your application does not provide a light background as shown on the store listing in App Bundle 9007. Please refer to the attached screenshots for more detail.
Please update your app to fix this issue and make sure to deactivate non-compliant App Bundle 9007 and increment the version number before resubmitting your app for another review.  

You may want to refer to our Building Apps for Wearables and Testing your App documentation for additional guidance.

**Comment by flobz** [comment]
@galadril did you miss my last message ?

**Comment by galadril** [comment]
i missed your message indeed. thanks.
ill take a look

**Comment by flobz** [comment]
Maybe you can try to publish the app with android auto again?

**Comment by rezzalex** [comment]
Hello @galadril  ans @flobz .

Any news on Android auto authorization to publish ?

Thank you

**Comment by galadril** [comment]
I guess your on the beta channel of the play store.
Thats indeed where im working on, its not yet released via the normal play store channels

**Comment by rezzalex** [comment]
Off course

Le mer. 22 juin 2022 à 20:52, HNO Mobile ***@***.***> a
écrit :

**Comment by rezzalex** [comment]
Hello @galadril , is it possible to have a little android auto feature video showcase ? Thanks

**Comment by rezzalex** [comment]
Hello.
Are you able to progress on Android auto , integration ?

**Comment by galadril** [comment]
I needed to change the implementation to androidx car libs..
At least its working again:

![image](https://user-images.githubusercontent.com/14561640/199336343-80d93859-c8df-498e-82f5-f3c7ea580dcb.png)

![image](https://user-images.githubusercontent.com/14561640/199336361-81e4a1be-4c06-4c9c-b40c-02e7c6065797.png)

**Comment by galadril** [comment]
We're not getting this app in the play store.. 
![image](https://user-images.githubusercontent.com/14561640/199816822-07c7130e-af5e-4525-93cc-742045918936.png)

**Comment by galadril** [comment]
Closing the issue. Not possible

**Comment by rezzalex** [comment]
@galadril , i have read that Android auto will be now open to IOT / Home control app ...

**Comment by galadril** [comment]
They recommend the use of GridTemplate for IoT apps btw. 
This app currently uses the ListTemplate for adding the items on the screen.

![image](https://user-images.githubusercontent.com/14561640/217542280-8abfe31d-e264-4f74-820c-5c99ebbfcd99.png)

Should not be to hard to refactor.
https://developer.android.com/training/cars/apps/iot#implement-functionality

**Comment by galadril** [comment]
![image](https://user-images.githubusercontent.com/14561640/217659017-84bea0d6-ed35-4a65-bb6c-1fd6ba2b4977.png)

**Comment by galadril** [comment]
![image](https://user-images.githubusercontent.com/14561640/217659396-9f514c8e-41d9-4594-8841-754eb88191c8.png)

**Comment by rezzalex** [comment]
Can't wait to test !

**Comment by galadril** [comment]
The change is allowed in open beta channel>
https://play.google.com/store/apps/details?id=nl.hnogames.domoticz

**Comment by rezzalex** [comment]
Thank you @galadril.

To be honest, knowing that I previously paid for the previous premium version, I think I will wait for the wearable version to be ready before paying the new annual fee.

**Comment by galadril** [comment]
no problemo. the premium app in the play store is still up-to-date

**Comment by galadril** [comment]
Did somebody try it? 
I turned my outside lights off this morning from my car ;) w00tw00t

**Comment by rezzalex** [comment]
> Did somebody try it? 
> I turned my outside lights off this morning from my car ;) w00tw00t

As soon as the wearable app is working, I will pay and try android auto.
No blackmail here, just to keep informed.

**Comment by galadril** [comment]
No blackmail, i get it ;).. Its in progress! (see other topic)
Its all about time management (i moved to a new  house as well last couple of weeks :D )

**Comment by WhatIsThatFor** [comment]
Hi galadril, thanks for re-opening this feature!
I tested it on my car, but I can't get a 100% success when I try to trigger a Scene...
It's a bit like the app needs to be awaken first, then after several attempts it finally works...
or should I hold the button a bit longer?
Maybe I should try with a simple switch first and see how it goes?
(car has a 10inch display and I use a Samsung S21FE)

**Comment by rezzalex** [comment]
On my side, the scene I use the most (opening and closing garage door and portal at the same time) also seems to not work all the time.

It always display "mixted status" once clicked with android auto, and sometimes it works and the 2 are opening, and sometimes none of them is opening. So why a "mixted" status ?

**Comment by WhatIsThatFor** [comment]
hi rezzalex, seems we experience the same behavior here..

**Comment by rezzalex** [comment]
Courage @galadril , we are behind you !!

**Comment by galadril** [comment]
Im appealing their decision to block it:

_Thanks for contacting Google Play. Your appeal has been submitted successfully and will be reviewed by a specialist. The ticket number for your appeal is referenced in the subject of this message_

**Comment by rezzalex** [comment]
Did Google specified a reason for Blocking ?
As the android auto is pretty much working, are they blocking only for WearOS ?

**Comment by galadril** [comment]
various reasons.. but every review is fresh (they dont look at history). and it repeats the next reasons:

1) missing connection details (aldo i clearly state that they can use the demo setup)
2) missing premium subscription rights (i've provided promotion codes)
3) Android auto not according to guidelines (not really clear on what to do to fix this)
4) Wear OS is not according to guidelines (not really clear on what to do to fix this)
5) Android auto has no items on the screen (probably nothing on the dashboard at that point)
6) Wear OS has no items on the screen (probably nothing on the dashboard at that point)

and this is going back and fort between those reasons now for months

**Comment by galadril** [comment]
I'm truly happy that finally Google approved the new version with Wear OS and Android Auto fixed/implemented.. YES

**Comment by flobz** [comment]
Great! Thanks for your tenacity!

**Comment by FirelightLokeren** [comment]
Hi,
I noticed that domoticz was availible in android auto.
I see some switches but not all. 
Is there a way to select witch switches are visible in android auto?

Kind regards
Koen
