### ISSUE TITLE
Some Visual changes

### ISSUE THREAD

**Issue by eserero** [domoticz/domoticz-android#625]
As I'm using Domoticz daily, and trying to get rid of all the other apps, I found a few things that are working well in Xiaomi/Alexa/Homekit that can be visually helpful.

1. It is difficult to identify from the icons if a device is off or on. the off state is a bit darker, but its not obvious. maybe make "on" state glow a bit? or make the whole button gray if its off (they way homekit does that)

2. I will be great to have an option for a smaller - fixed size button size that can be everywhere, So that we can fit more icons/sensors in a single page, with the current implementation in the dashboard the buttons are very big.
both homekit and Xiaomi have some example. I took the xiaomi as a suggestion below:
 - The name should have only one line (smaller font)
 - There should be a toggle on/off that is very clear on the same line as the icon (to save space)
 - values should also be smaller fonts to save space
 - clicking on the panel itself open the graph/options etc.
 - example below based on the xiaomi app, Apple homekit has 3 items in a row but the logic , but I think  two are enough.

![image](https://user-images.githubusercontent.com/55898840/103101805-f993a500-4621-11eb-8395-3ebd72f2de67.png)

3. Ability to choose different backgrounds per plan would be super :-)

I just opened another feature request for room plan improvements as well, just wanted to put my thoughts on paper.
Much appreciate your application and domoticz!

**Comment by galadril** [comment]
Thanks for all your thoughts.. ill keep these issues open just to have an eye out for new ideas for myself!

**Comment by galadril** [comment]
I think that a lot of these topics are now in the latest Domoticz apps. closing this issue for now (lets open a different one if needed)
