### ISSUE TITLE
Transparant widgets

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#63]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&start=500#p69277

by rathmannm » Sun Jan 10, 2016 7:58 pm

any chance we could get widgets with transparent backgrounds

**Comment by remb0** [comment]
I agree,    it would be nicer on most of the wallpapers.

**Comment by galadril** [comment]
Added the option

![screenshot_20170110-113841](https://cloud.githubusercontent.com/assets/14561640/21803404/3e2536ae-d72a-11e6-98e9-830e17ffc989.png)

![screenshot_20170110-113857](https://cloud.githubusercontent.com/assets/14561640/21803405/3e436390-d72a-11e6-8b36-73e97edcd8f1.png)
