### ISSUE TITLE
Geofence not working anymore

### ISSUE THREAD

**Issue by etmrugl** [domoticz/domoticz-android#630]
**Describe the bug**
In the app Geofence is working, including notifications. But the associated switch in the Domoticz server is not set.

**To Reproduce**
1. I leave the house and with enough distance I get a notification in the app that I left the home.
2. The switch in the Domoticz server is not changed.

I tried to re-install the app, no luck.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: [e.g. Android 11.0
 - Domoticz system version 2020.2
 - Domoticz app version 0.2.295

**Comment by galadril** [comment]
Are you sure that your phone has battery optimalization set to unlimited(off) for Domoticz?

**Comment by etmrugl** [comment]
> 
> 
> Are you sure that your phone has battery optimalization set to unlimited(off) for Domoticz?

Yes.

**Comment by galadril** [comment]
So Geofences are working, but setting the switch on/off isn't.
What kind of switch are you toggling? Just a normal on/off device?

I've been testing this, and i have no issues with this part... thats why..

**Comment by etmrugl** [comment]
It is a normal on/off switch.

If I use a on/off button in the Domoticz web interface, the status of that button is not correctly updated in the Domoticz app.

And there is more. I use the deConz plugin. I defined groups and scenes in the Phoscon app. For instance: Groep Zolder and Scene Zolder Diner. If the group is off and I activate the scene, the group should also switch on. This works correctly in the web interface in Domoticz. If I activate the scene in the Domoticz app, it works OK, but the status of the group is not updated correctly.

To make things a bit complicated: the Groep Zolder is a regular on/off button in Domoticz, the Scene Zolder Diner is a pusbutton ni Domoticz.
![image](https://user-images.githubusercontent.com/60889628/110697128-32d4bd80-81ec-11eb-80a7-5d572e661d01.png)

**Comment by galadril** [comment]
"And there is more. I use the deConz plugin. I defined groups and scenes in the Phoscon app. For instance: Groep Zolder and Scene Zolder Diner. If the group is off and I activate the scene, the group should also switch on. This works correctly in the web interface in Domoticz. If I activate the scene in the Domoticz app, it works OK, but the status of the group is not updated correctly."

How did you automated this? device settings? events? scripts?

**Comment by etmrugl** [comment]
On these groups and scenes there is no automation (yet)
There is also no automation (yet) in the geofence switch.

**Comment by galadril** [comment]
can you make a screenshot of your geofence settings screen?

**Comment by etmrugl** [comment]
![image](https://user-images.githubusercontent.com/60889628/110699941-acba7600-81ef-11eb-8fbf-1d9521dbbd2b.png)

**Comment by rezzalex** [comment]
Just a tought :

Is using another geofence solution, like The one from google home app for
instance, could prevent the one from domoticz mobile app to work properly ?

**Comment by galadril** [comment]
It shouldn't interfere with eachother no

**Comment by galadril** [comment]
I've been working with Geofences for my own solution a lot, and cant really reproduce this
