### ISSUE TITLE
problem when changing user

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz-android#635]
I have created a new user in domoticz and when I enter the app I find it and can log in, the problem is that when I exit the app I no longer get the list of users and I cannot return to the previous one, I have to restore the app.

version: 0.2.306 (8498)

Domoticz
Version: 2021.1
Build Hash: 8547c5b7e
Compile Date: 2021-04-17 17:29:11

a greeting

**Comment by galadril** [comment]
Hmmm you dont see the list of users, because that user isn't ad admin..
only an admin can see the other usernames via an api..

**Comment by turin400** [comment]
So when I log in as a non-administrator user, there is a way to close the session without restoring the app and to be able to log in with another user. I don't know if I'm doing something wrong.

**Comment by galadril** [comment]
Yes via settings/connection settings.. you can change the username and
password there as well

Op zo 16 mei 2021 om 21:05 schreef turin400 ***@***.***>:

**Comment by turin400** [comment]
you're right. Thanks for everything.

**Comment by galadril** [comment]
Your welcome!
