### ISSUE TITLE
Geofence implementation using Pathsense as option instead of Googles Location Services.

### ISSUE THREAD

**Issue by CV8R** [domoticz/domoticz-android#636]
**Is your feature request related to a problem? Please describe.**
I would like my alarm system to be reliably, timely and accurately armed when I leave my homes location and disarmed when returning to the location utilizing the location of my phone.

**Describe the solution you'd like**
An option in the Domoticz app to select the Geofence location provider as the Pathsense system rather than Googles. https://pathsense.com/

**Describe alternatives you've considered**
Multiple other solutions, all using Googles location services and all suffer the same problem of late ingress and egress updates.

I was using the Egigeozone app successfully which implements the Pathsense system, using Egigeozone to send a URL to my Domoticz System. https://www.egigeozone.de/default_en.html

Unfortunately, the Egigeozone app is no longer maintained.

I have now implemented a kludge using the Pathsense demo application from the Android Play store.  This demo app allows 1 fence and triggers Egress and Ingress notifications with a max radius of 250m.  I have captured these notifications with Tasker with AutoNotifcation apps and use the Tasker app to send the URL to Domoticz.  My experience thus far is that the solution works well and accurately and promptly responds when traversing the Geofence boundary.

The kludge isn't a great solution and I would like to set the radius to 1000m.

My experience with Pathsense is that it is far superior to Googles.

**Additional context**
The Google system is so slow to update in recent Android versions that it has become unusable to disarm/arm alarms when entering and leaving a Geofence (home area). I have tried many Geofence solutions including this app and any that use Googles system all detect the Geofence egress and ingress at the same time but the location updates are severely delayed.  The problem with Googles solution is that the egress often happens minutes (up to 15) after entering the fence.

Pathsense supports Android and iOS.

**Comment by galadril** [comment]
Looks cool, but we dont have 1000 monthly users.. a bit more..
![image](https://user-images.githubusercontent.com/14561640/130607032-5c2221ac-03d6-4c70-9b10-9578771f6971.png)

**Comment by CV8R** [comment]
I am guessing their quotation was way out of the ballpark to warrant further investigation. I figured Pathsense would have come to the party with a reasonable price, since they would benefit from the exposure, given the demographic of the Domoticz userbase.
