### ISSUE TITLE
Bluetooth feature is not working

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz-android#653]
Hello,

I can't get the Bluetooth function to work

After activating the Bluetooth feature, clicking on the "+" button top-right doesn't do anything. I was expecting it to add the current or recorded Bluetooth devices

**Smartphone (please complete the following information):**
 - Device: XIAMOI MI9
 - OS: Android 11 RKQ1
 - Domoticz system version 2022.1 (build 14352)
 - Domoticz app version 0.2.328 (8937)

**Comment by rezzalex** [comment]
It seems to be fixed, right ?

**Comment by galadril** [comment]
This is fixed indeed
