### ISSUE TITLE
Biometric verification should not be "all the time"

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz-android#654]
**Describe the bug**
The biometric check is asking for my fingerpints even coming from a parameter menu back to the main screen

**To Reproduce**
- Authenticate by biometric when app launch
- go to some settings menu
- go back to the main screen
- The app is asking again for the Biometric authentication
- 
**Expected behavior**
don't ask for Biometric authentication if already been performed within the last X minutes (3?)

**Smartphone (please complete the following information):**
Device: XIAMOI MI9
OS: Android 11 RKQ1
Domoticz system version 2022.1 (build 14352)
Domoticz app version 0.2.328 (8937)

**Comment by rezzalex** [comment]
Hello.
Still here in the latest version

**Comment by galadril** [comment]
Better late then never, this should be fixed in the next release
