### ISSUE TITLE
Inverted open/close buttons for blinds workig via MQTT Auto Discovery

### ISSUE THREAD

**Issue by MichaluxPL** [domoticz/domoticz-android#667]
Z-Wave blinds working via MQTT Auto Discovery and configured as "Blinds Percentage" have inverted open/close buttons, that means tapping close button opens blinds (rolls up) and open -> closes (rolls down).
In the same time opening/closing blinds using percentage bar works as expected (0% closes, 100% opens)

**To Reproduce**
1. Configure MQTT Auto Discovery
2. Set switch type for a blind device to Blinds Percentage
3. Tap open/close in the mobile app.

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 10.0
 - Domoticz system version : 2022.1 (build 14380)
 - Domoticz app version: 0.2.332 (9023)

**Comment by galadril** [comment]
Cant you set the device type to Blinds Percentage Inverted? Looks like thats the issue instead of an mobile app issue maybe..

**Comment by MichaluxPL** [comment]
No, I can't - this would invert directions in Domoticz itself.
Android app should recognize switch type set and act accordingly.

**Comment by MichaluxPL** [comment]
So ... can You fix it ?

**Comment by galadril** [comment]
Domoticz system version : 2022.2 reworked the way blinds work.
New version of the mobile app is coming today or tomorrow.

Plz check if the bug is still applicable for you with the new versions

**Comment by MichaluxPL** [comment]
Looks like now it works OK :)
Thx !
