### ISSUE TITLE
widgets losing conection to devices

### ISSUE THREAD

**Issue by Rouzax** [domoticz/domoticz-android#668]
I bought the Premium app and have subscribed to the "new" app, do understand that the growth is out of Domoticz, so the number of new people is not growing anymore and as a result it would be impossible to maintain the App for free.

Do have issues with the new app that my widgets lose their connection to the switches they are assigned with, this happened very occasionally on the old premium app but happens each day on the new one.
![0qOnbGl](https://user-images.githubusercontent.com/4103090/179390386-6001d015-12ca-4d94-a9a5-837e905582e4.png)
Phone Samsung S21 FE 5G (SM-G990B)
App Domoticz 0.2.334

**Comment by galadril** [comment]
i actually need to fully rebuild the widgets due to Android 12 sdk changes:
https://developer.android.com/about/versions/12/features/widgets
