### ISSUE TITLE
Android UUID not valid anymore with newer androids?

### ISSUE THREAD

**Issue by Olifant1990** [domoticz/domoticz-android#669]
**Describe the bug**
I have switched to a new Android phone, the Nokia X20 with Android 12.
When is connected the Domoticz app with my Domoticz server, I saw a new user under Setup -> More options -> Mobile Devices.
That user has type "Android31".
But, the UUID seems odd and I cannot send a test push notification, it doesn't arrive.
It seems the token is not correct anymore on new Android versions?

**Screenshots** !!!
![afbeelding](https://user-images.githubusercontent.com/25199588/182837553-9f50981f-dbaa-4038-9fad-a1cb05a663a1.png)

**Smartphone (please complete the following information):**
 - Device: Nokia X20
 - OS: Android 12
 - Domoticz system version 2022.1 (build 14440)
 - Domoticz app version 0.2.334 (9038)

**Comment by galadril** [comment]
The UUID mechanism is indeed changed, its not really a phone id anymore but an unique id assigned for the Domoticz app.
But this should all still work.. sometimes i just get a new id and then register the phone again as a new phone (cant remove the old as i dont have that id anymore..)

Just filter on 'Last seen' and test the latest UUID for your phone.

![image](https://user-images.githubusercontent.com/14561640/183284271-af6ce1a0-097a-4ac3-b40f-b40b4e447e39.png)

Please try and close this issue if that works

**Comment by Olifant1990** [comment]
Indeed I got it to work, but only after going to notification settings in the app and press Google Cloud Messaging-ID (to send to Domoticz).
Nothing changed in the mobile user overview, but test button sends a test messages and it is being received at my phone.

Will see how much my UUID is changing, hope not much. I have a lot notifications which are depending on a specific phone.
So a new phone registration should not be a right solution when an UUID changes.

**Comment by galadril** [comment]
Closing the issue for now.
I've tested this locally with a new device.. and after Android OS update and my UUID was pushed correctly
