### ISSUE TITLE
Blinds and awings movement inverted in domoticz app after update shelly plugin from enesbcs 

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz-android#675]
**Describe the bug**
Dear friends,

After update the shelly plugin for domoticz "https://github.com/enesbcs/Shelly_MQTT" my blind and my awings are inverted in android app domoticz. 
In the Domoticz web gui interface, after edit device, has been added a box titled "reverse open/close state" if we had this box in the app we could easily correct the problem

**To Reproduce**
Opening and closing the blinds, the movement is inverted
**Expected behavior**
When i make click in "up blind" The blind should go up ,and vice versa.

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy note 9
 - OS: [Android 10.0]
 - Domoticz system version [ Version: 2022.2 (build 14823) ]
 - Domoticz app version :  home automation 0.2.320 (8513) --> old pay version app

**Additional context**
To be able to raise or lower my blinds I have to press the opposite direction

**Comment by galadril** [comment]
This should be the fixed version of the app when your running Domoticz 2022.2:
0.2.343 (9200)

**Comment by galadril** [comment]
This fix is btw published also for the 'old' premuim app in the store

**Comment by galadril** [comment]
The premium app is unpublished, so new people can't buy it anymore. But existing users should still be able to install/update it:
https://support.google.com/googleplay/android-developer/answer/9859350?hl=en

![image](https://user-images.githubusercontent.com/14561640/209146471-3c137182-5083-4a70-9140-83c435e30a79.png)

So this version should be available in the play store to update for you
![image](https://user-images.githubusercontent.com/14561640/209146594-e5db14fb-31a5-4559-b4df-7b7dd177f39b.png)

**Comment by kitopopo** [comment]
> This should be the fixed version of the app when your running Domoticz 2022.2:
> 0.2.343 (9200)
> 

Thanks for answer dear @galadril ,

The problem has been fixed in 0.2.343 (9200) app update.

Thanks, best regards .
