### ISSUE TITLE
On the Left Sidebar we have loss the shortcuts of user variables and events

### ISSUE THREAD

**Issue by kitopopo** [domoticz/domoticz-android#676]
Dear friends,

After update from Domoticz app premium version  from home automation 0.2.320 (8513) to home automation 0.2.343 (9200), we have loss in the left sidebar  two shortcuts of **user variables** and **events**.  "they are two shortcuts that I use daily several times and now they are in settings at the end of the list. If it's posible. Would you be so kind if you could put the shortcuts back in the sidebar in the next update, I would be very grateful. 

Thanks in advance, best regards

![SmartSelect_20221223-114018_Domoticz Premium](https://user-images.githubusercontent.com/51416982/209321932-573877c5-7821-4203-97ee-360e54ccd4bc.jpg)

![SmartSelect_20221223-114228_Domoticz Premium](https://user-images.githubusercontent.com/51416982/209322208-4e80d2f0-c1de-40f5-85e1-75b72eaba869.jpg)

**Comment by galadril** [comment]
No sorry.. its also in Domoticz base system part of the sub menu's and not the main menu.

**Comment by kitopopo** [comment]
> No sorry.. its also in Domoticz base system part of the sub menu's and not the main menu.
> 

Dear friend, thanks for you answer.
In my previous app version 0.2.320 (8513) the user variable and events are in the left sidebar. It has been changed in the lastest update
