### ISSUE TITLE
Android Wear OS no app?

### ISSUE THREAD

**Issue by Brutuss** [domoticz/domoticz-android#677]
Hi,

When searching on the playstore on a wear OS smartwatch. Example Samsung Watch 5 Pro. Domoticz is not showing in the list.

Installing the app on the phone and use a premium account also no app on the watch.

**Comment by rezzalex** [comment]
+1, I just bought a galaxy watch and was excited about the DZ wearable app, and can not find it either

**Comment by galadril** [comment]
Thats weird.. ill look into that. (im a bit bussy at the moment, so it could take till somewhere in januari/feb)

**Comment by Brutuss** [comment]
> Thats weird.. ill look into that. (im a bit bussy at the moment, so it could take till somewhere in januari/feb)

Thats to bad. Then we have to wait :( Then I could have wait with the premium payment.

**Comment by rezzalex** [comment]
Hello @galadril , happy new year ,!! All the best !
I hope you will soon have time to check on this missing wear OS app :-)

**Comment by galadril** [comment]
Ive been trying to get the previous version of the Wear OS app uploaded to Google..

But it seems that I need to rewrite to Wear OS app from GoogleApiClient sdk to GoogleAPI and a different MessageApi for syncing data between de app / wear app

![image](https://user-images.githubusercontent.com/14561640/212029332-e3b59259-8deb-414c-b341-32469c8bc492.png)

So this needs some more development (maybe even rebuild the app with the latest WearOS 3 changes..)

**Comment by rezzalex** [comment]
Hello @galadril ,
I have been able to download the "Wearable" app, but it stays stuck on the initial blue screen

**Comment by galadril** [comment]
yeah it needs some work..

**Comment by rezzalex** [comment]
Hello @galadril ,
Have you been able to work on it ?
Thanks you

**Comment by galadril** [comment]
Still working on it.. Aldo I did manage to get the Wear OS app to work again on my watch with a local dev build after these changes
https://github.com/domoticz/domoticz-android/commit/c0730e4d388502b325b5bf25195b75112711f2e9

So ill try to get it in the Play Store after some more testing

**Comment by rezzalex** [comment]
I bought the premium version and remove both he dz android app and wearOS app, reinstall the new DZ android app one, and the wearOS app is not showing,-up and can not be found within the watch Playstore... :-(

**Comment by galadril** [comment]
As explained earlier. im trying to get this approved in the play store. as android auto and wear os are new apks its triggering a manual review process at Google, and they are hitting some walls with the demo setup within the app.

**Comment by rezzalex** [comment]
I thought that because the androip app was released in the play store, the Wear OS and Android auto parts had been validated at the same time. It is obviously not the case here.

**Comment by rezzalex** [comment]
The android auto seems to work fine.
But no wearOS app available

**Comment by galadril** [comment]
Your on the Domoticz Premium app? Or the free with subscription model?

Weirdly enough, Google keeps on rejecting the update for the Domoticz free app, but it approved the update (with the Wear OS and Android Auto apk). So you should be able to get the Wear and Auto app with your paid app.

**Comment by rezzalex** [comment]
Once my new subscription paid, I removed the previous premium app (paid once long time ago).

**Comment by galadril** [comment]
Im truely happy that finnaly Google approved the new version with WearOS and Android Auto fixed/implemented.. YES

**Comment by Brutuss** [comment]
> Hello @galadril , I have been able to download the "Wearable" app, but it stays stuck on the initial blue screen

Thx for the update! After the update I still get this..

**Comment by galadril** [comment]
thts weird.. did you try to reinstall the app(s) from the play store? Also on your watch?
(ill do the same, was sure that it worked when developing !)

**Comment by galadril** [comment]
ive cleanly installed the latest version of the app on both devices (wear and phone needs to be updated) and it works here nu

**Comment by galadril** [comment]
awesome. tx

**Comment by rezzalex** [comment]
Thank you @galadril , it is working !!!
