### ISSUE TITLE
RFXCom Blinds control broken

### ISSUE THREAD

**Issue by Gozzima** [domoticz/domoticz-android#678]
I am sticked to domoticz 2020.1 jadahl version which is the most recent one working on my Synology DS215j with USB drivers to be able to use my RFXCom and ZWave USB keys.

My RfxCom blinds are not working anymore in Android App since the latest upgrade : 0.2.343 (9200).
They still work in the web browser either on PC or smartphone web browser (Chrome and EDGE tested).

I saw in the discussion about [issue 673](https://github.com/domoticz/domoticz-android/issues/673) that [@cyberictagop](https://github.com/cyberictagop) had the same problem as me with 2020.2 jadahl version.
It looks like this bug appeared with the fix [ae7e65b](https://github.com/domoticz/domoticz-android/commit/ae7e65b7fcd7c1317011abcb5c2d70ebd3d47a0a) for inverted blinds with domoticz 2022.2 version

Upgrade to domoticz 2022.2 is not an option for us as it has not been compiled with USB drivers on synology ARM architecture.

**Comment by galadril** [comment]
The latest version of the app works with the latest version of Domoticz.
