### ISSUE TITLE
Button color position and cutting text

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz-android#68]
Problem with color button now is in lates version 0.1.217
![d249cd64-b191-11e5-8001-f66cc8302a9e](https://cloud.githubusercontent.com/assets/4134018/12298997/16310732-ba15-11e5-81a2-e8648b1fcae4.jpg)

Screen is from older version but in latest is the same.

Problem with cutting text translation is also avaible in latest version
![f8627bb0-b207-11e5-853d-db4a3af0406d](https://cloud.githubusercontent.com/assets/4134018/12299065/5fe25d22-ba15-11e5-894a-d63b817cca19.jpg)

**Comment by galadril** [comment]
I've put the color button to the right because it works with the on/off + slider (which are all to the right).
Log, Timer and notification buttons are linked the the switch, so they are put on the left..

So I don't see the color button as a bug

**Comment by galadril** [comment]
"cutting text translation" =>
is it possible to make a 'shorter' translation in crowdin?

**Comment by pepeEL** [comment]
maybe finally change to "Ost. widoczny"

**Comment by pepeEL** [comment]
But my suggestion is to add strings other for switches and other for this problem. And for switches i add translation: " Ostatnio widoczny"  but for this problem i add other: "Ost. widoczny"
Can you add this? And i add translation corrected...

**Comment by RoadXY** [comment]
Could you explain your last comment please?
Maybe with screenshots?

**Comment by pepeEL** [comment]
![16310732-ba15-11e5-81a2-e8648b1fcae4](https://cloud.githubusercontent.com/assets/16692223/12322571/383470e4-bab5-11e5-9d7a-12dfb00f5a57.jpg)
Example.
For this strings create in Crowdin:
Last seen  -i translate > "Ostatnio widoczny"

But.
![5fe25d22-ba15-11e5-894a-d63b817cca19](https://cloud.githubusercontent.com/assets/16692223/12322602/5f3495b6-bab5-11e5-90f2-d051b4e48a95.jpg)
For this create in crowdin strings example:

Last seen2  -i translate > "Ost. widoczny"


I think about two other strings one for switches on full screen , one for window.
