### ISSUE TITLE
App Always scroll up in a "room plan" screen

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz-android#687]
Latest version.

When scrolling down in a room plan menu, when having the vertical scroller because of many devices, the screen always scroll up, preventing to really use the icons at the bottom ...

**Comment by galadril** [comment]
with auto refresh enabled or without?

**Comment by rezzalex** [comment]
with auto refresh activated, no issue when not activated

**Comment by rezzalex** [comment]
Hello, Any news on this ?

**Comment by galadril** [comment]
Fixed (a wile ago)
