### ISSUE TITLE
Crash in start up after uprading to latest version

### ISSUE THREAD

**Issue by rezzalex** [domoticz/domoticz-android#688]
Crash in start up after upgrading to latest version 0.2356(9312)
Just after fingerprint authentication ...

**Comment by jvanderzande** [comment]
Same here.... reverted to the previous version. 
It crashes for me when listing devices in a room. The initial screen is displayed fine.

**Comment by galadril** [comment]
ill take a look at the crash reports :(

**Comment by rezzalex** [comment]
> Same here.... reverted to the previous version. 
> It crashes for me when listing devices in a room. The initial screen is displayed fine. 

@jvanderzande how did you revert to the previous version?

**Comment by jvanderzande** [comment]
I have the App on 2 phones, so I could:

1. Use the Airdroid app to download it from the phone with the previous version to my laptop
2. Copied in with Airdroid to the phone I had updated.
3. Started the latest version and saved the config.
4. Uninstalled the last version
5. Ran the installer for the previous version from the SDCard
6. Imported the saved settings.

That's it. :)

**Comment by galadril** [comment]
i've seen 2 new different crash reports that i couldnt encounter for my own domoticz setup.
I should have fixed both, new version is pushlished (takes some hours for Google review)

668 (0.2.357 (9320))


Sorry for the inconvenience caused, please give me a headsup if you can try the new fix

**Comment by jvanderzande** [comment]
Will let you know when available &  installed.

**Comment by jvanderzande** [comment]
Just updated to 9320 and it doesn't crash anymore for me. Cheers.

**Comment by galadril** [comment]
Awesome, thanks for letting me know (and sorry for the issues caused)

**Comment by rezzalex** [comment]
The bug for "scrolling back to the top",
But there is still 1 remaining, when scrolling the rooms in the "homeboard"
menu, from left to right, it revert back on the left on his own... :-(
