### ISSUE TITLE
Last seen include date

### ISSUE THREAD

**Issue by jvandenbroek** [domoticz/domoticz-android#69]
Many of my sensors haven't updated their status for more than 24 hours, but last seen only displays the time. I'd suggest that if last seen date / time is more than 24 hours ago, the date is also shown.

**Comment by RoadXY** [comment]
What do you think of this (https://github.com/domoticz/domoticz-android/issues/113) request?
Has some overlap.

**Comment by galadril** [comment]
Thats also a possibility, I've reworked all adapters to work with a method from UsefulBits.

So if we change that method to give back relative dates, then thats it.

**Comment by RoadXY** [comment]
I can have a look tonight, if you like?
