### ISSUE TITLE
[premium subscription] - scenes switches do not work as widget 

### ISSUE THREAD

**Issue by Rouzax** [domoticz/domoticz-android#694]
**Describe the bug**
I can add all sorts of widgets but when adding a scene switch as widget it ends up empty with no text and no function 

**Expected behavior**
The widget to work as expected 

**Screenshots** !!!
![Screenshot_20230620_200651_One UI Home](https://github.com/domoticz/domoticz-android/assets/4103090/6ca1845b-5558-4949-98d5-aa61dea909e5)

**Smartphone (please complete the following information):**
 - Device: Samsung S21FE
 - OS: Android 13
 - Domoticz system Version: 2023.1 (build 15330)
 - Domoticz app Version 0.2.358 (9328)
 - 
**Additional context**

**Comment by Rouzax** [comment]
Still an issue in 0.2.361.

**Comment by galadril** [comment]
Removed widgets for now. needs to be rebuild
