### ISSUE TITLE
Scenes and switches are mixed up on widgets

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#7]
https://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=68109#p68102

by tozzke » Mon Jan 04, 2016 2:36 pm

When I try to add a switch with IDX 14 to my homescreen, it shows a scene with IDX 14 instead. When I push the button, it switches the switch instead of the scene, but the button doesn't update the on/off status, so I can only switch that light on or when the button only shows 'off', off. This happens with all my widgets when I try to add a switch. Adding a scene-widget seems to work fine.

**Comment by RoadXY** [comment]
Could we take some time to see if we can solve this? @galadril :-)

**Comment by galadril** [comment]
Please test, but i think we can close this one!
