### ISSUE TITLE
Switch selector As dimmer ?

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz-android#70]
Hi
I see that support for switch selector is implement but this no looks good. It is a slider dimmer. Slider as button. Before i turn on I dont see what is on first position , on second position etc.
Maybe can change to button....
![selector](https://cloud.githubusercontent.com/assets/4134018/12305136/860bef22-ba33-11e5-9428-7ad2235f6ff6.jpg)

![screenshot_2016-01-13-20-15-35](https://cloud.githubusercontent.com/assets/4134018/12305138/88b7284a-ba33-11e5-8b8f-5d2079682b64.png)

![screenshot_2016-01-13-20-17-06](https://cloud.githubusercontent.com/assets/4134018/12305139/8b20c438-ba33-11e5-93db-9f9c6de1b32f.png)

![screenshot_2016-01-13-20-17-51](https://cloud.githubusercontent.com/assets/4134018/12305141/8cf4a5fe-ba33-11e5-8d7e-e8c49d555f12.png)

**Comment by galadril** [comment]
Reworked selector to show a dialog with possible values to choose from:

![2](https://cloud.githubusercontent.com/assets/14561640/12348366/dc9d74e4-bb66-11e5-99d2-f5398e623cf8.png)
![1](https://cloud.githubusercontent.com/assets/14561640/12348367/dc9eb070-bb66-11e5-98a7-afba003c0d2e.png)
