### ISSUE TITLE
Status switches in Dashboard not changing

### ISSUE THREAD

**Issue by 14rut** [domoticz/domoticz-android#702]
**Describe the bug**
In Dashboard, no updates of the status of switches is displayed

**To Reproduce**
1. Go to 'Dashboard
2. Click on 'switch'  for example turn on/off TV
3. The switch is turning on, i can hear de click and see the tv lights on
4. de status stays as original displayed at open domitics app. (also wrong while TV was off)
5. See error

**Expected behavior**
Status change on activation switch

**Screenshots** !!!
![Screenshot_2023-09-24-13-16-31-43_5398ad44e992a39ae9edac26b3775fdf](https://github.com/domoticz/domoticz-android/assets/118394752/c7b70733-5fd0-481f-a06e-4ae69c97460a)
![Screenshot_2023-09-24-13-16-27-34_5398ad44e992a39ae9edac26b3775fdf](https://github.com/domoticz/domoticz-android/assets/118394752/706f65ce-0519-47c8-8c26-ce7ec4905920)

**Smartphone (please complete the following information):**
 - Device: Oneplus 8T kb2003
 - OS: [e.g. oxygenOS 13.1
 - Domoticz system version 
             Version: 2023.2
             Build Hash: 19efd039c
             Compile Date: 2023-07-21 17:23:44
             dzVents Version: 3.1.8
             Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]

 - Domoticz app version [e.g. 0.2.361(9349)]

**Comment by galadril** [comment]
Also on the latest versions? If you refresh 5 seconds later, is the switch then turned? 
(could be timing/low response on Domoticz)
