### ISSUE TITLE
 [WebServer] Deprecated RType (devices) for API request.

### ISSUE THREAD

**Issue by ajarzyn** [domoticz/domoticz-android#703]
While using `Domoticz Premium` app deprecation log is printed:
`[WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command!`

**To Reproduce**
Steps to reproduce the behaviour:
0. Have Domoticz latest stable build:  Version: 2023.2 (build 15457)
1. Have Android `Domoticz Premium` application version 0.2.361 (9349)
2. Log in and list devices
3. Log in into web UI and check logs

**Expected behaviour**
I'm worried that API deprecation means `Domoticz Premium` will end it's support.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10.0
 - Domoticz system version 2023.2 (build 15457)
 - Domoticz app version 0.2.361 (9349)

**Comment by kiddigital** [comment]
@ajarzyn , please report this with the App builder as this has to be corrected in the App and not in domoticz.

I know they are aware, but still good idea to report it.

The message itself is not an issue (yet) so no worries.

**Comment by kiddigital** [comment]
@ajarzyn , my bad. You already reported it at the correct place 😁

**Comment by waltervl** [comment]
See also https://github.com/domoticz/domoticz-android/issues/692

**Comment by galadril** [comment]
lets continue on the other topic, closing this one
