### ISSUE TITLE
App doesn't work after upgrade

### ISSUE THREAD

**Issue by jvanderzande** [domoticz/domoticz-android#705]
**Describe the bug**
The app shows OEPS after upgrade and doesn't do anything anymore. See reports on the domoticz forum:
https://www.domoticz.com/forum/viewtopic.php?p=308147

**To Reproduce**
1. upgrade from Domoticz Premium_0.2.361 (9349) to the latest released 
2. start the app

**Expected behavior**
That it works again. ;) 

**Screenshots** !!!
See thread in forum.

**Comment by galadril** [comment]
What's your Domoticz base version, can you update?

**Comment by jvanderzande** [comment]
Running on an older 4.107 version so guess we lost backwards compatibility? Not planning any upgrade soon as there is no real requirement for me and don't want to break my zwave for now.

**Comment by kniazio** [comment]
A warning should have been given that older versions of Domoticz would stop working. I wouldn't install updates.

**Comment by ZaGaPonG** [comment]
Hi,
Same problem here.
As auto-update was checked my Domoticz premium app has been updated tonthe last version during the night.
The Domoticz version is well find by the app so, the connection is OK but no device are displayed.
In addition, working well with the same parameters with the other apps (with subscription plan).
In conclusion, the problem coming exclusively from the last version of the app.
Please make a simple rollback on Android store, easiest way

Thanks in advance

**Comment by kniazio** [comment]
> Hi, Same problem here. As auto-update was checked my Domoticz premium app has been updated to the last version during the night. The Domoticz version is well find by the app so, the connection is OK but no device are displayed. In addition, working well with the same parameters with the other apps (with subscription plan). In conclusion, the problem coming exclusively from the last version of the app. Please make a simple rollback on Android store, easiest way
> 
> Thanks in advance

Tell me how to do it. How to undo an update?

**Comment by ZaGaPonG** [comment]
> > Hi, Same problem here. As auto-update was checked my Domoticz premium app has been updated to the last version during the night. The Domoticz version is well find by the app so, the connection is OK but no device are displayed. In addition, working well with the same parameters with the other apps (with subscription plan). In conclusion, the problem coming exclusively from the last version of the app. Please make a simple rollback on Android store, easiest way
> > Thanks in advance
> 
> Tell me how to do it. How to undo an update?

Not possible for us (users) but the developper just have to publish a new version (based on previous one).
That the easiest way to fix the problem urgently and without waste of time for devs, as this is supposed being an not maintained version

**Comment by galadril** [comment]
_Version 4.10717 (May 9th 2019)_
Sorry, but I'm trying to keep things backwards compatible **until** some level.

Domoticz introduced all kinds of reworked api's:
https://github.com/domoticz/domoticz-android/issues/692

And I'm trying my best to keep things backwards compatible with the new apis, see v1 and v2 DomoticzValues.java here:
https://github.com/domoticz/domoticz-android/commit/b997d5f970ee0c58a8b9a999aa57177ad592af49


But i simple don't have x amount of old Domoticz test systems. So i cant tell you when the app starts to break for these old Domoticz setups.. If you don't update your Domoticz system, please choose then to also not update the app. Don't expect me to keep backwards compatibility for years.

**Comment by jvanderzande** [comment]
Understand and i have made a workaround for these Breaking-Change made in Domoticz by building a reverse proxy config which updates the keywords from New to Old format, which now works fine with the new version! :) 
Details can be found here: https://www.domoticz.com/forum/viewtopic.php?p=308169#p308169

**Comment by galadril** [comment]
Cool, thanks for describing that workaround

**Comment by galadril** [comment]
Ok so im trying to get something fixed for this issue in the next update.
But see this as a best effort

**Comment by jvlerick** [comment]
> _Version 4.10717 (May 9th 2019)_ Sorry, but I'm trying to keep things backwards compatible **until** some level.
> 
> Domoticz introduced all kinds of reworked api's: #692
> 
> And I'm trying my best to keep things backwards compatible with the new apis, see v1 and v2 DomoticzValues.java here: [b997d5f](https://github.com/domoticz/domoticz-android/commit/b997d5f970ee0c58a8b9a999aa57177ad592af49)
> 
> But i simple don't have x amount of old Domoticz test systems. So i cant tell you when the app starts to break for these old Domoticz setups.. If you don't update your Domoticz system, please choose then to also not update the app. Don't expect me to keep backwards compatibility for years.

Why is the Legacy Premium still getting updates if it is no longer supported?
And how come the free app does work fine with exactly the same server configuration and Domoticz version?

**Comment by ZaGaPonG** [comment]
> Ok so im trying to get something fixed for this issue in the next update. But see this as a best effort
 Hi, 
Just updated my Domoticz Premium app from Play Store and work perfectly.
Thank you vert much for this fast update, really appreciated!

Have nice day

**Comment by jvanderzande** [comment]
> Ok so im trying to get something fixed for this issue in the next update. But see this as a best effort

The latest is working fine!    thanks.
