### ISSUE TITLE
Legacy Premium Stopped Working

### ISSUE THREAD

**Issue by Lv2hack** [domoticz/domoticz-android#706]
I understand you don't want to spend time on the old premium version but it recently stopped working for me.  I have not updated Domoticz recently (using 2021.1) yet within the past two weeks the premium app started returning an error about no server data.  I tried clearing the cache and data yet the behavior remains the same. 

The new Android version with ads works fine but I was just wondering why the old version would suddenly stop working?

**Comment by galadril** [comment]
lets continue here
https://github.com/domoticz/domoticz-android/issues/705
