### ISSUE TITLE
Set color for RGBW device problem

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz-android#71]
Hi
I have a Fibaro Zwave RGBW and connected with strip RGBW. But when i change slider on screen color nothing change. I can only change color by click on colors round. For what is this slider ? And for what round in center is cut on two part ?
![screenshot_2016-01-13-20-15-59](https://cloud.githubusercontent.com/assets/4134018/12305298/53324c12-ba34-11e5-825f-dfcb84351548.png)

**Comment by galadril** [comment]
"And for what round in center is cut on two part"
the right side was the last color you've set for this lamp.. (history)

**Comment by pepeEL** [comment]
Ahhh ok
But is any chance to correct working this sliders ?

**Comment by galadril** [comment]
i'll look into them..
But at this moment, domoticz is changing the JSON to support hex color values..

so maybe we should put this on hold, until domoticz is finished with the RGB changes..

**Comment by pepeEL** [comment]
OK thanks... check it as bug on your list.

**Comment by pp1984** [comment]
In version 0.1.222 problem is still...
