### ISSUE TITLE
Support for multiple Domoticz users

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz-android#72]
Please add support for users to i can set app my childreen and i setup on server domoticz for what devices should he visible :)

**Comment by RoadXY** [comment]
Great idea!
Definitively will do this!

**Comment by PiterEL** [comment]
Sorry for duplicate features :)

**Comment by PiterEL** [comment]
ok thanks... But you know when :) ?

**Comment by RoadXY** [comment]
No, sorry

**Comment by galadril** [comment]
Think we first need user support within Domoticz?

**Comment by RoadXY** [comment]
Is already there. You can specify read only users

**Comment by galadril** [comment]
https://github.com/domoticz/domoticz-android/commit/80890d07b6948f827da0f0085407f4d435a51fa5

**Comment by galadril** [comment]
Think we can close this:

![multi user](https://cloud.githubusercontent.com/assets/14561640/14733201/93c8011a-0861-11e6-8093-5ffdb9001538.png)
