### ISSUE TITLE
Geofence - unable to switch protected switch

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#75]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&start=520#p69901

By Skippiemanz » Thu Jan 14, 2016 1:48 am

Receive notification but the switch isn't flipped. Maybe something to do with my virtual switch beeing protected? Switch hasn't been triggered since installation off the app. Using premium version and beta tester. Updated the geofencing settings after the beta update today.

*EDIT* Just turned off the switch protection and the geofencing off the app switched it right away! So please look in to that!

**Comment by RoadXY** [comment]
Password protected devices should pass along a password code like this:

&passcode=xxxxx

http://www.domoticz.com/forum/viewtopic.php?f=6&t=9838

**Comment by RoadXY** [comment]
I think we should have an input field in settings for the password code to be able to switch password protected devices.

**Comment by galadril** [comment]
Started with adding support on protected devices.

![screenshot_20160116-140043](https://cloud.githubusercontent.com/assets/14561640/12372489/ebe82b76-bc59-11e5-9261-7e09bf3a5cbd.png)  

![screenshot_20160116-140049](https://cloud.githubusercontent.com/assets/14561640/12372488/ebe74ce2-bc59-11e5-9a63-91dd34647f5f.png)  

![screenshot_20160116-140038](https://cloud.githubusercontent.com/assets/14561640/12372487/ebe6efea-bc59-11e5-9caf-3d1694b2880c.png)  


Todo, protected devices in: 
geofences, widgets, wear

**Comment by galadril** [comment]
We can close this issue:
https://github.com/domoticz/domoticz-android/commit/eae188771afc355a0ea5b6814b72c2539e30dccd
