### ISSUE TITLE
Enhance error messages

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#76]
Currently error messages displayed are the messages provided by  JSON or the VolleyUtil.
If the result is empty we should look for error messages like in the example below:

}
"message" : "WRONG CODE",
"status" : "ERROR",
"title" : "SwitchLight"
}

**Comment by galadril** [comment]
I now give the error message to the parser.OnError

**Comment by galadril** [comment]
I now give the exception back to the ErrorHandling method.. so this one can then probably be closed?
