### ISSUE TITLE
Quick Access to Domoticz Notification Settings

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#78]
More on this here:
https://plus.google.com/+CyrilMottier/posts/YY6tbJrJMra

![device-2016-01-14-203519](https://cloud.githubusercontent.com/assets/3482284/12335594/4ab0d50a-bb00-11e5-8bdf-a8bb5fed91b7.png)
![device-2016-01-14-203738](https://cloud.githubusercontent.com/assets/3482284/12335600/54917b1a-bb00-11e5-878e-974bddb2d656.png)

**Comment by galadril** [comment]
Nicely done!

**Comment by RoadXY** [comment]
Did you try it? :-)

**Comment by galadril** [comment]
ja natuurlijk, wist niet eens dat het kon ;)

**Comment by RoadXY** [comment]
Toch een nice touch vind ik zulke kleine dingen altijd :-D

**Comment by galadril** [comment]
Klopt!
