### ISSUE TITLE
Custom sorting of all lists

### ISSUE THREAD

**Issue by RoadXY** [domoticz/domoticz-android#8]
Custom sorting of every screen

**Comment by galadril** [comment]
Would love to implement drag and drop to sort a listview...

**Comment by RoadXY** [comment]
Saw you implemented Nick Haarman's listview adapter which is a start to this!
This commit: https://github.com/domoticz/domoticz-android/commit/dc769e8a0a966b234dd1f35ac91fc2a0759fd9a1

**Comment by galadril** [comment]
Finished the implementation on drag/drop

**Comment by galadril** [comment]
See result:
https://user-images.githubusercontent.com/14561640/47802675-1b8a8900-dd31-11e8-96cc-1a6b1e3dd96e.gif
